/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const addAssignmentBodyRoleEnum = {
  Owner: "Owner",
  Collaborator: "Collaborator",
} as const;

export type AddAssignmentBodyRoleEnumKey =
  (typeof addAssignmentBodyRoleEnum)[keyof typeof addAssignmentBodyRoleEnum];

export type AddAssignmentBody = {
  /**
   * @description UUID of the user being assigned
   * @type string, uuid
   */
  userId: string;
  /**
   * @description Assignment role
   * @type string
   */
  role: AddAssignmentBodyRoleEnumKey;
};
