/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AddBudgetItemBody = {
  /**
   * @description Budget item description
   * @minLength 1
   * @type string
   */
  concept: string;
  /**
   * @description Amount in minor currency units (e.g. cents)
   * @minLength 0
   * @type integer
   */
  amountMinor: number;
};
