/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const addResponsibleBodyRoleEnum = {
  Lead: "Lead",
  Member: "Member",
} as const;

export type AddResponsibleBodyRoleEnumKey =
  (typeof addResponsibleBodyRoleEnum)[keyof typeof addResponsibleBodyRoleEnum];

export type AddResponsibleBody = {
  /**
   * @description UUID of the user being assigned
   * @type string, uuid
   */
  userId: string;
  /**
   * @description Responsible role
   * @type string
   */
  role: AddResponsibleBodyRoleEnumKey;
};
