/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BulkDeleteProjectsBody = {
  /**
   * @description IDs of projects to soft-delete (1 to 500).
   * @type array
   */
  ids: string[];
};
