/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BulkDeleteContactsBody = {
  /**
   * @description IDs of contacts to soft-delete (1 to 500).
   * @type array
   */
  ids: string[];
};
