/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const changeProjectStateBodyNewStateEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type ChangeProjectStateBodyNewStateEnumKey =
  (typeof changeProjectStateBodyNewStateEnum)[keyof typeof changeProjectStateBodyNewStateEnum];

export type ChangeProjectStateBody = {
  /**
   * @description Target project status
   * @type string
   */
  newState: ChangeProjectStateBodyNewStateEnumKey;
};
