/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const changeStateBodyNewStateEnum = {
  Contact: "Contact",
  Lead: "Lead",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type ChangeStateBodyNewStateEnumKey =
  (typeof changeStateBodyNewStateEnum)[keyof typeof changeStateBodyNewStateEnum];

export type ChangeStateBody = {
  /**
   * @description Target pipeline state
   * @type string
   */
  newState: ChangeStateBodyNewStateEnumKey;
};
