/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const contactStateChangeViewPreviousStateEnum = {
  Contact: "Contact",
  Lead: "Lead",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type ContactStateChangeViewPreviousStateEnumKey =
  (typeof contactStateChangeViewPreviousStateEnum)[keyof typeof contactStateChangeViewPreviousStateEnum];

export const contactStateChangeViewNextStateEnum = {
  Contact: "Contact",
  Lead: "Lead",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type ContactStateChangeViewNextStateEnumKey =
  (typeof contactStateChangeViewNextStateEnum)[keyof typeof contactStateChangeViewNextStateEnum];

export type ContactStateChangeView = {
  /**
   * @description State change UUID
   * @type string
   */
  id: string;
  /**
   * @description Contact UUID
   * @type string
   */
  contactId: string;
  /**
   * @type string
   */
  previousState: ContactStateChangeViewPreviousStateEnumKey;
  /**
   * @type string
   */
  nextState: ContactStateChangeViewNextStateEnumKey;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  changedAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
};
