/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const contactEventViewEventTypeEnum = {
  FirstContact: "FirstContact",
  MessageSent: "MessageSent",
  ResponseReceived: "ResponseReceived",
  MeetingCall: "MeetingCall",
  ProposalSent: "ProposalSent",
  ProposalWon: "ProposalWon",
  ProposalRejected: "ProposalRejected",
  FollowUpPending: "FollowUpPending",
  Note: "Note",
} as const;

export type ContactEventViewEventTypeEnumKey =
  (typeof contactEventViewEventTypeEnum)[keyof typeof contactEventViewEventTypeEnum];

export type ContactEventView = {
  /**
   * @description Event UUID
   * @type string
   */
  id: string;
  /**
   * @description Contact UUID
   * @type string
   */
  contactId: string;
  /**
   * @description User UUID who authored the event
   * @type string
   */
  authorId: string;
  /**
   * @type string
   */
  eventType: ContactEventViewEventTypeEnumKey;
  /**
   * @type string
   */
  detail: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  occurredAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
};
