/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const contactViewContactTypeEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactViewContactTypeEnumKey =
  (typeof contactViewContactTypeEnum)[keyof typeof contactViewContactTypeEnum];

export const contactViewSexEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type ContactViewSexEnumKey =
  (typeof contactViewSexEnum)[keyof typeof contactViewSexEnum];

export const contactViewPipelineStateEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type ContactViewPipelineStateEnumKey =
  (typeof contactViewPipelineStateEnum)[keyof typeof contactViewPipelineStateEnum];

export const contactViewSourceChannelEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type ContactViewSourceChannelEnumKey =
  (typeof contactViewSourceChannelEnum)[keyof typeof contactViewSourceChannelEnum];

export const contactViewInterestLevelEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type ContactViewInterestLevelEnumKey =
  (typeof contactViewInterestLevelEnum)[keyof typeof contactViewInterestLevelEnum];

export const channelsChannelTypeEnum = {
  Phone: "Phone",
  Email: "Email",
  WhatsApp: "WhatsApp",
  Instagram: "Instagram",
  Website: "Website",
  Other: "Other",
} as const;

export type ChannelsChannelTypeEnumKey =
  (typeof channelsChannelTypeEnum)[keyof typeof channelsChannelTypeEnum];

export type ContactView = {
  /**
   * @description Contact UUID
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  contactType: ContactViewContactTypeEnumKey;
  /**
   * @type string
   */
  sex: ContactViewSexEnumKey | null;
  /**
   * @type string
   */
  addressStreet: string | null;
  /**
   * @type string
   */
  addressNumber: string | null;
  /**
   * @type string
   */
  addressPostalCode: string | null;
  /**
   * @type string
   */
  addressCity: string | null;
  /**
   * @type string
   */
  addressProvince: string | null;
  /**
   * @type string
   */
  addressCountry: string | null;
  /**
   * @type string
   */
  notes: string | null;
  /**
   * @type string
   */
  pipelineState: ContactViewPipelineStateEnumKey;
  /**
   * @type string
   */
  sourceChannel: ContactViewSourceChannelEnumKey | null;
  /**
   * @type string
   */
  interestLevel: ContactViewInterestLevelEnumKey | null;
  /**
   * @description User UUID who created this contact
   * @type string
   */
  createdBy: string;
  /**
   * @description Creator user data. Present on detail endpoint.
   * @type object | undefined
   */
  creator?: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    name: string;
  };
  /**
   * @description Communication channels
   * @type array
   */
  channels: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    channelType: ChannelsChannelTypeEnumKey;
    /**
     * @type string
     */
    value: string;
    /**
     * @type boolean
     */
    isPrimary: boolean;
  }[];
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  updatedAt: string;
};
