/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const contactAssignmentListItemRoleEnum = {
  Owner: "Owner",
  Collaborator: "Collaborator",
} as const;

export type ContactAssignmentListItemRoleEnumKey =
  (typeof contactAssignmentListItemRoleEnum)[keyof typeof contactAssignmentListItemRoleEnum];

export type ContactAssignmentListItem = {
  /**
   * @description UUID of the assigned user
   * @type string
   */
  userId: string;
  /**
   * @description Display name of the assigned user
   * @type string
   */
  userName: string;
  /**
   * @type string
   */
  role: ContactAssignmentListItemRoleEnumKey;
  /**
   * @description UUID of the user that performed the assignment
   * @type string
   */
  assignedBy: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  assignedAt: string;
};
