/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const statesStateEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type StatesStateEnumKey =
  (typeof statesStateEnum)[keyof typeof statesStateEnum];

export type ContactKpisResponse = {
  /**
   * @type object
   */
  total: {
    /**
     * @minLength 0
     * @type integer
     */
    count: number;
    /**
     * @minLength 0
     * @type integer
     */
    current: number;
    /**
     * @minLength 0
     * @type integer
     */
    previous: number;
  };
  /**
   * @type array
   */
  states: {
    /**
     * @type string
     */
    state: StatesStateEnumKey;
    /**
     * @minLength 0
     * @type integer
     */
    current: number;
    /**
     * @minLength 0
     * @type integer
     */
    previous: number;
  }[];
};
