/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateUserBody = {
  /**
   * @description User email (unique)
   * @type string, email
   */
  email: string;
  /**
   * @description User full name
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @description Password (>= 8 chars)
   * @minLength 8
   * @type string
   */
  password: string;
};
