/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProjectBody = {
  /**
   * @description Project name
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @description Project description
   * @type string
   */
  description?: string | null;
  /**
   * @description UUID of the associated contact
   * @type string, uuid
   */
  contactId: string;
  /**
   * @description ISO 4217 currency code
   * @minLength 3
   * @maxLength 3
   * @type string
   */
  currency: string;
  /**
   * @description Project start date (YYYY-MM-DD)
   * @type string, date
   */
  startDate: string;
  /**
   * @description Project planned end date (YYYY-MM-DD)
   * @type string, date
   */
  plannedEndDate: string;
};
