/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type DeleteProjectsIdExpensesExpenseidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  expenseId: string;
};

/**
 * @description Expense removed. Returns updated project.
 */
export type DeleteProjectsIdExpensesExpenseid200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type DeleteProjectsIdExpensesExpenseid401 = Problem;

/**
 * @description Project or expense not found.
 */
export type DeleteProjectsIdExpensesExpenseid404 = Problem;

export type DeleteProjectsIdExpensesExpenseidMutationResponse =
  DeleteProjectsIdExpensesExpenseid200;

export type DeleteProjectsIdExpensesExpenseidMutation = {
  Response: DeleteProjectsIdExpensesExpenseid200;
  PathParams: DeleteProjectsIdExpensesExpenseidPathParams;
  Errors:
    | DeleteProjectsIdExpensesExpenseid401
    | DeleteProjectsIdExpensesExpenseid404;
};
