/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";

export type DeleteContactsIdAssignmentsUseridPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  userId: string;
};

/**
 * @description Assignment removed. Returns updated contact.
 */
export type DeleteContactsIdAssignmentsUserid200 = ContactView;

/**
 * @description Unauthorized.
 */
export type DeleteContactsIdAssignmentsUserid401 = Problem;

/**
 * @description Contact or assignment not found.
 */
export type DeleteContactsIdAssignmentsUserid404 = Problem;

export type DeleteContactsIdAssignmentsUseridMutationResponse =
  DeleteContactsIdAssignmentsUserid200;

export type DeleteContactsIdAssignmentsUseridMutation = {
  Response: DeleteContactsIdAssignmentsUserid200;
  PathParams: DeleteContactsIdAssignmentsUseridPathParams;
  Errors:
    | DeleteContactsIdAssignmentsUserid401
    | DeleteContactsIdAssignmentsUserid404;
};
