/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type DeleteProjectsIdDocumentsDocidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  docId: string;
};

/**
 * @description Document deleted.
 */
export type DeleteProjectsIdDocumentsDocid204 = any;

/**
 * @description Unauthorized.
 */
export type DeleteProjectsIdDocumentsDocid401 = Problem;

/**
 * @description Project or document not found.
 */
export type DeleteProjectsIdDocumentsDocid404 = Problem;

export type DeleteProjectsIdDocumentsDocidMutationResponse =
  DeleteProjectsIdDocumentsDocid204;

export type DeleteProjectsIdDocumentsDocidMutation = {
  Response: DeleteProjectsIdDocumentsDocid204;
  PathParams: DeleteProjectsIdDocumentsDocidPathParams;
  Errors: DeleteProjectsIdDocumentsDocid401 | DeleteProjectsIdDocumentsDocid404;
};
