/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type DeleteAnalysisTemplatesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Template deactivated.
 */
export type DeleteAnalysisTemplatesId200 = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  rubro: string;
  /**
   * @type string
   */
  prompt: string;
  /**
   * @type string
   */
  modelProvider: string;
  /**
   * @type integer
   */
  version: number;
  /**
   * @type boolean
   */
  isActive: boolean;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};

/**
 * @description Unauthorized.
 */
export type DeleteAnalysisTemplatesId401 = Problem;

/**
 * @description Template not found.
 */
export type DeleteAnalysisTemplatesId404 = Problem;

export type DeleteAnalysisTemplatesIdMutationResponse =
  DeleteAnalysisTemplatesId200;

export type DeleteAnalysisTemplatesIdMutation = {
  Response: DeleteAnalysisTemplatesId200;
  PathParams: DeleteAnalysisTemplatesIdPathParams;
  Errors: DeleteAnalysisTemplatesId401 | DeleteAnalysisTemplatesId404;
};
