/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";

export type DeleteContactsIdChannelsChannelidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  channelId: string;
};

/**
 * @description Channel removed. Returns updated contact.
 */
export type DeleteContactsIdChannelsChannelid200 = ContactView;

/**
 * @description Unauthorized.
 */
export type DeleteContactsIdChannelsChannelid401 = Problem;

/**
 * @description Contact not found.
 */
export type DeleteContactsIdChannelsChannelid404 = Problem;

export type DeleteContactsIdChannelsChannelidMutationResponse =
  DeleteContactsIdChannelsChannelid200;

export type DeleteContactsIdChannelsChannelidMutation = {
  Response: DeleteContactsIdChannelsChannelid200;
  PathParams: DeleteContactsIdChannelsChannelidPathParams;
  Errors:
    | DeleteContactsIdChannelsChannelid401
    | DeleteContactsIdChannelsChannelid404;
};
