/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type DeleteContactsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Contact deleted.
 */
export type DeleteContactsId204 = any;

/**
 * @description Unauthorized.
 */
export type DeleteContactsId401 = Problem;

/**
 * @description Contact not found.
 */
export type DeleteContactsId404 = Problem;

export type DeleteContactsIdMutationResponse = DeleteContactsId204;

export type DeleteContactsIdMutation = {
  Response: DeleteContactsId204;
  PathParams: DeleteContactsIdPathParams;
  Errors: DeleteContactsId401 | DeleteContactsId404;
};
