/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type DeleteUsersIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description User deleted.
 */
export type DeleteUsersId204 = any;

/**
 * @description Unauthorized.
 */
export type DeleteUsersId401 = Problem;

/**
 * @description User not found.
 */
export type DeleteUsersId404 = Problem;

export type DeleteUsersIdMutationResponse = DeleteUsersId204;

export type DeleteUsersIdMutation = {
  Response: DeleteUsersId204;
  PathParams: DeleteUsersIdPathParams;
  Errors: DeleteUsersId401 | DeleteUsersId404;
};
