/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type DeleteProjectsIdExtensionsExtidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  extId: string;
};

/**
 * @description Extension removed. Returns updated project.
 */
export type DeleteProjectsIdExtensionsExtid200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type DeleteProjectsIdExtensionsExtid401 = Problem;

/**
 * @description Project or extension not found.
 */
export type DeleteProjectsIdExtensionsExtid404 = Problem;

export type DeleteProjectsIdExtensionsExtidMutationResponse =
  DeleteProjectsIdExtensionsExtid200;

export type DeleteProjectsIdExtensionsExtidMutation = {
  Response: DeleteProjectsIdExtensionsExtid200;
  PathParams: DeleteProjectsIdExtensionsExtidPathParams;
  Errors:
    | DeleteProjectsIdExtensionsExtid401
    | DeleteProjectsIdExtensionsExtid404;
};
