/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type DeleteProjectsIdBudgetItemsItemidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  itemId: string;
};

/**
 * @description Budget item removed. Returns updated project.
 */
export type DeleteProjectsIdBudgetItemsItemid200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type DeleteProjectsIdBudgetItemsItemid401 = Problem;

/**
 * @description Project or budget item not found.
 */
export type DeleteProjectsIdBudgetItemsItemid404 = Problem;

export type DeleteProjectsIdBudgetItemsItemidMutationResponse =
  DeleteProjectsIdBudgetItemsItemid200;

export type DeleteProjectsIdBudgetItemsItemidMutation = {
  Response: DeleteProjectsIdBudgetItemsItemid200;
  PathParams: DeleteProjectsIdBudgetItemsItemidPathParams;
  Errors:
    | DeleteProjectsIdBudgetItemsItemid401
    | DeleteProjectsIdBudgetItemsItemid404;
};
