/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FilterGroupObject = {
  /**
   * @type object | undefined
   */
  id?: {
    eq?: string | string[];
    ne?: string | string[];
    in?: string | string[];
    nin?: string | string[];
    isNull?: string | string[];
    isNotNull?: string | string[];
  };
  /**
   * @type object | undefined
   */
  email?: {
    eq?: string | string[];
    ne?: string | string[];
    in?: string | string[];
    nin?: string | string[];
    ilike?: string | string[];
    isNull?: string | string[];
    isNotNull?: string | string[];
  };
  /**
   * @type object | undefined
   */
  name?: {
    eq?: string | string[];
    ne?: string | string[];
    in?: string | string[];
    nin?: string | string[];
    ilike?: string | string[];
    isNull?: string | string[];
    isNotNull?: string | string[];
  };
  /**
   * @type object | undefined
   */
  createdAt?: {
    eq?: string | string[];
    ne?: string | string[];
    gt?: string | string[];
    gte?: string | string[];
    lt?: string | string[];
    lte?: string | string[];
    between?: string | string[];
    isNull?: string | string[];
    isNotNull?: string | string[];
  };
  /**
   * @type object | undefined
   */
  updatedAt?: {
    eq?: string | string[];
    ne?: string | string[];
    gt?: string | string[];
    gte?: string | string[];
    lt?: string | string[];
    lte?: string | string[];
    between?: string | string[];
    isNull?: string | string[];
    isNotNull?: string | string[];
  };
};
