/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactAssignmentListResponse } from "./ContactAssignmentListResponse.ts";
import type { Problem } from "./Problem.ts";

export type GetContactsIdAssignmentsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Paginated list of assignments.
 */
export type GetContactsIdAssignments200 = ContactAssignmentListResponse;

/**
 * @description Unauthorized.
 */
export type GetContactsIdAssignments401 = Problem;

/**
 * @description Contact not found.
 */
export type GetContactsIdAssignments404 = Problem;

export type GetContactsIdAssignmentsQueryResponse = GetContactsIdAssignments200;

export type GetContactsIdAssignmentsQuery = {
  Response: GetContactsIdAssignments200;
  PathParams: GetContactsIdAssignmentsPathParams;
  Errors: GetContactsIdAssignments401 | GetContactsIdAssignments404;
};
