/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactListResponse } from "./ContactListResponse.ts";
import type { FilterGroupObject } from "./FilterGroupObject.ts";
import type { Pagination } from "./Pagination.ts";
import type { Problem } from "./Problem.ts";

export const contactTypeEqEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactTypeEqEnumKey =
  (typeof contactTypeEqEnum)[keyof typeof contactTypeEqEnum];

export const contactTypeNeEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactTypeNeEnumKey =
  (typeof contactTypeNeEnum)[keyof typeof contactTypeNeEnum];

export const contactTypeInEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactTypeInEnumKey =
  (typeof contactTypeInEnum)[keyof typeof contactTypeInEnum];

export const contactTypeNinEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactTypeNinEnumKey =
  (typeof contactTypeNinEnum)[keyof typeof contactTypeNinEnum];

export const contactTypeIsNullEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactTypeIsNullEnumKey =
  (typeof contactTypeIsNullEnum)[keyof typeof contactTypeIsNullEnum];

export const contactTypeIsNotNullEnum = {
  Person: "Person",
  Company: "Company",
} as const;

export type ContactTypeIsNotNullEnumKey =
  (typeof contactTypeIsNotNullEnum)[keyof typeof contactTypeIsNotNullEnum];

export const sexEqEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type SexEqEnumKey = (typeof sexEqEnum)[keyof typeof sexEqEnum];

export const sexNeEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type SexNeEnumKey = (typeof sexNeEnum)[keyof typeof sexNeEnum];

export const sexInEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type SexInEnumKey = (typeof sexInEnum)[keyof typeof sexInEnum];

export const sexNinEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type SexNinEnumKey = (typeof sexNinEnum)[keyof typeof sexNinEnum];

export const sexIsNullEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type SexIsNullEnumKey =
  (typeof sexIsNullEnum)[keyof typeof sexIsNullEnum];

export const sexIsNotNullEnum = {
  Male: "Male",
  Female: "Female",
  Other: "Other",
  Unspecified: "Unspecified",
} as const;

export type SexIsNotNullEnumKey =
  (typeof sexIsNotNullEnum)[keyof typeof sexIsNotNullEnum];

export const pipelineStateEqEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type PipelineStateEqEnumKey =
  (typeof pipelineStateEqEnum)[keyof typeof pipelineStateEqEnum];

export const pipelineStateNeEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type PipelineStateNeEnumKey =
  (typeof pipelineStateNeEnum)[keyof typeof pipelineStateNeEnum];

export const pipelineStateInEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type PipelineStateInEnumKey =
  (typeof pipelineStateInEnum)[keyof typeof pipelineStateInEnum];

export const pipelineStateNinEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type PipelineStateNinEnumKey =
  (typeof pipelineStateNinEnum)[keyof typeof pipelineStateNinEnum];

export const pipelineStateIsNullEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type PipelineStateIsNullEnumKey =
  (typeof pipelineStateIsNullEnum)[keyof typeof pipelineStateIsNullEnum];

export const pipelineStateIsNotNullEnum = {
  Contact: "Contact",
  Lead: "Lead",
  AtRisk: "AtRisk",
  Customer: "Customer",
  Discarded: "Discarded",
} as const;

export type PipelineStateIsNotNullEnumKey =
  (typeof pipelineStateIsNotNullEnum)[keyof typeof pipelineStateIsNotNullEnum];

export const sourceChannelEqEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type SourceChannelEqEnumKey =
  (typeof sourceChannelEqEnum)[keyof typeof sourceChannelEqEnum];

export const sourceChannelNeEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type SourceChannelNeEnumKey =
  (typeof sourceChannelNeEnum)[keyof typeof sourceChannelNeEnum];

export const sourceChannelInEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type SourceChannelInEnumKey =
  (typeof sourceChannelInEnum)[keyof typeof sourceChannelInEnum];

export const sourceChannelNinEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type SourceChannelNinEnumKey =
  (typeof sourceChannelNinEnum)[keyof typeof sourceChannelNinEnum];

export const sourceChannelIsNullEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type SourceChannelIsNullEnumKey =
  (typeof sourceChannelIsNullEnum)[keyof typeof sourceChannelIsNullEnum];

export const sourceChannelIsNotNullEnum = {
  Instagram: "Instagram",
  WhatsApp: "WhatsApp",
  Referral: "Referral",
  Email: "Email",
  Other: "Other",
} as const;

export type SourceChannelIsNotNullEnumKey =
  (typeof sourceChannelIsNotNullEnum)[keyof typeof sourceChannelIsNotNullEnum];

export const interestLevelEqEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type InterestLevelEqEnumKey =
  (typeof interestLevelEqEnum)[keyof typeof interestLevelEqEnum];

export const interestLevelNeEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type InterestLevelNeEnumKey =
  (typeof interestLevelNeEnum)[keyof typeof interestLevelNeEnum];

export const interestLevelInEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type InterestLevelInEnumKey =
  (typeof interestLevelInEnum)[keyof typeof interestLevelInEnum];

export const interestLevelNinEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type InterestLevelNinEnumKey =
  (typeof interestLevelNinEnum)[keyof typeof interestLevelNinEnum];

export const interestLevelIsNullEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type InterestLevelIsNullEnumKey =
  (typeof interestLevelIsNullEnum)[keyof typeof interestLevelIsNullEnum];

export const interestLevelIsNotNullEnum = {
  Cold: "Cold",
  Warm: "Warm",
  Hot: "Hot",
} as const;

export type InterestLevelIsNotNullEnumKey =
  (typeof interestLevelIsNotNullEnum)[keyof typeof interestLevelIsNotNullEnum];

export type GetContactsQueryParams = {
  /**
   * @type object | undefined
   */
  filter?: {
    /**
     * @type object | undefined
     */
    id?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    name?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    contactType?: {
      eq?: ContactTypeEqEnumKey | ContactTypeEqEnumKey[];
      ne?: ContactTypeNeEnumKey | ContactTypeNeEnumKey[];
      in?: ContactTypeInEnumKey | ContactTypeInEnumKey[];
      nin?: ContactTypeNinEnumKey | ContactTypeNinEnumKey[];
      isNull?: ContactTypeIsNullEnumKey | ContactTypeIsNullEnumKey[];
      isNotNull?: ContactTypeIsNotNullEnumKey | ContactTypeIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    sex?: {
      eq?: SexEqEnumKey | SexEqEnumKey[];
      ne?: SexNeEnumKey | SexNeEnumKey[];
      in?: SexInEnumKey | SexInEnumKey[];
      nin?: SexNinEnumKey | SexNinEnumKey[];
      isNull?: SexIsNullEnumKey | SexIsNullEnumKey[];
      isNotNull?: SexIsNotNullEnumKey | SexIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    addressStreet?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    addressNumber?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    addressPostalCode?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    addressCity?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    addressProvince?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    addressCountry?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    notes?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    pipelineState?: {
      eq?: PipelineStateEqEnumKey | PipelineStateEqEnumKey[];
      ne?: PipelineStateNeEnumKey | PipelineStateNeEnumKey[];
      in?: PipelineStateInEnumKey | PipelineStateInEnumKey[];
      nin?: PipelineStateNinEnumKey | PipelineStateNinEnumKey[];
      isNull?: PipelineStateIsNullEnumKey | PipelineStateIsNullEnumKey[];
      isNotNull?:
        | PipelineStateIsNotNullEnumKey
        | PipelineStateIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    sourceChannel?: {
      eq?: SourceChannelEqEnumKey | SourceChannelEqEnumKey[];
      ne?: SourceChannelNeEnumKey | SourceChannelNeEnumKey[];
      in?: SourceChannelInEnumKey | SourceChannelInEnumKey[];
      nin?: SourceChannelNinEnumKey | SourceChannelNinEnumKey[];
      isNull?: SourceChannelIsNullEnumKey | SourceChannelIsNullEnumKey[];
      isNotNull?:
        | SourceChannelIsNotNullEnumKey
        | SourceChannelIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    interestLevel?: {
      eq?: InterestLevelEqEnumKey | InterestLevelEqEnumKey[];
      ne?: InterestLevelNeEnumKey | InterestLevelNeEnumKey[];
      in?: InterestLevelInEnumKey | InterestLevelInEnumKey[];
      nin?: InterestLevelNinEnumKey | InterestLevelNinEnumKey[];
      isNull?: InterestLevelIsNullEnumKey | InterestLevelIsNullEnumKey[];
      isNotNull?:
        | InterestLevelIsNotNullEnumKey
        | InterestLevelIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    createdBy?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    createdAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    updatedAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    deletedAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type array | undefined
     */
    or?: FilterGroupObject[];
  };
  /**
   * @minLength 1
   * @type string | undefined
   */
  search?: string;
  /**
   * @type object | undefined
   */
  pagination?: Pagination;
  /**
   * @type string | undefined
   */
  sort?: string;
};

/**
 * @description Paginated list of contacts.
 */
export type GetContacts200 = ContactListResponse;

/**
 * @description Unauthorized.
 */
export type GetContacts401 = Problem;

export type GetContactsQueryResponse = GetContacts200;

export type GetContactsQuery = {
  Response: GetContacts200;
  QueryParams: GetContactsQueryParams;
  Errors: GetContacts401;
};
