/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";

export type GetContactsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Contact found.
 */
export type GetContactsId200 = ContactView;

/**
 * @description Unauthorized.
 */
export type GetContactsId401 = Problem;

/**
 * @description Contact not found.
 */
export type GetContactsId404 = Problem;

export type GetContactsIdQueryResponse = GetContactsId200;

export type GetContactsIdQuery = {
  Response: GetContactsId200;
  PathParams: GetContactsIdPathParams;
  Errors: GetContactsId401 | GetContactsId404;
};
