/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactStateChangeListResponse } from "./ContactStateChangeListResponse.ts";
import type { Problem } from "./Problem.ts";

export type GetContactsIdStateChangesPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Paginated list of state changes.
 */
export type GetContactsIdStateChanges200 = ContactStateChangeListResponse;

/**
 * @description Unauthorized.
 */
export type GetContactsIdStateChanges401 = Problem;

/**
 * @description Contact not found.
 */
export type GetContactsIdStateChanges404 = Problem;

export type GetContactsIdStateChangesQueryResponse =
  GetContactsIdStateChanges200;

export type GetContactsIdStateChangesQuery = {
  Response: GetContactsIdStateChanges200;
  PathParams: GetContactsIdStateChangesPathParams;
  Errors: GetContactsIdStateChanges401 | GetContactsIdStateChanges404;
};
