/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactEventListResponse } from "./ContactEventListResponse.ts";
import type { Problem } from "./Problem.ts";

export type GetContactsIdEventsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Paginated list of events.
 */
export type GetContactsIdEvents200 = ContactEventListResponse;

/**
 * @description Unauthorized.
 */
export type GetContactsIdEvents401 = Problem;

/**
 * @description Contact not found.
 */
export type GetContactsIdEvents404 = Problem;

export type GetContactsIdEventsQueryResponse = GetContactsIdEvents200;

export type GetContactsIdEventsQuery = {
  Response: GetContactsIdEvents200;
  PathParams: GetContactsIdEventsPathParams;
  Errors: GetContactsIdEvents401 | GetContactsIdEvents404;
};
