/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactKpisResponse } from "./ContactKpisResponse.ts";
import type { Problem } from "./Problem.ts";

/**
 * @description Pipeline KPIs for current and previous 30-day windows.
 */
export type GetContactsKpis200 = ContactKpisResponse;

/**
 * @description Unauthorized.
 */
export type GetContactsKpis401 = Problem;

export type GetContactsKpisQueryResponse = GetContactsKpis200;

export type GetContactsKpisQuery = {
  Response: GetContactsKpis200;
  Errors: GetContactsKpis401;
};
