/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type GetEnrichmentsQueryParams = {
  /**
   * @type string, uuid
   */
  contactId: string;
};

export const getEnrichments200TriggerKindEnum = {
  post_import: "post_import",
  batch: "batch",
  individual: "individual",
  retry: "retry",
} as const;

export type GetEnrichments200TriggerKindEnumKey =
  (typeof getEnrichments200TriggerKindEnum)[keyof typeof getEnrichments200TriggerKindEnum];

export const getEnrichments200StatusEnum = {
  queued: "queued",
  processing: "processing",
  completed: "completed",
  failed: "failed",
} as const;

export type GetEnrichments200StatusEnumKey =
  (typeof getEnrichments200StatusEnum)[keyof typeof getEnrichments200StatusEnum];

/**
 * @description Insights for the given contact, newest first.
 */
export type GetEnrichments200 = GetEnrichments200TriggerKindEnumKey[];

/**
 * @description Missing or invalid contactId.
 */
export type GetEnrichments400 = Problem;

/**
 * @description Unauthorized.
 */
export type GetEnrichments401 = Problem;

export type GetEnrichmentsQueryResponse = GetEnrichments200;

export type GetEnrichmentsQuery = {
  Response: GetEnrichments200;
  QueryParams: GetEnrichmentsQueryParams;
  Errors: GetEnrichments400 | GetEnrichments401;
};
