/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImportListResponse } from "./ImportListResponse.ts";
import type { Problem } from "./Problem.ts";

export type GetImportsQueryParams = {
  /**
   * @description Number of items to return
   * @minLength 1
   * @maxLength 100
   * @default 20
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Number of items to skip
   * @minLength 0
   * @default 0
   * @type integer
   */
  offset?: number | null;
};

/**
 * @description Paginated list of imports, newest first.
 */
export type GetImports200 = ImportListResponse;

/**
 * @description Unauthorized.
 */
export type GetImports401 = Problem;

export type GetImportsQueryResponse = GetImports200;

export type GetImportsQuery = {
  Response: GetImports200;
  QueryParams: GetImportsQueryParams;
  Errors: GetImports401;
};
