/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImportStatusResponse } from "./ImportStatusResponse.ts";
import type { Problem } from "./Problem.ts";

export type GetImportsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Import status with progress counters and optional rejected.csv link.
 */
export type GetImportsId200 = ImportStatusResponse;

/**
 * @description Unauthorized.
 */
export type GetImportsId401 = Problem;

/**
 * @description Import not found.
 */
export type GetImportsId404 = Problem;

export type GetImportsIdQueryResponse = GetImportsId200;

export type GetImportsIdQuery = {
  Response: GetImportsId200;
  PathParams: GetImportsIdPathParams;
  Errors: GetImportsId401 | GetImportsId404;
};
