/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FilterGroupObject } from "./FilterGroupObject.ts";
import type { Pagination } from "./Pagination.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectStateChangeListResponse } from "./ProjectStateChangeListResponse.ts";

export type GetProjectsIdStateChangesPathParams = {
  /**
   * @type string
   */
  id: string;
};

export const previousStateEqEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type PreviousStateEqEnumKey =
  (typeof previousStateEqEnum)[keyof typeof previousStateEqEnum];

export const previousStateNeEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type PreviousStateNeEnumKey =
  (typeof previousStateNeEnum)[keyof typeof previousStateNeEnum];

export const previousStateInEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type PreviousStateInEnumKey =
  (typeof previousStateInEnum)[keyof typeof previousStateInEnum];

export const previousStateNinEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type PreviousStateNinEnumKey =
  (typeof previousStateNinEnum)[keyof typeof previousStateNinEnum];

export const previousStateIsNullEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type PreviousStateIsNullEnumKey =
  (typeof previousStateIsNullEnum)[keyof typeof previousStateIsNullEnum];

export const previousStateIsNotNullEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type PreviousStateIsNotNullEnumKey =
  (typeof previousStateIsNotNullEnum)[keyof typeof previousStateIsNotNullEnum];

export const nextStateEqEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type NextStateEqEnumKey =
  (typeof nextStateEqEnum)[keyof typeof nextStateEqEnum];

export const nextStateNeEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type NextStateNeEnumKey =
  (typeof nextStateNeEnum)[keyof typeof nextStateNeEnum];

export const nextStateInEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type NextStateInEnumKey =
  (typeof nextStateInEnum)[keyof typeof nextStateInEnum];

export const nextStateNinEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type NextStateNinEnumKey =
  (typeof nextStateNinEnum)[keyof typeof nextStateNinEnum];

export const nextStateIsNullEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type NextStateIsNullEnumKey =
  (typeof nextStateIsNullEnum)[keyof typeof nextStateIsNullEnum];

export const nextStateIsNotNullEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type NextStateIsNotNullEnumKey =
  (typeof nextStateIsNotNullEnum)[keyof typeof nextStateIsNotNullEnum];

export type GetProjectsIdStateChangesQueryParams = {
  /**
   * @type object | undefined
   */
  filter?: {
    /**
     * @type object | undefined
     */
    id?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    previousState?: {
      eq?: PreviousStateEqEnumKey | PreviousStateEqEnumKey[];
      ne?: PreviousStateNeEnumKey | PreviousStateNeEnumKey[];
      in?: PreviousStateInEnumKey | PreviousStateInEnumKey[];
      nin?: PreviousStateNinEnumKey | PreviousStateNinEnumKey[];
      isNull?: PreviousStateIsNullEnumKey | PreviousStateIsNullEnumKey[];
      isNotNull?:
        | PreviousStateIsNotNullEnumKey
        | PreviousStateIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    nextState?: {
      eq?: NextStateEqEnumKey | NextStateEqEnumKey[];
      ne?: NextStateNeEnumKey | NextStateNeEnumKey[];
      in?: NextStateInEnumKey | NextStateInEnumKey[];
      nin?: NextStateNinEnumKey | NextStateNinEnumKey[];
      isNull?: NextStateIsNullEnumKey | NextStateIsNullEnumKey[];
      isNotNull?: NextStateIsNotNullEnumKey | NextStateIsNotNullEnumKey[];
    };
    /**
     * @type object | undefined
     */
    causeKind?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    causedByUserId?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    changedAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    createdAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type array | undefined
     */
    or?: FilterGroupObject[];
  };
  /**
   * @minLength 1
   * @type string | undefined
   */
  search?: string;
  /**
   * @type object | undefined
   */
  pagination?: Pagination;
  /**
   * @type string | undefined
   */
  sort?: string;
};

/**
 * @description Paginated list of state changes.
 */
export type GetProjectsIdStateChanges200 = ProjectStateChangeListResponse;

/**
 * @description Unauthorized.
 */
export type GetProjectsIdStateChanges401 = Problem;

/**
 * @description Project not found.
 */
export type GetProjectsIdStateChanges404 = Problem;

export type GetProjectsIdStateChangesQueryResponse =
  GetProjectsIdStateChanges200;

export type GetProjectsIdStateChangesQuery = {
  Response: GetProjectsIdStateChanges200;
  PathParams: GetProjectsIdStateChangesPathParams;
  QueryParams: GetProjectsIdStateChangesQueryParams;
  Errors: GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404;
};
