/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FilterGroupObject } from "./FilterGroupObject.ts";
import type { Pagination } from "./Pagination.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectBudgetItemListResponse } from "./ProjectBudgetItemListResponse.ts";

export type GetProjectsIdBudgetItemsPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type GetProjectsIdBudgetItemsQueryParams = {
  /**
   * @type object | undefined
   */
  filter?: {
    /**
     * @type object | undefined
     */
    id?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    concept?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    amountMinor?: {
      eq?: string | string[];
      ne?: string | string[];
      in?: string | string[];
      nin?: string | string[];
      ilike?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    createdAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type object | undefined
     */
    updatedAt?: {
      eq?: string | string[];
      ne?: string | string[];
      gt?: string | string[];
      gte?: string | string[];
      lt?: string | string[];
      lte?: string | string[];
      between?: string | string[];
      isNull?: string | string[];
      isNotNull?: string | string[];
    };
    /**
     * @type array | undefined
     */
    or?: FilterGroupObject[];
  };
  /**
   * @minLength 1
   * @type string | undefined
   */
  search?: string;
  /**
   * @type object | undefined
   */
  pagination?: Pagination;
  /**
   * @type string | undefined
   */
  sort?: string;
};

/**
 * @description Paginated list of budget items.
 */
export type GetProjectsIdBudgetItems200 = ProjectBudgetItemListResponse;

/**
 * @description Unauthorized.
 */
export type GetProjectsIdBudgetItems401 = Problem;

/**
 * @description Project not found.
 */
export type GetProjectsIdBudgetItems404 = Problem;

export type GetProjectsIdBudgetItemsQueryResponse = GetProjectsIdBudgetItems200;

export type GetProjectsIdBudgetItemsQuery = {
  Response: GetProjectsIdBudgetItems200;
  PathParams: GetProjectsIdBudgetItemsPathParams;
  QueryParams: GetProjectsIdBudgetItemsQueryParams;
  Errors: GetProjectsIdBudgetItems401 | GetProjectsIdBudgetItems404;
};
