/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectDocumentDownloadUrl } from "./ProjectDocumentDownloadUrl.ts";

export type GetProjectsIdDocumentsDocidDownloadUrlPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  docId: string;
};

/**
 * @description Presigned download URL.
 */
export type GetProjectsIdDocumentsDocidDownloadUrl200 =
  ProjectDocumentDownloadUrl;

/**
 * @description Unauthorized.
 */
export type GetProjectsIdDocumentsDocidDownloadUrl401 = Problem;

/**
 * @description Project or document not found.
 */
export type GetProjectsIdDocumentsDocidDownloadUrl404 = Problem;

export type GetProjectsIdDocumentsDocidDownloadUrlQueryResponse =
  GetProjectsIdDocumentsDocidDownloadUrl200;

export type GetProjectsIdDocumentsDocidDownloadUrlQuery = {
  Response: GetProjectsIdDocumentsDocidDownloadUrl200;
  PathParams: GetProjectsIdDocumentsDocidDownloadUrlPathParams;
  Errors:
    | GetProjectsIdDocumentsDocidDownloadUrl401
    | GetProjectsIdDocumentsDocidDownloadUrl404;
};
