/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type GetProjectsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Project found.
 */
export type GetProjectsId200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type GetProjectsId401 = Problem;

/**
 * @description Project not found.
 */
export type GetProjectsId404 = Problem;

export type GetProjectsIdQueryResponse = GetProjectsId200;

export type GetProjectsIdQuery = {
  Response: GetProjectsId200;
  PathParams: GetProjectsIdPathParams;
  Errors: GetProjectsId401 | GetProjectsId404;
};
