/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { UserListResponse } from "./UserListResponse.ts";

/**
 * @description Paginated list of users.
 */
export type GetUsers200 = UserListResponse;

/**
 * @description Unauthorized.
 */
export type GetUsers401 = Problem;

export type GetUsersQueryResponse = GetUsers200;

export type GetUsersQuery = {
  Response: GetUsers200;
  Errors: GetUsers401;
};
