/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ImportUploadResponse = {
  /**
   * @description UUID of the created import record
   * @type string, uuid
   */
  importId: string;
  /**
   * @description Import status after upload (awaiting_mapping)
   * @type string
   */
  status: string;
  /**
   * @description Column headers detected from the first row of the uploaded file
   * @type array
   */
  columnHeaders: string[];
};
