/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ImportSetMappingResponse = {
  /**
   * @description UUID of the import record
   * @type string, uuid
   */
  importId: string;
  /**
   * @description Import status after mapping (pending)
   * @type string
   */
  status: string;
};
