/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ImportListItem = {
  /**
   * @description Import UUID
   * @type string, uuid
   */
  id: string;
  /**
   * @description Import lifecycle status
   * @type string
   */
  status: string;
  /**
   * @description Current processing stage (null until processing begins)
   * @type string
   */
  stage: string | null;
  /**
   * @description Total data rows (null until counting pass completes)
   * @type integer
   */
  totalRows: number | null;
  /**
   * @description Rows committed so far
   * @type integer
   */
  processedRows: number;
  /**
   * @description Rows successfully inserted
   * @type integer
   */
  okCount: number;
  /**
   * @description Rows rejected due to validation errors
   * @type integer
   */
  failedCount: number;
  /**
   * @description Rows skipped as duplicates
   * @type integer
   */
  duplicatedCount: number;
  /**
   * @description Presigned URL for rejected.csv (null when no rejects)
   * @type string, uri
   */
  rejectedCsvUrl: string | null;
  /**
   * @description ISO 8601 creation timestamp
   * @type string
   */
  createdAt: string;
};
