/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const insightOutTriggerKindEnum = {
  post_import: "post_import",
  batch: "batch",
  individual: "individual",
  retry: "retry",
} as const;

export type InsightOutTriggerKindEnumKey =
  (typeof insightOutTriggerKindEnum)[keyof typeof insightOutTriggerKindEnum];

export const insightOutStatusEnum = {
  queued: "queued",
  processing: "processing",
  completed: "completed",
  failed: "failed",
} as const;

export type InsightOutStatusEnumKey =
  (typeof insightOutStatusEnum)[keyof typeof insightOutStatusEnum];

export type InsightOut = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  contactId: string;
  /**
   * @type string, uuid
   */
  templateId: string;
  /**
   * @type integer
   */
  templateVersion: number;
  /**
   * @type string
   */
  triggerKind: InsightOutTriggerKindEnumKey;
  /**
   * @type string
   */
  status: InsightOutStatusEnumKey;
  /**
   * @type integer
   */
  attempts: number;
  /**
   * @type object
   */
  result: {
    /**
     * @type string
     */
    resumen: string;
    /**
     * @type array
     */
    recomendaciones: string[];
    /**
     * @type string
     */
    observaciones: string;
  } | null;
  /**
   * @type string
   */
  modelUsed: string | null;
  /**
   * @type integer
   */
  promptTokens: number | null;
  /**
   * @type integer
   */
  completionTokens: number | null;
  /**
   * @type string
   */
  costUsd: string | null;
  /**
   * @type string
   */
  lastError: string | null;
  /**
   * @type string
   */
  completedAt: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
