/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Money = {
  /**
   * @description Amount in minor currency units
   * @type number
   */
  amountMinor: number;
  /**
   * @description ISO 4217 currency code
   * @type string
   */
  currency: string;
};
