/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Pagination = {
  /**
   * @minLength 1
   * @maxLength 100
   * @default 20
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @minLength 0
   * @default 0
   * @type integer
   */
  offset?: number | null;
};
