/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";
import type { UpdateProjectBody } from "./UpdateProjectBody.ts";

export type PatchProjectsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Project updated.
 */
export type PatchProjectsId200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PatchProjectsId401 = Problem;

/**
 * @description Project not found.
 */
export type PatchProjectsId404 = Problem;

export type PatchProjectsIdMutationRequest = UpdateProjectBody;

export type PatchProjectsIdMutationResponse = PatchProjectsId200;

export type PatchProjectsIdMutation = {
  Response: PatchProjectsId200;
  Request: PatchProjectsIdMutationRequest;
  PathParams: PatchProjectsIdPathParams;
  Errors: PatchProjectsId401 | PatchProjectsId404;
};
