/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { UpdateUserBody } from "./UpdateUserBody.ts";
import type { UserView } from "./UserView.ts";

export type PatchUsersIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description User updated.
 */
export type PatchUsersId200 = UserView;

/**
 * @description Unauthorized.
 */
export type PatchUsersId401 = Problem;

/**
 * @description User not found.
 */
export type PatchUsersId404 = Problem;

export type PatchUsersIdMutationRequest = UpdateUserBody;

export type PatchUsersIdMutationResponse = PatchUsersId200;

export type PatchUsersIdMutation = {
  Response: PatchUsersId200;
  Request: PatchUsersIdMutationRequest;
  PathParams: PatchUsersIdPathParams;
  Errors: PatchUsersId401 | PatchUsersId404;
};
