/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";
import type { UpdateResponsibleRoleBody } from "./UpdateResponsibleRoleBody.ts";

export type PatchProjectsIdResponsiblesUseridPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  userId: string;
};

/**
 * @description Role updated. Returns updated project.
 */
export type PatchProjectsIdResponsiblesUserid200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PatchProjectsIdResponsiblesUserid401 = Problem;

/**
 * @description Project or responsible not found.
 */
export type PatchProjectsIdResponsiblesUserid404 = Problem;

export type PatchProjectsIdResponsiblesUseridMutationRequest =
  UpdateResponsibleRoleBody;

export type PatchProjectsIdResponsiblesUseridMutationResponse =
  PatchProjectsIdResponsiblesUserid200;

export type PatchProjectsIdResponsiblesUseridMutation = {
  Response: PatchProjectsIdResponsiblesUserid200;
  Request: PatchProjectsIdResponsiblesUseridMutationRequest;
  PathParams: PatchProjectsIdResponsiblesUseridPathParams;
  Errors:
    | PatchProjectsIdResponsiblesUserid401
    | PatchProjectsIdResponsiblesUserid404;
};
