/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImportSetMappingResponse } from "./ImportSetMappingResponse.ts";
import type { Problem } from "./Problem.ts";
import type { SetMappingBody } from "./SetMappingBody.ts";

export type PatchImportsIdMappingPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Mapping saved. Import is now pending.
 */
export type PatchImportsIdMapping200 = ImportSetMappingResponse;

/**
 * @description Incomplete or invalid mapping.
 */
export type PatchImportsIdMapping400 = Problem;

/**
 * @description Unauthorized.
 */
export type PatchImportsIdMapping401 = Problem;

/**
 * @description Import not found.
 */
export type PatchImportsIdMapping404 = Problem;

export type PatchImportsIdMappingMutationRequest = SetMappingBody;

export type PatchImportsIdMappingMutationResponse = PatchImportsIdMapping200;

export type PatchImportsIdMappingMutation = {
  Response: PatchImportsIdMapping200;
  Request: PatchImportsIdMappingMutationRequest;
  PathParams: PatchImportsIdMappingPathParams;
  Errors:
    | PatchImportsIdMapping400
    | PatchImportsIdMapping401
    | PatchImportsIdMapping404;
};
