/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChangeStateBody } from "./ChangeStateBody.ts";
import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";

export type PatchContactsIdStatePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description State changed. Returns updated contact.
 */
export type PatchContactsIdState200 = ContactView;

/**
 * @description Unauthorized.
 */
export type PatchContactsIdState401 = Problem;

/**
 * @description Contact not found.
 */
export type PatchContactsIdState404 = Problem;

export type PatchContactsIdStateMutationRequest = ChangeStateBody;

export type PatchContactsIdStateMutationResponse = PatchContactsIdState200;

export type PatchContactsIdStateMutation = {
  Response: PatchContactsIdState200;
  Request: PatchContactsIdStateMutationRequest;
  PathParams: PatchContactsIdStatePathParams;
  Errors: PatchContactsIdState401 | PatchContactsIdState404;
};
