/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";
import type { UpdateBudgetItemBody } from "./UpdateBudgetItemBody.ts";

export type PatchProjectsIdBudgetItemsItemidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  itemId: string;
};

/**
 * @description Budget item updated. Returns updated project.
 */
export type PatchProjectsIdBudgetItemsItemid200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PatchProjectsIdBudgetItemsItemid401 = Problem;

/**
 * @description Project or budget item not found.
 */
export type PatchProjectsIdBudgetItemsItemid404 = Problem;

export type PatchProjectsIdBudgetItemsItemidMutationRequest =
  UpdateBudgetItemBody;

export type PatchProjectsIdBudgetItemsItemidMutationResponse =
  PatchProjectsIdBudgetItemsItemid200;

export type PatchProjectsIdBudgetItemsItemidMutation = {
  Response: PatchProjectsIdBudgetItemsItemid200;
  Request: PatchProjectsIdBudgetItemsItemidMutationRequest;
  PathParams: PatchProjectsIdBudgetItemsItemidPathParams;
  Errors:
    | PatchProjectsIdBudgetItemsItemid401
    | PatchProjectsIdBudgetItemsItemid404;
};
