/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";
import type { UpdateAssignmentRoleBody } from "./UpdateAssignmentRoleBody.ts";

export type PatchContactsIdAssignmentsUseridPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  userId: string;
};

/**
 * @description Assignment role updated. Returns updated contact.
 */
export type PatchContactsIdAssignmentsUserid200 = ContactView;

/**
 * @description Unauthorized.
 */
export type PatchContactsIdAssignmentsUserid401 = Problem;

/**
 * @description Contact or assignment not found.
 */
export type PatchContactsIdAssignmentsUserid404 = Problem;

export type PatchContactsIdAssignmentsUseridMutationRequest =
  UpdateAssignmentRoleBody;

export type PatchContactsIdAssignmentsUseridMutationResponse =
  PatchContactsIdAssignmentsUserid200;

export type PatchContactsIdAssignmentsUseridMutation = {
  Response: PatchContactsIdAssignmentsUserid200;
  Request: PatchContactsIdAssignmentsUseridMutationRequest;
  PathParams: PatchContactsIdAssignmentsUseridPathParams;
  Errors:
    | PatchContactsIdAssignmentsUserid401
    | PatchContactsIdAssignmentsUserid404;
};
