/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";
import type { UpdateChannelBody } from "./UpdateChannelBody.ts";

export type PatchContactsIdChannelsChannelidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  channelId: string;
};

/**
 * @description Channel updated. Returns updated contact.
 */
export type PatchContactsIdChannelsChannelid200 = ContactView;

/**
 * @description Unauthorized.
 */
export type PatchContactsIdChannelsChannelid401 = Problem;

/**
 * @description Contact not found.
 */
export type PatchContactsIdChannelsChannelid404 = Problem;

export type PatchContactsIdChannelsChannelidMutationRequest = UpdateChannelBody;

export type PatchContactsIdChannelsChannelidMutationResponse =
  PatchContactsIdChannelsChannelid200;

export type PatchContactsIdChannelsChannelidMutation = {
  Response: PatchContactsIdChannelsChannelid200;
  Request: PatchContactsIdChannelsChannelidMutationRequest;
  PathParams: PatchContactsIdChannelsChannelidPathParams;
  Errors:
    | PatchContactsIdChannelsChannelid401
    | PatchContactsIdChannelsChannelid404;
};
