/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type PatchAnalysisTemplatesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Template updated.
 */
export type PatchAnalysisTemplatesId200 = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  rubro: string;
  /**
   * @type string
   */
  prompt: string;
  /**
   * @type string
   */
  modelProvider: string;
  /**
   * @type integer
   */
  version: number;
  /**
   * @type boolean
   */
  isActive: boolean;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};

/**
 * @description Validation error.
 */
export type PatchAnalysisTemplatesId400 = Problem;

/**
 * @description Unauthorized.
 */
export type PatchAnalysisTemplatesId401 = Problem;

/**
 * @description Template not found.
 */
export type PatchAnalysisTemplatesId404 = Problem;

export type PatchAnalysisTemplatesIdMutationRequest = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  name?: string;
  /**
   * @minLength 1
   * @type string | undefined
   */
  rubro?: string;
  /**
   * @minLength 1
   * @type string | undefined
   */
  prompt?: string;
  /**
   * @minLength 1
   * @type string | undefined
   */
  modelProvider?: string;
};

export type PatchAnalysisTemplatesIdMutationResponse =
  PatchAnalysisTemplatesId200;

export type PatchAnalysisTemplatesIdMutation = {
  Response: PatchAnalysisTemplatesId200;
  Request: PatchAnalysisTemplatesIdMutationRequest;
  PathParams: PatchAnalysisTemplatesIdPathParams;
  Errors:
    | PatchAnalysisTemplatesId400
    | PatchAnalysisTemplatesId401
    | PatchAnalysisTemplatesId404;
};
