/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddChannelBody } from "./AddChannelBody.ts";
import type { ContactView } from "./ContactView.ts";
import type { Problem } from "./Problem.ts";

export type PostContactsIdChannelsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Channel added. Returns updated contact.
 */
export type PostContactsIdChannels200 = ContactView;

/**
 * @description Unauthorized.
 */
export type PostContactsIdChannels401 = Problem;

/**
 * @description Contact not found.
 */
export type PostContactsIdChannels404 = Problem;

export type PostContactsIdChannelsMutationRequest = AddChannelBody;

export type PostContactsIdChannelsMutationResponse = PostContactsIdChannels200;

export type PostContactsIdChannelsMutation = {
  Response: PostContactsIdChannels200;
  Request: PostContactsIdChannelsMutationRequest;
  PathParams: PostContactsIdChannelsPathParams;
  Errors: PostContactsIdChannels401 | PostContactsIdChannels404;
};
