/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";
import type { ProjectDocumentView } from "./ProjectDocumentView.ts";

export type PostProjectsIdDocumentsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Document uploaded.
 */
export type PostProjectsIdDocuments201 = ProjectDocumentView;

/**
 * @description Invalid file.
 */
export type PostProjectsIdDocuments400 = Problem;

/**
 * @description Unauthorized.
 */
export type PostProjectsIdDocuments401 = Problem;

/**
 * @description Project not found.
 */
export type PostProjectsIdDocuments404 = Problem;

export type PostProjectsIdDocumentsMutationResponse =
  PostProjectsIdDocuments201;

export type PostProjectsIdDocumentsMutation = {
  Response: PostProjectsIdDocuments201;
  PathParams: PostProjectsIdDocumentsPathParams;
  Errors:
    | PostProjectsIdDocuments400
    | PostProjectsIdDocuments401
    | PostProjectsIdDocuments404;
};
