/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

/**
 * @description Template created.
 */
export type PostAnalysisTemplates201 = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  rubro: string;
  /**
   * @type string
   */
  prompt: string;
  /**
   * @type string
   */
  modelProvider: string;
  /**
   * @type integer
   */
  version: number;
  /**
   * @type boolean
   */
  isActive: boolean;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};

/**
 * @description Validation error.
 */
export type PostAnalysisTemplates400 = Problem;

/**
 * @description Unauthorized.
 */
export type PostAnalysisTemplates401 = Problem;

export type PostAnalysisTemplatesMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string;
  /**
   * @minLength 1
   * @type string
   */
  rubro: string;
  /**
   * @minLength 1
   * @type string
   */
  prompt: string;
  /**
   * @minLength 1
   * @type string
   */
  modelProvider: string;
};

export type PostAnalysisTemplatesMutationResponse = PostAnalysisTemplates201;

export type PostAnalysisTemplatesMutation = {
  Response: PostAnalysisTemplates201;
  Request: PostAnalysisTemplatesMutationRequest;
  Errors: PostAnalysisTemplates400 | PostAnalysisTemplates401;
};
