/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Sesión cerrada. La cookie de sesión queda limpia.
 */
export type PostAuthLogout204 = any;

export type PostAuthLogoutMutationResponse = PostAuthLogout204;

export type PostAuthLogoutMutation = {
  Response: PostAuthLogout204;
  Errors: any;
};
