/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImportUploadResponse } from "./ImportUploadResponse.ts";
import type { Problem } from "./Problem.ts";

/**
 * @description Import created. Returns detected column headers for mapping.
 */
export type PostImports201 = ImportUploadResponse;

/**
 * @description Invalid file (wrong MIME, size exceeded, or missing file field).
 */
export type PostImports400 = Problem;

/**
 * @description Unauthorized.
 */
export type PostImports401 = Problem;

export type PostImportsMutationResponse = PostImports201;

export type PostImportsMutation = {
  Response: PostImports201;
  Errors: PostImports400 | PostImports401;
};
