/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChangeProjectStateBody } from "./ChangeProjectStateBody.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type PostProjectsIdStatePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description State changed. Returns updated project.
 */
export type PostProjectsIdState200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PostProjectsIdState401 = Problem;

/**
 * @description Project not found.
 */
export type PostProjectsIdState404 = Problem;

/**
 * @description Transition not allowed.
 */
export type PostProjectsIdState422 = Problem;

export type PostProjectsIdStateMutationRequest = ChangeProjectStateBody;

export type PostProjectsIdStateMutationResponse = PostProjectsIdState200;

export type PostProjectsIdStateMutation = {
  Response: PostProjectsIdState200;
  Request: PostProjectsIdStateMutationRequest;
  PathParams: PostProjectsIdStatePathParams;
  Errors:
    | PostProjectsIdState401
    | PostProjectsIdState404
    | PostProjectsIdState422;
};
