/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddExtensionBody } from "./AddExtensionBody.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type PostProjectsIdExtensionsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Extension added. Returns updated project.
 */
export type PostProjectsIdExtensions200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PostProjectsIdExtensions401 = Problem;

/**
 * @description Project not found.
 */
export type PostProjectsIdExtensions404 = Problem;

export type PostProjectsIdExtensionsMutationRequest = AddExtensionBody;

export type PostProjectsIdExtensionsMutationResponse =
  PostProjectsIdExtensions200;

export type PostProjectsIdExtensionsMutation = {
  Response: PostProjectsIdExtensions200;
  Request: PostProjectsIdExtensionsMutationRequest;
  PathParams: PostProjectsIdExtensionsPathParams;
  Errors: PostProjectsIdExtensions401 | PostProjectsIdExtensions404;
};
