/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

/**
 * @description Batch enrichment queued. Returns created insight IDs (duplicates skipped).
 */
export type PostEnrichmentsBatch201 = {
  /**
   * @type array
   */
  insightIds: string[];
  /**
   * @type integer
   */
  count: number;
};

/**
 * @description Validation error.
 */
export type PostEnrichmentsBatch400 = Problem;

/**
 * @description Unauthorized.
 */
export type PostEnrichmentsBatch401 = Problem;

/**
 * @description Template inactive.
 */
export type PostEnrichmentsBatch422 = Problem;

export type PostEnrichmentsBatchMutationRequest = {
  /**
   * @type array
   */
  contactIds: string[];
  /**
   * @type string, uuid
   */
  templateId: string;
};

export type PostEnrichmentsBatchMutationResponse = PostEnrichmentsBatch201;

export type PostEnrichmentsBatchMutation = {
  Response: PostEnrichmentsBatch201;
  Request: PostEnrichmentsBatchMutationRequest;
  Errors:
    | PostEnrichmentsBatch400
    | PostEnrichmentsBatch401
    | PostEnrichmentsBatch422;
};
