/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

export type PostEnrichmentsIdRetryPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Insight reset to queued and re-enqueued.
 */
export type PostEnrichmentsIdRetry200 = {
  /**
   * @type string, uuid
   */
  insightId: string;
};

/**
 * @description Unauthorized.
 */
export type PostEnrichmentsIdRetry401 = Problem;

/**
 * @description Insight not found.
 */
export type PostEnrichmentsIdRetry404 = Problem;

/**
 * @description Insight is not in failed status.
 */
export type PostEnrichmentsIdRetry422 = Problem;

export type PostEnrichmentsIdRetryMutationResponse = PostEnrichmentsIdRetry200;

export type PostEnrichmentsIdRetryMutation = {
  Response: PostEnrichmentsIdRetry200;
  PathParams: PostEnrichmentsIdRetryPathParams;
  Errors:
    | PostEnrichmentsIdRetry401
    | PostEnrichmentsIdRetry404
    | PostEnrichmentsIdRetry422;
};
