/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddBudgetItemBody } from "./AddBudgetItemBody.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type PostProjectsIdBudgetItemsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Budget item added. Returns updated project.
 */
export type PostProjectsIdBudgetItems200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PostProjectsIdBudgetItems401 = Problem;

/**
 * @description Project not found.
 */
export type PostProjectsIdBudgetItems404 = Problem;

export type PostProjectsIdBudgetItemsMutationRequest = AddBudgetItemBody;

export type PostProjectsIdBudgetItemsMutationResponse =
  PostProjectsIdBudgetItems200;

export type PostProjectsIdBudgetItemsMutation = {
  Response: PostProjectsIdBudgetItems200;
  Request: PostProjectsIdBudgetItemsMutationRequest;
  PathParams: PostProjectsIdBudgetItemsPathParams;
  Errors: PostProjectsIdBudgetItems401 | PostProjectsIdBudgetItems404;
};
