/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

/**
 * @description Sesión iniciada. La cookie de sesión queda seteada.
 */
export type PostAuthLogin200 = {
  /**
   * @type string
   */
  userId: string;
};

/**
 * @description Credenciales inválidas.
 */
export type PostAuthLogin401 = Problem;

export type PostAuthLoginMutationRequest = {
  /**
   * @type string, email
   */
  email: string;
  /**
   * @minLength 1
   * @type string
   */
  password: string;
};

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
  Response: PostAuthLogin200;
  Request: PostAuthLoginMutationRequest;
  Errors: PostAuthLogin401;
};
