/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Problem } from "./Problem.ts";

/**
 * @description Enrichment insight created and queued.
 */
export type PostEnrichments201 = {
  /**
   * @type array
   */
  insightIds: string[];
  /**
   * @type integer
   */
  count: number;
};

/**
 * @description Validation error.
 */
export type PostEnrichments400 = Problem;

/**
 * @description Unauthorized.
 */
export type PostEnrichments401 = Problem;

/**
 * @description Template not found.
 */
export type PostEnrichments404 = Problem;

/**
 * @description Template inactive.
 */
export type PostEnrichments422 = Problem;

export type PostEnrichmentsMutationRequest = {
  /**
   * @type string, uuid
   */
  contactId: string;
  /**
   * @type string, uuid
   */
  templateId: string;
};

export type PostEnrichmentsMutationResponse = PostEnrichments201;

export type PostEnrichmentsMutation = {
  Response: PostEnrichments201;
  Request: PostEnrichmentsMutationRequest;
  Errors:
    | PostEnrichments400
    | PostEnrichments401
    | PostEnrichments404
    | PostEnrichments422;
};
