/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddExpenseBody } from "./AddExpenseBody.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type PostProjectsIdExpensesPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Expense added. Returns updated project.
 */
export type PostProjectsIdExpenses200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PostProjectsIdExpenses401 = Problem;

/**
 * @description Project not found.
 */
export type PostProjectsIdExpenses404 = Problem;

export type PostProjectsIdExpensesMutationRequest = AddExpenseBody;

export type PostProjectsIdExpensesMutationResponse = PostProjectsIdExpenses200;

export type PostProjectsIdExpensesMutation = {
  Response: PostProjectsIdExpenses200;
  Request: PostProjectsIdExpensesMutationRequest;
  PathParams: PostProjectsIdExpensesPathParams;
  Errors: PostProjectsIdExpenses401 | PostProjectsIdExpenses404;
};
