/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateProjectBody } from "./CreateProjectBody.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

/**
 * @description Project created.
 */
export type PostProjects201 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PostProjects401 = Problem;

export type PostProjectsMutationRequest = CreateProjectBody;

export type PostProjectsMutationResponse = PostProjects201;

export type PostProjectsMutation = {
  Response: PostProjects201;
  Request: PostProjectsMutationRequest;
  Errors: PostProjects401;
};
