/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddResponsibleBody } from "./AddResponsibleBody.ts";
import type { Problem } from "./Problem.ts";
import type { ProjectView } from "./ProjectView.ts";

export type PostProjectsIdResponsiblesPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Responsible added. Returns updated project.
 */
export type PostProjectsIdResponsibles200 = ProjectView;

/**
 * @description Unauthorized.
 */
export type PostProjectsIdResponsibles401 = Problem;

/**
 * @description Project not found.
 */
export type PostProjectsIdResponsibles404 = Problem;

export type PostProjectsIdResponsiblesMutationRequest = AddResponsibleBody;

export type PostProjectsIdResponsiblesMutationResponse =
  PostProjectsIdResponsibles200;

export type PostProjectsIdResponsiblesMutation = {
  Response: PostProjectsIdResponsibles200;
  Request: PostProjectsIdResponsiblesMutationRequest;
  PathParams: PostProjectsIdResponsiblesPathParams;
  Errors: PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404;
};
