/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserBody } from "./CreateUserBody.ts";
import type { Problem } from "./Problem.ts";
import type { UserView } from "./UserView.ts";

/**
 * @description User created.
 */
export type PostUsers201 = UserView;

/**
 * @description Unauthorized.
 */
export type PostUsers401 = Problem;

/**
 * @description Email already registered.
 */
export type PostUsers409 = Problem;

export type PostUsersMutationRequest = CreateUserBody;

export type PostUsersMutationResponse = PostUsers201;

export type PostUsersMutation = {
  Response: PostUsers201;
  Request: PostUsersMutationRequest;
  Errors: PostUsers401 | PostUsers409;
};
