/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Problem = {
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type integer
   */
  status: number;
  /**
   * @type string
   */
  detail: string;
  /**
   * @type string
   */
  instance: string;
};
