/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjectExtensionView = {
  /**
   * @description Extension UUID
   * @type string
   */
  id: string;
  /**
   * @description Project UUID
   * @type string
   */
  projectId: string;
  /**
   * @description Number of additional days granted
   * @type number
   */
  additionalDays: number;
  /**
   * @description Computed end date after this extension (YYYY-MM-DD)
   * @type string
   */
  appliedEndDate: string;
  /**
   * @type string
   */
  reason: string;
  /**
   * @description Extension cost in minor currency units
   * @type number
   */
  cost: number | null;
  /**
   * @description Amount billed in minor currency units
   * @type number
   */
  billedAmount: number | null;
  /**
   * @description Date the extension was granted (YYYY-MM-DD)
   * @type string
   */
  grantedAt: string;
  /**
   * @description User UUID who granted the extension
   * @type string
   */
  grantedBy: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  updatedAt: string;
};
