/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjectDocumentDownloadUrl = {
  /**
   * @description Presigned download URL
   * @type string, uri
   */
  url: string;
  /**
   * @description ISO 8601 expiration timestamp
   * @type string, date-time
   */
  expiresAt: string;
};
