/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const projectStateChangeViewPreviousStateEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type ProjectStateChangeViewPreviousStateEnumKey =
  (typeof projectStateChangeViewPreviousStateEnum)[keyof typeof projectStateChangeViewPreviousStateEnum];

export const projectStateChangeViewNextStateEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type ProjectStateChangeViewNextStateEnumKey =
  (typeof projectStateChangeViewNextStateEnum)[keyof typeof projectStateChangeViewNextStateEnum];

export const projectStateChangeViewCauseKindEnum = {
  manual: "manual",
  system: "system",
} as const;

export type ProjectStateChangeViewCauseKindEnumKey =
  (typeof projectStateChangeViewCauseKindEnum)[keyof typeof projectStateChangeViewCauseKindEnum];

export type ProjectStateChangeView = {
  /**
   * @description State change UUID
   * @type string
   */
  id: string;
  /**
   * @description Project UUID
   * @type string
   */
  projectId: string;
  /**
   * @type string
   */
  previousState: ProjectStateChangeViewPreviousStateEnumKey;
  /**
   * @type string
   */
  nextState: ProjectStateChangeViewNextStateEnumKey;
  /**
   * @type string
   */
  causeKind: ProjectStateChangeViewCauseKindEnumKey;
  /**
   * @description User UUID (manual changes)
   * @type string
   */
  causedByUserId: string | null;
  /**
   * @description Optional note for manual changes
   * @type string
   */
  note: string | null;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  changedAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
};
