/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectBudgetItemView } from "./ProjectBudgetItemView.ts";

export type ProjectBudgetItemListResponse = {
  /**
   * @description List of items
   * @type array
   */
  items: ProjectBudgetItemView[];
  /**
   * @description Total number of items
   * @type integer
   */
  total: number;
  /**
   * @description Page size
   * @type integer
   */
  limit: number;
  /**
   * @description Page offset
   * @type integer
   */
  offset: number;
};
