/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const projectListItemStatusEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type ProjectListItemStatusEnumKey =
  (typeof projectListItemStatusEnum)[keyof typeof projectListItemStatusEnum];

export const leadsRoleEnum = {
  Lead: "Lead",
  Member: "Member",
} as const;

export type LeadsRoleEnumKey =
  (typeof leadsRoleEnum)[keyof typeof leadsRoleEnum];

export type ProjectListItem = {
  /**
   * @description Project UUID
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  description: string | null;
  /**
   * @description Associated contact UUID
   * @type string
   */
  contactId: string;
  /**
   * @description Associated contact name
   * @type string
   */
  contactName: string | null;
  /**
   * @description ISO 4217 currency code
   * @type string
   */
  currency: string;
  /**
   * @type string
   */
  status: ProjectListItemStatusEnumKey;
  /**
   * @description Start date (YYYY-MM-DD)
   * @type string
   */
  startDate: string;
  /**
   * @description Planned end date (YYYY-MM-DD)
   * @type string
   */
  plannedEndDate: string;
  /**
   * @description User UUID who created this project
   * @type string
   */
  createdBy: string;
  /**
   * @description Total number of responsibles
   * @type integer
   */
  responsiblesCount: number;
  /**
   * @description Lead responsibles
   * @type array
   */
  leads: {
    /**
     * @type string
     */
    userId: string;
    /**
     * @type string
     */
    userName: string;
    /**
     * @type string
     */
    role: LeadsRoleEnumKey;
  }[];
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  updatedAt: string;
};
