/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Money } from "./Money.ts";
import type { ProjectProfit } from "./ProjectProfit.ts";

export const projectViewStatusEnum = {
  Draft: "Draft",
  Active: "Active",
  Closed: "Closed",
  Cancelled: "Cancelled",
} as const;

export type ProjectViewStatusEnumKey =
  (typeof projectViewStatusEnum)[keyof typeof projectViewStatusEnum];

export const responsiblesRoleEnum = {
  Lead: "Lead",
  Member: "Member",
} as const;

export type ResponsiblesRoleEnumKey =
  (typeof responsiblesRoleEnum)[keyof typeof responsiblesRoleEnum];

export type ProjectView = {
  /**
   * @description Project UUID
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  description: string | null;
  /**
   * @description Associated contact UUID
   * @type string
   */
  contactId: string;
  /**
   * @description ISO 4217 currency code
   * @type string
   */
  currency: string;
  /**
   * @type string
   */
  status: ProjectViewStatusEnumKey;
  /**
   * @description Start date (YYYY-MM-DD)
   * @type string
   */
  startDate: string;
  /**
   * @description Original planned end date before any extensions (YYYY-MM-DD)
   * @type string
   */
  originalPlannedEndDate: string;
  /**
   * @description Derived planned end date including all extensions (YYYY-MM-DD)
   * @type string
   */
  plannedEndDate: string;
  /**
   * @description User UUID who created this project
   * @type string
   */
  createdBy: string;
  /**
   * @description Creator user data. Present on detail endpoint.
   * @type object | undefined
   */
  creator?: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    name: string;
  };
  /**
   * @description Project responsibles
   * @type array
   */
  responsibles: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    userId: string;
    /**
     * @type string
     */
    userName: string | null;
    /**
     * @type string
     */
    role: ResponsiblesRoleEnumKey;
    /**
     * @type string
     */
    assignedBy: string;
    /**
     * @type string
     */
    assignedAt: string;
  }[];
  /**
   * @description Derived financial totals
   * @type object
   */
  totals: {
    /**
     * @type object
     */
    budget: Money;
    /**
     * @type object
     */
    expenses: Money;
    /**
     * @type object
     */
    profit: ProjectProfit;
  };
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  createdAt: string;
  /**
   * @description ISO 8601 timestamp
   * @type string
   */
  updatedAt: string;
};
