/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SetMappingBody = {
  /**
   * @description Maps each Excel column header to a Contact field name.
   * @type object
   */
  mapping: {
    [key: string]: string;
  };
  /**
   * @description Optional template UUID to associate with this import (no FK in Fase 1).
   * @type string, uuid
   */
  templateId?: string | null;
};
