/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateChannelBodyChannelTypeEnum = {
  Phone: "Phone",
  Email: "Email",
  WhatsApp: "WhatsApp",
  Instagram: "Instagram",
  Website: "Website",
  Other: "Other",
} as const;

export type UpdateChannelBodyChannelTypeEnumKey =
  (typeof updateChannelBodyChannelTypeEnum)[keyof typeof updateChannelBodyChannelTypeEnum];

export type UpdateChannelBody = {
  /**
   * @description Communication channel type
   * @type string | undefined
   */
  channelType?: UpdateChannelBodyChannelTypeEnumKey;
  /**
   * @description Channel value (phone number, URL, handle)
   * @minLength 1
   * @type string | undefined
   */
  value?: string;
  /**
   * @description Whether this is the primary contact channel
   * @type boolean | undefined
   */
  isPrimary?: boolean;
};
