/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateExtensionBody = {
  /**
   * @description Number of additional days
   * @type integer | undefined
   */
  additionalDays?: number;
  /**
   * @description Reason for the extension
   * @minLength 1
   * @type string | undefined
   */
  reason?: string;
  /**
   * @description Extension cost in minor currency units
   * @minLength 0
   * @type integer
   */
  cost?: number | null;
  /**
   * @description Amount billed in minor currency units
   * @minLength 0
   * @type integer
   */
  billedAmount?: number | null;
  /**
   * @description Date the extension was granted (YYYY-MM-DD)
   * @type string | undefined, date
   */
  grantedAt?: string;
};
