/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateUserBody = {
  /**
   * @description New full name
   * @minLength 1
   * @type string | undefined
   */
  name?: string;
  /**
   * @description New password (>= 8 chars)
   * @minLength 8
   * @type string | undefined
   */
  password?: string;
};
