/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  DeleteProjectsIdResponsiblesUseridMutationResponse,
  DeleteProjectsIdResponsiblesUseridPathParams,
  DeleteProjectsIdResponsiblesUserid401,
  DeleteProjectsIdResponsiblesUserid404,
  DeleteProjectsIdResponsiblesUserid422,
} from "../types/DeleteProjectsIdResponsiblesUserid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getDeleteProjectsIdResponsiblesUseridUrl(
  id: DeleteProjectsIdResponsiblesUseridPathParams["id"],
  userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"],
) {
  const res = {
    method: "DELETE",
    url: `/projects/${id}/responsibles/${userId}` as const,
  };
  return res;
}

/**
 * @summary Remove a responsible from a project
 * {@link /projects/:id/responsibles/:userId}
 */
export async function deleteProjectsIdResponsiblesUserid(
  id: DeleteProjectsIdResponsiblesUseridPathParams["id"],
  userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdResponsiblesUserid401
      | DeleteProjectsIdResponsiblesUserid404
      | DeleteProjectsIdResponsiblesUserid422
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteProjectsIdResponsiblesUseridUrl(id, userId).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
