/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  DeleteContactsIdChannelsChannelidMutationResponse,
  DeleteContactsIdChannelsChannelidPathParams,
  DeleteContactsIdChannelsChannelid401,
  DeleteContactsIdChannelsChannelid404,
} from "../types/DeleteContactsIdChannelsChannelid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getDeleteContactsIdChannelsChannelidUrl(
  id: DeleteContactsIdChannelsChannelidPathParams["id"],
  channelId: DeleteContactsIdChannelsChannelidPathParams["channelId"],
) {
  const res = {
    method: "DELETE",
    url: `/contacts/${id}/channels/${channelId}` as const,
  };
  return res;
}

/**
 * @summary Remove a communication channel from a contact
 * {@link /contacts/:id/channels/:channelId}
 */
export async function deleteContactsIdChannelsChannelid(
  id: DeleteContactsIdChannelsChannelidPathParams["id"],
  channelId: DeleteContactsIdChannelsChannelidPathParams["channelId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteContactsIdChannelsChannelidMutationResponse,
    ResponseErrorConfig<
      | DeleteContactsIdChannelsChannelid401
      | DeleteContactsIdChannelsChannelid404
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteContactsIdChannelsChannelidUrl(id, channelId).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
