/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  DeleteProjectsIdExtensionsExtidMutationResponse,
  DeleteProjectsIdExtensionsExtidPathParams,
  DeleteProjectsIdExtensionsExtid401,
  DeleteProjectsIdExtensionsExtid404,
} from "../types/DeleteProjectsIdExtensionsExtid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getDeleteProjectsIdExtensionsExtidUrl(
  id: DeleteProjectsIdExtensionsExtidPathParams["id"],
  extId: DeleteProjectsIdExtensionsExtidPathParams["extId"],
) {
  const res = {
    method: "DELETE",
    url: `/projects/${id}/extensions/${extId}` as const,
  };
  return res;
}

/**
 * @summary Remove an extension from a project
 * {@link /projects/:id/extensions/:extId}
 */
export async function deleteProjectsIdExtensionsExtid(
  id: DeleteProjectsIdExtensionsExtidPathParams["id"],
  extId: DeleteProjectsIdExtensionsExtidPathParams["extId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdExtensionsExtid401 | DeleteProjectsIdExtensionsExtid404
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteProjectsIdExtensionsExtidUrl(id, extId).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
