/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  DeleteContactsIdMutationResponse,
  DeleteContactsIdPathParams,
  DeleteContactsId401,
  DeleteContactsId404,
} from "../types/DeleteContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getDeleteContactsIdUrl(id: DeleteContactsIdPathParams["id"]) {
  const res = { method: "DELETE", url: `/contacts/${id}` as const };
  return res;
}

/**
 * @summary Soft-delete a contact
 * {@link /contacts/:id}
 */
export async function deleteContactsId(
  id: DeleteContactsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteContactsIdMutationResponse,
    ResponseErrorConfig<DeleteContactsId401 | DeleteContactsId404>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteContactsIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
