/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetAuthMeQueryResponse,
  GetAuthMe401,
} from "../types/GetAuthMe.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetAuthMeUrl() {
  const res = { method: "GET", url: `/auth/me` as const };
  return res;
}

/**
 * @summary Obtener usuario autenticado
 * {@link /auth/me}
 */
export async function getAuthMe(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAuthMeQueryResponse,
    ResponseErrorConfig<GetAuthMe401>,
    unknown
  >({ method: "GET", url: getGetAuthMeUrl().url.toString(), ...requestConfig });
  return res.data;
}
