/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetAnalysisTemplatesQueryResponse,
  GetAnalysisTemplates401,
} from "../types/GetAnalysisTemplates.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetAnalysisTemplatesUrl() {
  const res = { method: "GET", url: `/analysis-templates` as const };
  return res;
}

/**
 * @summary List all analysis templates
 * {@link /analysis-templates}
 */
export async function getAnalysisTemplates(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAnalysisTemplatesQueryResponse,
    ResponseErrorConfig<GetAnalysisTemplates401>,
    unknown
  >({
    method: "GET",
    url: getGetAnalysisTemplatesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
