/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetContactsKpisQueryResponse,
  GetContactsKpis401,
} from "../types/GetContactsKpis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetContactsKpisUrl() {
  const res = { method: "GET", url: `/contacts/kpis` as const };
  return res;
}

/**
 * @summary Get pipeline-flow KPIs for contacts
 * {@link /contacts/kpis}
 */
export async function getContactsKpis(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetContactsKpisQueryResponse,
    ResponseErrorConfig<GetContactsKpis401>,
    unknown
  >({
    method: "GET",
    url: getGetContactsKpisUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
