/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/http-client";
import type {
  GetContactsIdEventsQueryResponse,
  GetContactsIdEventsPathParams,
  GetContactsIdEvents401,
  GetContactsIdEvents404,
} from "../types/GetContactsIdEvents.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";

function getGetContactsIdEventsUrl(id: GetContactsIdEventsPathParams["id"]) {
  const res = { method: "GET", url: `/contacts/:id/events` as const };
  return res;
}

/**
 * @summary List events for a contact
 * {@link /contacts/:id/events}
 */
export async function getContactsIdEvents(
  id: GetContactsIdEventsPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetContactsIdEventsQueryResponse,
    ResponseErrorConfig<GetContactsIdEvents401 | GetContactsIdEvents404>,
    unknown
  >({
    method: "GET",
    url: getGetContactsIdEventsUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
