/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/http-client";
import type {
  GetContactsIdQueryResponse,
  GetContactsIdPathParams,
  GetContactsId401,
  GetContactsId404,
} from "../types/GetContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";

function getGetContactsIdUrl(id: GetContactsIdPathParams["id"]) {
  const res = { method: "GET", url: `/contacts/:id` as const };
  return res;
}

/**
 * @summary Get a contact by id
 * {@link /contacts/:id}
 */
export async function getContactsId(
  id: GetContactsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetContactsIdQueryResponse,
    ResponseErrorConfig<GetContactsId401 | GetContactsId404>,
    unknown
  >({
    method: "GET",
    url: getGetContactsIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
