/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetContactsIdAssignmentsQueryResponse,
  GetContactsIdAssignmentsPathParams,
  GetContactsIdAssignments401,
  GetContactsIdAssignments404,
} from "../types/GetContactsIdAssignments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetContactsIdAssignmentsUrl(
  id: GetContactsIdAssignmentsPathParams["id"],
) {
  const res = { method: "GET", url: `/contacts/${id}/assignments` as const };
  return res;
}

/**
 * @summary List assignments (assignees) of a contact
 * {@link /contacts/:id/assignments}
 */
export async function getContactsIdAssignments(
  id: GetContactsIdAssignmentsPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetContactsIdAssignmentsQueryResponse,
    ResponseErrorConfig<
      GetContactsIdAssignments401 | GetContactsIdAssignments404
    >,
    unknown
  >({
    method: "GET",
    url: getGetContactsIdAssignmentsUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
