/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetEnrichmentsQueryResponse,
  GetEnrichmentsQueryParams,
  GetEnrichments400,
  GetEnrichments401,
} from "../types/GetEnrichments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetEnrichmentsUrl() {
  const res = { method: "GET", url: `/enrichments` as const };
  return res;
}

/**
 * @summary List enrichment insights for a contact
 * {@link /enrichments}
 */
export async function getEnrichments(
  params: GetEnrichmentsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetEnrichmentsQueryResponse,
    ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>,
    unknown
  >({
    method: "GET",
    url: getGetEnrichmentsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
