/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetEnrichmentsIdQueryResponse,
  GetEnrichmentsIdPathParams,
  GetEnrichmentsId401,
  GetEnrichmentsId404,
} from "../types/GetEnrichmentsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetEnrichmentsIdUrl(id: GetEnrichmentsIdPathParams["id"]) {
  const res = { method: "GET", url: `/enrichments/${id}` as const };
  return res;
}

/**
 * @summary Get enrichment insight status and result
 * {@link /enrichments/:id}
 */
export async function getEnrichmentsId(
  id: GetEnrichmentsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetEnrichmentsIdQueryResponse,
    ResponseErrorConfig<GetEnrichmentsId401 | GetEnrichmentsId404>,
    unknown
  >({
    method: "GET",
    url: getGetEnrichmentsIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
