/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetImportsQueryResponse,
  GetImportsQueryParams,
  GetImports401,
} from "../types/GetImports.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetImportsUrl() {
  const res = { method: "GET", url: `/imports` as const };
  return res;
}

/**
 * @summary List imports (paginated)
 * {@link /imports}
 */
export async function getImports(
  params?: GetImportsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetImportsQueryResponse,
    ResponseErrorConfig<GetImports401>,
    unknown
  >({
    method: "GET",
    url: getGetImportsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
