/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetImportsIdQueryResponse,
  GetImportsIdPathParams,
  GetImportsId401,
  GetImportsId404,
} from "../types/GetImportsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetImportsIdUrl(id: GetImportsIdPathParams["id"]) {
  const res = { method: "GET", url: `/imports/${id}` as const };
  return res;
}

/**
 * @summary Get the current status and progress of an import
 * {@link /imports/:id}
 */
export async function getImportsId(
  id: GetImportsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetImportsIdQueryResponse,
    ResponseErrorConfig<GetImportsId401 | GetImportsId404>,
    unknown
  >({
    method: "GET",
    url: getGetImportsIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
