/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetProjectsIdExpensesQueryResponse,
  GetProjectsIdExpensesPathParams,
  GetProjectsIdExpensesQueryParams,
  GetProjectsIdExpenses401,
  GetProjectsIdExpenses404,
} from "../types/GetProjectsIdExpenses.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetProjectsIdExpensesUrl(
  id: GetProjectsIdExpensesPathParams["id"],
) {
  const res = { method: "GET", url: `/projects/${id}/expenses` as const };
  return res;
}

/**
 * @summary List expenses for a project
 * {@link /projects/:id/expenses}
 */
export async function getProjectsIdExpenses(
  id: GetProjectsIdExpensesPathParams["id"],
  params?: GetProjectsIdExpensesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProjectsIdExpensesQueryResponse,
    ResponseErrorConfig<GetProjectsIdExpenses401 | GetProjectsIdExpenses404>,
    unknown
  >({
    method: "GET",
    url: getGetProjectsIdExpensesUrl(id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
