/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetProjectsIdStateChangesQueryResponse,
  GetProjectsIdStateChangesPathParams,
  GetProjectsIdStateChangesQueryParams,
  GetProjectsIdStateChanges401,
  GetProjectsIdStateChanges404,
} from "../types/GetProjectsIdStateChanges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetProjectsIdStateChangesUrl(
  id: GetProjectsIdStateChangesPathParams["id"],
) {
  const res = { method: "GET", url: `/projects/${id}/state-changes` as const };
  return res;
}

/**
 * @summary List state changes for a project
 * {@link /projects/:id/state-changes}
 */
export async function getProjectsIdStateChanges(
  id: GetProjectsIdStateChangesPathParams["id"],
  params?: GetProjectsIdStateChangesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProjectsIdStateChangesQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
    >,
    unknown
  >({
    method: "GET",
    url: getGetProjectsIdStateChangesUrl(id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
