/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetProjectsIdExtensionsQueryResponse,
  GetProjectsIdExtensionsPathParams,
  GetProjectsIdExtensionsQueryParams,
  GetProjectsIdExtensions401,
  GetProjectsIdExtensions404,
} from "../types/GetProjectsIdExtensions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetProjectsIdExtensionsUrl(
  id: GetProjectsIdExtensionsPathParams["id"],
) {
  const res = { method: "GET", url: `/projects/${id}/extensions` as const };
  return res;
}

/**
 * @summary List extensions for a project
 * {@link /projects/:id/extensions}
 */
export async function getProjectsIdExtensions(
  id: GetProjectsIdExtensionsPathParams["id"],
  params?: GetProjectsIdExtensionsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProjectsIdExtensionsQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdExtensions401 | GetProjectsIdExtensions404
    >,
    unknown
  >({
    method: "GET",
    url: getGetProjectsIdExtensionsUrl(id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
