/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
  GetProjectsIdDocumentsDocidDownloadUrlPathParams,
  GetProjectsIdDocumentsDocidDownloadUrl401,
  GetProjectsIdDocumentsDocidDownloadUrl404,
} from "../types/GetProjectsIdDocumentsDocidDownloadUrl.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetProjectsIdDocumentsDocidDownloadUrlUrl(
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"],
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"],
) {
  const res = {
    method: "GET",
    url: `/projects/${id}/documents/${docId}/download-url` as const,
  };
  return res;
}

/**
 * @summary Get a presigned download URL for a document
 * {@link /projects/:id/documents/:docId/download-url}
 */
export async function getProjectsIdDocumentsDocidDownloadUrl(
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"],
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
    ResponseErrorConfig<
      | GetProjectsIdDocumentsDocidDownloadUrl401
      | GetProjectsIdDocumentsDocidDownloadUrl404
    >,
    unknown
  >({
    method: "GET",
    url: getGetProjectsIdDocumentsDocidDownloadUrlUrl(id, docId).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
