/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetProjectsIdBudgetItemsQueryResponse,
  GetProjectsIdBudgetItemsPathParams,
  GetProjectsIdBudgetItemsQueryParams,
  GetProjectsIdBudgetItems401,
  GetProjectsIdBudgetItems404,
} from "../types/GetProjectsIdBudgetItems.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetProjectsIdBudgetItemsUrl(
  id: GetProjectsIdBudgetItemsPathParams["id"],
) {
  const res = { method: "GET", url: `/projects/${id}/budget-items` as const };
  return res;
}

/**
 * @summary List budget items for a project
 * {@link /projects/:id/budget-items}
 */
export async function getProjectsIdBudgetItems(
  id: GetProjectsIdBudgetItemsPathParams["id"],
  params?: GetProjectsIdBudgetItemsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProjectsIdBudgetItemsQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdBudgetItems401 | GetProjectsIdBudgetItems404
    >,
    unknown
  >({
    method: "GET",
    url: getGetProjectsIdBudgetItemsUrl(id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
