/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  GetProjectsKpisQueryResponse,
  GetProjectsKpis401,
} from "../types/GetProjectsKpis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getGetProjectsKpisUrl() {
  const res = { method: "GET", url: `/projects/kpis` as const };
  return res;
}

/**
 * @summary Get status KPIs for projects
 * {@link /projects/kpis}
 */
export async function getProjectsKpis(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProjectsKpisQueryResponse,
    ResponseErrorConfig<GetProjectsKpis401>,
    unknown
  >({
    method: "GET",
    url: getGetProjectsKpisUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
