/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/http-client";
import type { GetUsersQueryResponse, GetUsers401 } from "../types/GetUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";

function getGetUsersUrl() {
  const res = { method: "GET", url: `/users` as const };
  return res;
}

/**
 * @summary List users
 * {@link /users}
 */
export async function getUsers(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUsersQueryResponse,
    ResponseErrorConfig<GetUsers401>,
    unknown
  >({ method: "GET", url: getGetUsersUrl().url.toString(), ...requestConfig });
  return res.data;
}
