/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchProjectsIdExpensesExpenseidMutationRequest,
  PatchProjectsIdExpensesExpenseidMutationResponse,
  PatchProjectsIdExpensesExpenseidPathParams,
  PatchProjectsIdExpensesExpenseid401,
  PatchProjectsIdExpensesExpenseid404,
} from "../types/PatchProjectsIdExpensesExpenseid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchProjectsIdExpensesExpenseidUrl(
  id: PatchProjectsIdExpensesExpenseidPathParams["id"],
  expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"],
) {
  const res = {
    method: "PATCH",
    url: `/projects/${id}/expenses/${expenseId}` as const,
  };
  return res;
}

/**
 * @summary Update an expense
 * {@link /projects/:id/expenses/:expenseId}
 */
export async function patchProjectsIdExpensesExpenseid(
  id: PatchProjectsIdExpensesExpenseidPathParams["id"],
  expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"],
  data: PatchProjectsIdExpensesExpenseidMutationRequest,
  config: Partial<
    RequestConfig<PatchProjectsIdExpensesExpenseidMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExpensesExpenseid401 | PatchProjectsIdExpensesExpenseid404
    >,
    PatchProjectsIdExpensesExpenseidMutationRequest
  >({
    method: "PATCH",
    url: getPatchProjectsIdExpensesExpenseidUrl(id, expenseId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
