/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchProjectsIdMutationRequest,
  PatchProjectsIdMutationResponse,
  PatchProjectsIdPathParams,
  PatchProjectsId401,
  PatchProjectsId404,
} from "../types/PatchProjectsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchProjectsIdUrl(id: PatchProjectsIdPathParams["id"]) {
  const res = { method: "PATCH", url: `/projects/${id}` as const };
  return res;
}

/**
 * @summary Update a project
 * {@link /projects/:id}
 */
export async function patchProjectsId(
  id: PatchProjectsIdPathParams["id"],
  data: PatchProjectsIdMutationRequest,
  config: Partial<RequestConfig<PatchProjectsIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchProjectsIdMutationResponse,
    ResponseErrorConfig<PatchProjectsId401 | PatchProjectsId404>,
    PatchProjectsIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchProjectsIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
