/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchProjectsIdResponsiblesUseridMutationRequest,
  PatchProjectsIdResponsiblesUseridMutationResponse,
  PatchProjectsIdResponsiblesUseridPathParams,
  PatchProjectsIdResponsiblesUserid401,
  PatchProjectsIdResponsiblesUserid404,
} from "../types/PatchProjectsIdResponsiblesUserid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchProjectsIdResponsiblesUseridUrl(
  id: PatchProjectsIdResponsiblesUseridPathParams["id"],
  userId: PatchProjectsIdResponsiblesUseridPathParams["userId"],
) {
  const res = {
    method: "PATCH",
    url: `/projects/${id}/responsibles/${userId}` as const,
  };
  return res;
}

/**
 * @summary Update the role of a responsible
 * {@link /projects/:id/responsibles/:userId}
 */
export async function patchProjectsIdResponsiblesUserid(
  id: PatchProjectsIdResponsiblesUseridPathParams["id"],
  userId: PatchProjectsIdResponsiblesUseridPathParams["userId"],
  data: PatchProjectsIdResponsiblesUseridMutationRequest,
  config: Partial<
    RequestConfig<PatchProjectsIdResponsiblesUseridMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | PatchProjectsIdResponsiblesUserid401
      | PatchProjectsIdResponsiblesUserid404
    >,
    PatchProjectsIdResponsiblesUseridMutationRequest
  >({
    method: "PATCH",
    url: getPatchProjectsIdResponsiblesUseridUrl(id, userId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
