/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/http-client";
import type {
  PatchContactsIdStateMutationRequest,
  PatchContactsIdStateMutationResponse,
  PatchContactsIdStatePathParams,
  PatchContactsIdState401,
  PatchContactsIdState404,
} from "../types/PatchContactsIdState.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";

function getPatchContactsIdStateUrl(id: PatchContactsIdStatePathParams["id"]) {
  const res = { method: "PATCH", url: `/contacts/:id/state` as const };
  return res;
}

/**
 * @summary Manually change contact pipeline state
 * {@link /contacts/:id/state}
 */
export async function patchContactsIdState(
  id: PatchContactsIdStatePathParams["id"],
  data: PatchContactsIdStateMutationRequest,
  config: Partial<RequestConfig<PatchContactsIdStateMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchContactsIdStateMutationResponse,
    ResponseErrorConfig<PatchContactsIdState401 | PatchContactsIdState404>,
    PatchContactsIdStateMutationRequest
  >({
    method: "PATCH",
    url: getPatchContactsIdStateUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
