/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchContactsIdAssignmentsUseridMutationRequest,
  PatchContactsIdAssignmentsUseridMutationResponse,
  PatchContactsIdAssignmentsUseridPathParams,
  PatchContactsIdAssignmentsUserid401,
  PatchContactsIdAssignmentsUserid404,
} from "../types/PatchContactsIdAssignmentsUserid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchContactsIdAssignmentsUseridUrl(
  id: PatchContactsIdAssignmentsUseridPathParams["id"],
  userId: PatchContactsIdAssignmentsUseridPathParams["userId"],
) {
  const res = {
    method: "PATCH",
    url: `/contacts/${id}/assignments/${userId}` as const,
  };
  return res;
}

/**
 * @summary Update the role of an assignment
 * {@link /contacts/:id/assignments/:userId}
 */
export async function patchContactsIdAssignmentsUserid(
  id: PatchContactsIdAssignmentsUseridPathParams["id"],
  userId: PatchContactsIdAssignmentsUseridPathParams["userId"],
  data: PatchContactsIdAssignmentsUseridMutationRequest,
  config: Partial<
    RequestConfig<PatchContactsIdAssignmentsUseridMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchContactsIdAssignmentsUseridMutationResponse,
    ResponseErrorConfig<
      PatchContactsIdAssignmentsUserid401 | PatchContactsIdAssignmentsUserid404
    >,
    PatchContactsIdAssignmentsUseridMutationRequest
  >({
    method: "PATCH",
    url: getPatchContactsIdAssignmentsUseridUrl(id, userId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
