/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchContactsIdChannelsChannelidMutationRequest,
  PatchContactsIdChannelsChannelidMutationResponse,
  PatchContactsIdChannelsChannelidPathParams,
  PatchContactsIdChannelsChannelid401,
  PatchContactsIdChannelsChannelid404,
} from "../types/PatchContactsIdChannelsChannelid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchContactsIdChannelsChannelidUrl(
  id: PatchContactsIdChannelsChannelidPathParams["id"],
  channelId: PatchContactsIdChannelsChannelidPathParams["channelId"],
) {
  const res = {
    method: "PATCH",
    url: `/contacts/${id}/channels/${channelId}` as const,
  };
  return res;
}

/**
 * @summary Update a communication channel on a contact
 * {@link /contacts/:id/channels/:channelId}
 */
export async function patchContactsIdChannelsChannelid(
  id: PatchContactsIdChannelsChannelidPathParams["id"],
  channelId: PatchContactsIdChannelsChannelidPathParams["channelId"],
  data: PatchContactsIdChannelsChannelidMutationRequest,
  config: Partial<
    RequestConfig<PatchContactsIdChannelsChannelidMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchContactsIdChannelsChannelidMutationResponse,
    ResponseErrorConfig<
      PatchContactsIdChannelsChannelid401 | PatchContactsIdChannelsChannelid404
    >,
    PatchContactsIdChannelsChannelidMutationRequest
  >({
    method: "PATCH",
    url: getPatchContactsIdChannelsChannelidUrl(id, channelId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
