/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchImportsIdMappingMutationRequest,
  PatchImportsIdMappingMutationResponse,
  PatchImportsIdMappingPathParams,
  PatchImportsIdMapping400,
  PatchImportsIdMapping401,
  PatchImportsIdMapping404,
} from "../types/PatchImportsIdMapping.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchImportsIdMappingUrl(
  id: PatchImportsIdMappingPathParams["id"],
) {
  const res = { method: "PATCH", url: `/imports/${id}/mapping` as const };
  return res;
}

/**
 * @summary Define the column-to-field mapping for an import
 * {@link /imports/:id/mapping}
 */
export async function patchImportsIdMapping(
  id: PatchImportsIdMappingPathParams["id"],
  data: PatchImportsIdMappingMutationRequest,
  config: Partial<RequestConfig<PatchImportsIdMappingMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchImportsIdMappingMutationResponse,
    ResponseErrorConfig<
      | PatchImportsIdMapping400
      | PatchImportsIdMapping401
      | PatchImportsIdMapping404
    >,
    PatchImportsIdMappingMutationRequest
  >({
    method: "PATCH",
    url: getPatchImportsIdMappingUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
