/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchContactsIdMutationRequest,
  PatchContactsIdMutationResponse,
  PatchContactsIdPathParams,
  PatchContactsId401,
  PatchContactsId404,
} from "../types/PatchContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchContactsIdUrl(id: PatchContactsIdPathParams["id"]) {
  const res = { method: "PATCH", url: `/contacts/${id}` as const };
  return res;
}

/**
 * @summary Update scalar and address fields of a contact
 * {@link /contacts/:id}
 */
export async function patchContactsId(
  id: PatchContactsIdPathParams["id"],
  data: PatchContactsIdMutationRequest,
  config: Partial<RequestConfig<PatchContactsIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchContactsIdMutationResponse,
    ResponseErrorConfig<PatchContactsId401 | PatchContactsId404>,
    PatchContactsIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchContactsIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
