/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/http-client";
import type {
  PatchUsersIdMutationRequest,
  PatchUsersIdMutationResponse,
  PatchUsersIdPathParams,
  PatchUsersId401,
  PatchUsersId404,
} from "../types/PatchUsersId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";

function getPatchUsersIdUrl(id: PatchUsersIdPathParams["id"]) {
  const res = { method: "PATCH", url: `/users/${id}` as const };
  return res;
}

/**
 * @summary Update a user (name and/or password)
 * {@link /users/:id}
 */
export async function patchUsersId(
  id: PatchUsersIdPathParams["id"],
  data: PatchUsersIdMutationRequest,
  config: Partial<RequestConfig<PatchUsersIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchUsersIdMutationResponse,
    ResponseErrorConfig<PatchUsersId401 | PatchUsersId404>,
    PatchUsersIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchUsersIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
