/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PatchAnalysisTemplatesIdMutationRequest,
  PatchAnalysisTemplatesIdMutationResponse,
  PatchAnalysisTemplatesIdPathParams,
  PatchAnalysisTemplatesId400,
  PatchAnalysisTemplatesId401,
  PatchAnalysisTemplatesId404,
} from "../types/PatchAnalysisTemplatesId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPatchAnalysisTemplatesIdUrl(
  id: PatchAnalysisTemplatesIdPathParams["id"],
) {
  const res = { method: "PATCH", url: `/analysis-templates/${id}` as const };
  return res;
}

/**
 * @summary Update an analysis template
 * {@link /analysis-templates/:id}
 */
export async function patchAnalysisTemplatesId(
  id: PatchAnalysisTemplatesIdPathParams["id"],
  data: PatchAnalysisTemplatesIdMutationRequest,
  config: Partial<RequestConfig<PatchAnalysisTemplatesIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchAnalysisTemplatesIdMutationResponse,
    ResponseErrorConfig<
      | PatchAnalysisTemplatesId400
      | PatchAnalysisTemplatesId401
      | PatchAnalysisTemplatesId404
    >,
    PatchAnalysisTemplatesIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchAnalysisTemplatesIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
