/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostAuthLoginMutationRequest,
  PostAuthLoginMutationResponse,
  PostAuthLogin401,
} from "../types/PostAuthLogin.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostAuthLoginUrl() {
  const res = { method: "POST", url: `/auth/login` as const };
  return res;
}

/**
 * @summary Iniciar sesión
 * {@link /auth/login}
 */
export async function postAuthLogin(
  data: PostAuthLoginMutationRequest,
  config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<PostAuthLogin401>,
    PostAuthLoginMutationRequest
  >({
    method: "POST",
    url: getPostAuthLoginUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
