/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostProjectsIdResponsiblesMutationRequest,
  PostProjectsIdResponsiblesMutationResponse,
  PostProjectsIdResponsiblesPathParams,
  PostProjectsIdResponsibles401,
  PostProjectsIdResponsibles404,
} from "../types/PostProjectsIdResponsibles.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostProjectsIdResponsiblesUrl(
  id: PostProjectsIdResponsiblesPathParams["id"],
) {
  const res = { method: "POST", url: `/projects/${id}/responsibles` as const };
  return res;
}

/**
 * @summary Add a responsible to a project
 * {@link /projects/:id/responsibles}
 */
export async function postProjectsIdResponsibles(
  id: PostProjectsIdResponsiblesPathParams["id"],
  data: PostProjectsIdResponsiblesMutationRequest,
  config: Partial<RequestConfig<PostProjectsIdResponsiblesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProjectsIdResponsiblesMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404
    >,
    PostProjectsIdResponsiblesMutationRequest
  >({
    method: "POST",
    url: getPostProjectsIdResponsiblesUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
