/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostContactsBulkDeleteMutationRequest,
  PostContactsBulkDeleteMutationResponse,
  PostContactsBulkDelete401,
} from "../types/PostContactsBulkDelete.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostContactsBulkDeleteUrl() {
  const res = { method: "POST", url: `/contacts/bulk-delete` as const };
  return res;
}

/**
 * @summary Soft-delete multiple contacts
 * {@link /contacts/bulk-delete}
 */
export async function postContactsBulkDelete(
  data: PostContactsBulkDeleteMutationRequest,
  config: Partial<RequestConfig<PostContactsBulkDeleteMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostContactsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostContactsBulkDelete401>,
    PostContactsBulkDeleteMutationRequest
  >({
    method: "POST",
    url: getPostContactsBulkDeleteUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
