/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostProjectsBulkDeleteMutationRequest,
  PostProjectsBulkDeleteMutationResponse,
  PostProjectsBulkDelete401,
} from "../types/PostProjectsBulkDelete.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostProjectsBulkDeleteUrl() {
  const res = { method: "POST", url: `/projects/bulk-delete` as const };
  return res;
}

/**
 * @summary Soft-delete multiple projects
 * {@link /projects/bulk-delete}
 */
export async function postProjectsBulkDelete(
  data: PostProjectsBulkDeleteMutationRequest,
  config: Partial<RequestConfig<PostProjectsBulkDeleteMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProjectsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostProjectsBulkDelete401>,
    PostProjectsBulkDeleteMutationRequest
  >({
    method: "POST",
    url: getPostProjectsBulkDeleteUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
