/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostProjectsIdStateMutationRequest,
  PostProjectsIdStateMutationResponse,
  PostProjectsIdStatePathParams,
  PostProjectsIdState401,
  PostProjectsIdState404,
  PostProjectsIdState422,
} from "../types/PostProjectsIdState.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostProjectsIdStateUrl(id: PostProjectsIdStatePathParams["id"]) {
  const res = { method: "POST", url: `/projects/${id}/state` as const };
  return res;
}

/**
 * @summary Change project state
 * {@link /projects/:id/state}
 */
export async function postProjectsIdState(
  id: PostProjectsIdStatePathParams["id"],
  data: PostProjectsIdStateMutationRequest,
  config: Partial<RequestConfig<PostProjectsIdStateMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProjectsIdStateMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdState401 | PostProjectsIdState404 | PostProjectsIdState422
    >,
    PostProjectsIdStateMutationRequest
  >({
    method: "POST",
    url: getPostProjectsIdStateUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
