/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostEnrichmentsMutationRequest,
  PostEnrichmentsMutationResponse,
  PostEnrichments400,
  PostEnrichments401,
  PostEnrichments404,
  PostEnrichments422,
} from "../types/PostEnrichments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostEnrichmentsUrl() {
  const res = { method: "POST", url: `/enrichments` as const };
  return res;
}

/**
 * @summary Request LLM enrichment for a single contact
 * {@link /enrichments}
 */
export async function postEnrichments(
  data: PostEnrichmentsMutationRequest,
  config: Partial<RequestConfig<PostEnrichmentsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostEnrichmentsMutationResponse,
    ResponseErrorConfig<
      | PostEnrichments400
      | PostEnrichments401
      | PostEnrichments404
      | PostEnrichments422
    >,
    PostEnrichmentsMutationRequest
  >({
    method: "POST",
    url: getPostEnrichmentsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
