/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostProjectsIdExpensesMutationRequest,
  PostProjectsIdExpensesMutationResponse,
  PostProjectsIdExpensesPathParams,
  PostProjectsIdExpenses401,
  PostProjectsIdExpenses404,
} from "../types/PostProjectsIdExpenses.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostProjectsIdExpensesUrl(
  id: PostProjectsIdExpensesPathParams["id"],
) {
  const res = { method: "POST", url: `/projects/${id}/expenses` as const };
  return res;
}

/**
 * @summary Add an expense to a project
 * {@link /projects/:id/expenses}
 */
export async function postProjectsIdExpenses(
  id: PostProjectsIdExpensesPathParams["id"],
  data: PostProjectsIdExpensesMutationRequest,
  config: Partial<RequestConfig<PostProjectsIdExpensesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProjectsIdExpensesMutationResponse,
    ResponseErrorConfig<PostProjectsIdExpenses401 | PostProjectsIdExpenses404>,
    PostProjectsIdExpensesMutationRequest
  >({
    method: "POST",
    url: getPostProjectsIdExpensesUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
