/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostContactsIdAssignmentsMutationRequest,
  PostContactsIdAssignmentsMutationResponse,
  PostContactsIdAssignmentsPathParams,
  PostContactsIdAssignments401,
  PostContactsIdAssignments404,
} from "../types/PostContactsIdAssignments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostContactsIdAssignmentsUrl(
  id: PostContactsIdAssignmentsPathParams["id"],
) {
  const res = { method: "POST", url: `/contacts/${id}/assignments` as const };
  return res;
}

/**
 * @summary Assign a user to a contact
 * {@link /contacts/:id/assignments}
 */
export async function postContactsIdAssignments(
  id: PostContactsIdAssignmentsPathParams["id"],
  data: PostContactsIdAssignmentsMutationRequest,
  config: Partial<RequestConfig<PostContactsIdAssignmentsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostContactsIdAssignmentsMutationResponse,
    ResponseErrorConfig<
      PostContactsIdAssignments401 | PostContactsIdAssignments404
    >,
    PostContactsIdAssignmentsMutationRequest
  >({
    method: "POST",
    url: getPostContactsIdAssignmentsUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
