/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/http-client";
import type {
  PostUsersMutationRequest,
  PostUsersMutationResponse,
  PostUsers401,
  PostUsers409,
} from "../types/PostUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";

function getPostUsersUrl() {
  const res = { method: "POST", url: `/users` as const };
  return res;
}

/**
 * @summary Create a user
 * {@link /users}
 */
export async function postUsers(
  data: PostUsersMutationRequest,
  config: Partial<RequestConfig<PostUsersMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostUsersMutationResponse,
    ResponseErrorConfig<PostUsers401 | PostUsers409>,
    PostUsersMutationRequest
  >({
    method: "POST",
    url: getPostUsersUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
