/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostImportsMutationResponse,
  PostImports400,
  PostImports401,
} from "../types/PostImports.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostImportsUrl() {
  const res = { method: "POST", url: `/imports` as const };
  return res;
}

/**
 * @summary Upload an xlsx file and start an import
 * {@link /imports}
 */
export async function postImports(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostImportsMutationResponse,
    ResponseErrorConfig<PostImports400 | PostImports401>,
    unknown
  >({
    method: "POST",
    url: getPostImportsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
