/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostEnrichmentsBatchMutationRequest,
  PostEnrichmentsBatchMutationResponse,
  PostEnrichmentsBatch400,
  PostEnrichmentsBatch401,
  PostEnrichmentsBatch422,
} from "../types/PostEnrichmentsBatch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostEnrichmentsBatchUrl() {
  const res = { method: "POST", url: `/enrichments/batch` as const };
  return res;
}

/**
 * @summary Request LLM enrichment for multiple contacts
 * {@link /enrichments/batch}
 */
export async function postEnrichmentsBatch(
  data: PostEnrichmentsBatchMutationRequest,
  config: Partial<RequestConfig<PostEnrichmentsBatchMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostEnrichmentsBatchMutationResponse,
    ResponseErrorConfig<
      | PostEnrichmentsBatch400
      | PostEnrichmentsBatch401
      | PostEnrichmentsBatch422
    >,
    PostEnrichmentsBatchMutationRequest
  >({
    method: "POST",
    url: getPostEnrichmentsBatchUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
