/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostProjectsMutationRequest,
  PostProjectsMutationResponse,
  PostProjects401,
} from "../types/PostProjects.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostProjectsUrl() {
  const res = { method: "POST", url: `/projects` as const };
  return res;
}

/**
 * @summary Create a project
 * {@link /projects}
 */
export async function postProjects(
  data: PostProjectsMutationRequest,
  config: Partial<RequestConfig<PostProjectsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProjectsMutationResponse,
    ResponseErrorConfig<PostProjects401>,
    PostProjectsMutationRequest
  >({
    method: "POST",
    url: getPostProjectsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
