/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostProjectsIdExtensionsMutationRequest,
  PostProjectsIdExtensionsMutationResponse,
  PostProjectsIdExtensionsPathParams,
  PostProjectsIdExtensions401,
  PostProjectsIdExtensions404,
} from "../types/PostProjectsIdExtensions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostProjectsIdExtensionsUrl(
  id: PostProjectsIdExtensionsPathParams["id"],
) {
  const res = { method: "POST", url: `/projects/${id}/extensions` as const };
  return res;
}

/**
 * @summary Add an extension to a project
 * {@link /projects/:id/extensions}
 */
export async function postProjectsIdExtensions(
  id: PostProjectsIdExtensionsPathParams["id"],
  data: PostProjectsIdExtensionsMutationRequest,
  config: Partial<RequestConfig<PostProjectsIdExtensionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProjectsIdExtensionsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdExtensions401 | PostProjectsIdExtensions404
    >,
    PostProjectsIdExtensionsMutationRequest
  >({
    method: "POST",
    url: getPostProjectsIdExtensionsUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
