/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostContactsIdChannelsMutationRequest,
  PostContactsIdChannelsMutationResponse,
  PostContactsIdChannelsPathParams,
  PostContactsIdChannels401,
  PostContactsIdChannels404,
} from "../types/PostContactsIdChannels.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostContactsIdChannelsUrl(
  id: PostContactsIdChannelsPathParams["id"],
) {
  const res = { method: "POST", url: `/contacts/${id}/channels` as const };
  return res;
}

/**
 * @summary Add a communication channel to a contact
 * {@link /contacts/:id/channels}
 */
export async function postContactsIdChannels(
  id: PostContactsIdChannelsPathParams["id"],
  data: PostContactsIdChannelsMutationRequest,
  config: Partial<RequestConfig<PostContactsIdChannelsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostContactsIdChannelsMutationResponse,
    ResponseErrorConfig<PostContactsIdChannels401 | PostContactsIdChannels404>,
    PostContactsIdChannelsMutationRequest
  >({
    method: "POST",
    url: getPostContactsIdChannelsUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
