/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/lib/utils/http-client";
import type {
  PostAnalysisTemplatesMutationRequest,
  PostAnalysisTemplatesMutationResponse,
  PostAnalysisTemplates400,
  PostAnalysisTemplates401,
} from "../types/PostAnalysisTemplates.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";

function getPostAnalysisTemplatesUrl() {
  const res = { method: "POST", url: `/analysis-templates` as const };
  return res;
}

/**
 * @summary Create an analysis template
 * {@link /analysis-templates}
 */
export async function postAnalysisTemplates(
  data: PostAnalysisTemplatesMutationRequest,
  config: Partial<RequestConfig<PostAnalysisTemplatesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAnalysisTemplatesMutationResponse,
    ResponseErrorConfig<PostAnalysisTemplates400 | PostAnalysisTemplates401>,
    PostAnalysisTemplatesMutationRequest
  >({
    method: "POST",
    url: getPostAnalysisTemplatesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
