/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const addExtensionBodySchema = z.object({
  additionalDays: z
    .int()
    .gt(0)
    .describe("Number of additional days to extend the project"),
  reason: z.string().min(1).describe("Reason for the extension"),
  cost: z
    .int()
    .min(0)
    .describe("Extension cost in minor currency units")
    .nullish(),
  billedAmount: z
    .int()
    .min(0)
    .describe("Amount billed for this extension in minor currency units")
    .nullish(),
  grantedAt: z.iso
    .date()
    .describe("Date the extension was granted (YYYY-MM-DD)"),
});
