/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const addResponsibleBodySchema = z.object({
  userId: z.uuid().describe("UUID of the user being assigned"),
  role: z.enum(["Lead", "Member"]).describe("Responsible role"),
});
