/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const bulkDeleteContactsBodySchema = z.object({
  ids: z
    .array(z.string().min(1))
    .min(1)
    .max(500)
    .describe("IDs of contacts to soft-delete (1 to 500)."),
});
