/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const changeStateBodySchema = z.object({
  newState: z
    .enum(["Contact", "Lead", "Customer", "Discarded"])
    .describe("Target pipeline state"),
});
