/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const contactEventViewSchema = z.object({
  id: z.string().describe("Event UUID"),
  contactId: z.string().describe("Contact UUID"),
  authorId: z.string().describe("User UUID who authored the event"),
  eventType: z.enum([
    "FirstContact",
    "MessageSent",
    "ResponseReceived",
    "MeetingCall",
    "ProposalSent",
    "ProposalWon",
    "ProposalRejected",
    "FollowUpPending",
    "Note",
  ]),
  detail: z.string(),
  occurredAt: z.string().describe("ISO 8601 timestamp"),
  createdAt: z.string().describe("ISO 8601 timestamp"),
});
