/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactEventViewSchema } from "./contactEventViewSchema.ts";
import { z } from "zod/v4";

export const contactEventListResponseSchema = z.object({
  get items() {
    return z.array(contactEventViewSchema).describe("List of items");
  },
  total: z.int().describe("Total number of items"),
  limit: z.int().describe("Page size"),
  offset: z.int().describe("Page offset"),
});
