/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const contactAssignmentListItemSchema = z.object({
  userId: z.string().describe("UUID of the assigned user"),
  userName: z.string().describe("Display name of the assigned user"),
  role: z.enum(["Owner", "Collaborator"]),
  assignedBy: z
    .string()
    .describe("UUID of the user that performed the assignment"),
  assignedAt: z.string().describe("ISO 8601 timestamp"),
});
