/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const contactViewSchema = z.object({
  id: z.string().describe("Contact UUID"),
  name: z.string(),
  phone: z.nullable(z.string()),
  pipelineState: z.enum(["Contact", "Lead", "Customer", "Discarded"]),
  stateLocked: z.boolean(),
  sourceChannel: z.nullable(
    z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
  ),
  interestLevel: z.nullable(z.enum(["Cold", "Warm", "Hot"])),
  createdBy: z.string().describe("User UUID who created this contact"),
  creator: z.optional(
    z
      .object({
        id: z.string(),
        name: z.string(),
      })
      .describe("Creator user data, present only when populated=true"),
  ),
  createdAt: z.string().describe("ISO 8601 timestamp"),
  updatedAt: z.string().describe("ISO 8601 timestamp"),
});
