/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const createContactBodySchema = z.object({
  name: z.string().min(1).describe("Contact full name"),
  handle: z.string().describe("Social handle or username").nullish(),
  phone: z.string().describe("Phone number").nullish(),
  sourceChannel: z
    .enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"])
    .describe("Acquisition channel")
    .nullish(),
  interestLevel: z
    .enum(["Cold", "Warm", "Hot"])
    .describe("Interest level")
    .nullish(),
});
