/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

export const deleteProjectsIdExpensesExpenseidPathParamsSchema = z.object({
  id: z.string(),
  expenseId: z.string(),
});

/**
 * @description Expense removed. Returns updated project.
 */
export const deleteProjectsIdExpensesExpenseid200Schema = z.lazy(
  () => projectViewSchema,
);

/**
 * @description Unauthorized.
 */
export const deleteProjectsIdExpensesExpenseid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Project or expense not found.
 */
export const deleteProjectsIdExpensesExpenseid404Schema = z.lazy(
  () => problemSchema,
);

export const deleteProjectsIdExpensesExpenseidMutationResponseSchema = z.lazy(
  () => deleteProjectsIdExpensesExpenseid200Schema,
);
