/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const deleteContactsIdChannelsChannelidPathParamsSchema = z.object({
  id: z.string(),
  channelId: z.string(),
});

/**
 * @description Channel removed. Returns updated contact.
 */
export const deleteContactsIdChannelsChannelid200Schema = z.lazy(
  () => contactViewSchema,
);

/**
 * @description Unauthorized.
 */
export const deleteContactsIdChannelsChannelid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Contact not found.
 */
export const deleteContactsIdChannelsChannelid404Schema = z.lazy(
  () => problemSchema,
);

export const deleteContactsIdChannelsChannelidMutationResponseSchema = z.lazy(
  () => deleteContactsIdChannelsChannelid200Schema,
);
