/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const deleteUsersIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description User deleted.
 */
export const deleteUsersId204Schema = z.any();

/**
 * @description Unauthorized.
 */
export const deleteUsersId401Schema = z.lazy(() => problemSchema);

/**
 * @description User not found.
 */
export const deleteUsersId404Schema = z.lazy(() => problemSchema);

export const deleteUsersIdMutationResponseSchema = z.lazy(
  () => deleteUsersId204Schema,
);
