/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

export const deleteProjectsIdBudgetItemsItemidPathParamsSchema = z.object({
  id: z.string(),
  itemId: z.string(),
});

/**
 * @description Budget item removed. Returns updated project.
 */
export const deleteProjectsIdBudgetItemsItemid200Schema = z.lazy(
  () => projectViewSchema,
);

/**
 * @description Unauthorized.
 */
export const deleteProjectsIdBudgetItemsItemid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Project or budget item not found.
 */
export const deleteProjectsIdBudgetItemsItemid404Schema = z.lazy(
  () => problemSchema,
);

export const deleteProjectsIdBudgetItemsItemidMutationResponseSchema = z.lazy(
  () => deleteProjectsIdBudgetItemsItemid200Schema,
);
