/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const deleteProjectsIdDocumentsDocidPathParamsSchema = z.object({
  id: z.string(),
  docId: z.string(),
});

/**
 * @description Document deleted.
 */
export const deleteProjectsIdDocumentsDocid204Schema = z.any();

/**
 * @description Unauthorized.
 */
export const deleteProjectsIdDocumentsDocid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Project or document not found.
 */
export const deleteProjectsIdDocumentsDocid404Schema = z.lazy(
  () => problemSchema,
);

export const deleteProjectsIdDocumentsDocidMutationResponseSchema = z.lazy(
  () => deleteProjectsIdDocumentsDocid204Schema,
);
