/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { meResponseSchema } from "./meResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Usuario autenticado.
 */
export const getAuthMe200Schema = z.lazy(() => meResponseSchema);

/**
 * @description No autenticado.
 */
export const getAuthMe401Schema = z.lazy(() => problemSchema);

export const getAuthMeQueryResponseSchema = z.lazy(() => getAuthMe200Schema);
