/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Array of templates.
 */
export const getAnalysisTemplates200Schema = z.array(
  z.object({
    id: z.uuid(),
    name: z.string(),
    rubro: z.string(),
    prompt: z.string(),
    modelProvider: z.string(),
    version: z.int(),
    isActive: z.boolean(),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
);

/**
 * @description Unauthorized.
 */
export const getAnalysisTemplates401Schema = z.lazy(() => problemSchema);

export const getAnalysisTemplatesQueryResponseSchema = z.lazy(
  () => getAnalysisTemplates200Schema,
);
