/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getContactsIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Contact found.
 */
export const getContactsId200Schema = z.lazy(() => contactViewSchema);

/**
 * @description Unauthorized.
 */
export const getContactsId401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const getContactsId404Schema = z.lazy(() => problemSchema);

export const getContactsIdQueryResponseSchema = z.lazy(
  () => getContactsId200Schema,
);
