/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactKpisResponseSchema } from "./contactKpisResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Pipeline KPIs for current and previous 30-day windows.
 */
export const getContactsKpis200Schema = z.lazy(() => contactKpisResponseSchema);

/**
 * @description Unauthorized.
 */
export const getContactsKpis401Schema = z.lazy(() => problemSchema);

export const getContactsKpisQueryResponseSchema = z.lazy(
  () => getContactsKpis200Schema,
);
