/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactListResponseSchema } from "./contactListResponseSchema.ts";
import { filterGroupObjectSchema } from "./filterGroupObjectSchema.ts";
import { paginationSchema } from "./paginationSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getContactsQueryParamsSchema = z
  .object({
    filter: z.optional(
      z.object({
        id: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        name: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        contactType: z.optional(
          z.object({
            eq: z.optional(
              z.union([
                z.array(z.enum(["Person", "Company"])),
                z.enum(["Person", "Company"]),
              ]),
            ),
            ne: z.optional(
              z.union([
                z.array(z.enum(["Person", "Company"])),
                z.enum(["Person", "Company"]),
              ]),
            ),
            in: z.optional(
              z.union([
                z.array(z.enum(["Person", "Company"])),
                z.enum(["Person", "Company"]),
              ]),
            ),
            nin: z.optional(
              z.union([
                z.array(z.enum(["Person", "Company"])),
                z.enum(["Person", "Company"]),
              ]),
            ),
            isNull: z.optional(
              z.union([
                z.array(z.enum(["Person", "Company"])),
                z.enum(["Person", "Company"]),
              ]),
            ),
            isNotNull: z.optional(
              z.union([
                z.array(z.enum(["Person", "Company"])),
                z.enum(["Person", "Company"]),
              ]),
            ),
          }),
        ),
        sex: z.optional(
          z.object({
            eq: z.optional(
              z.union([
                z.array(z.enum(["Male", "Female", "Other", "Unspecified"])),
                z.enum(["Male", "Female", "Other", "Unspecified"]),
              ]),
            ),
            ne: z.optional(
              z.union([
                z.array(z.enum(["Male", "Female", "Other", "Unspecified"])),
                z.enum(["Male", "Female", "Other", "Unspecified"]),
              ]),
            ),
            in: z.optional(
              z.union([
                z.array(z.enum(["Male", "Female", "Other", "Unspecified"])),
                z.enum(["Male", "Female", "Other", "Unspecified"]),
              ]),
            ),
            nin: z.optional(
              z.union([
                z.array(z.enum(["Male", "Female", "Other", "Unspecified"])),
                z.enum(["Male", "Female", "Other", "Unspecified"]),
              ]),
            ),
            isNull: z.optional(
              z.union([
                z.array(z.enum(["Male", "Female", "Other", "Unspecified"])),
                z.enum(["Male", "Female", "Other", "Unspecified"]),
              ]),
            ),
            isNotNull: z.optional(
              z.union([
                z.array(z.enum(["Male", "Female", "Other", "Unspecified"])),
                z.enum(["Male", "Female", "Other", "Unspecified"]),
              ]),
            ),
          }),
        ),
        addressStreet: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        addressNumber: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        addressPostalCode: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        addressCity: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        addressProvince: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        addressCountry: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        notes: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        pipelineState: z.optional(
          z.object({
            eq: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Contact",
                    "Lead",
                    "AtRisk",
                    "Customer",
                    "Discarded",
                  ]),
                ),
                z.enum(["Contact", "Lead", "AtRisk", "Customer", "Discarded"]),
              ]),
            ),
            ne: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Contact",
                    "Lead",
                    "AtRisk",
                    "Customer",
                    "Discarded",
                  ]),
                ),
                z.enum(["Contact", "Lead", "AtRisk", "Customer", "Discarded"]),
              ]),
            ),
            in: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Contact",
                    "Lead",
                    "AtRisk",
                    "Customer",
                    "Discarded",
                  ]),
                ),
                z.enum(["Contact", "Lead", "AtRisk", "Customer", "Discarded"]),
              ]),
            ),
            nin: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Contact",
                    "Lead",
                    "AtRisk",
                    "Customer",
                    "Discarded",
                  ]),
                ),
                z.enum(["Contact", "Lead", "AtRisk", "Customer", "Discarded"]),
              ]),
            ),
            isNull: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Contact",
                    "Lead",
                    "AtRisk",
                    "Customer",
                    "Discarded",
                  ]),
                ),
                z.enum(["Contact", "Lead", "AtRisk", "Customer", "Discarded"]),
              ]),
            ),
            isNotNull: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Contact",
                    "Lead",
                    "AtRisk",
                    "Customer",
                    "Discarded",
                  ]),
                ),
                z.enum(["Contact", "Lead", "AtRisk", "Customer", "Discarded"]),
              ]),
            ),
          }),
        ),
        sourceChannel: z.optional(
          z.object({
            eq: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Instagram",
                    "WhatsApp",
                    "Referral",
                    "Email",
                    "Other",
                  ]),
                ),
                z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
              ]),
            ),
            ne: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Instagram",
                    "WhatsApp",
                    "Referral",
                    "Email",
                    "Other",
                  ]),
                ),
                z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
              ]),
            ),
            in: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Instagram",
                    "WhatsApp",
                    "Referral",
                    "Email",
                    "Other",
                  ]),
                ),
                z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
              ]),
            ),
            nin: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Instagram",
                    "WhatsApp",
                    "Referral",
                    "Email",
                    "Other",
                  ]),
                ),
                z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
              ]),
            ),
            isNull: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Instagram",
                    "WhatsApp",
                    "Referral",
                    "Email",
                    "Other",
                  ]),
                ),
                z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
              ]),
            ),
            isNotNull: z.optional(
              z.union([
                z.array(
                  z.enum([
                    "Instagram",
                    "WhatsApp",
                    "Referral",
                    "Email",
                    "Other",
                  ]),
                ),
                z.enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"]),
              ]),
            ),
          }),
        ),
        interestLevel: z.optional(
          z.object({
            eq: z.optional(
              z.union([
                z.array(z.enum(["Cold", "Warm", "Hot"])),
                z.enum(["Cold", "Warm", "Hot"]),
              ]),
            ),
            ne: z.optional(
              z.union([
                z.array(z.enum(["Cold", "Warm", "Hot"])),
                z.enum(["Cold", "Warm", "Hot"]),
              ]),
            ),
            in: z.optional(
              z.union([
                z.array(z.enum(["Cold", "Warm", "Hot"])),
                z.enum(["Cold", "Warm", "Hot"]),
              ]),
            ),
            nin: z.optional(
              z.union([
                z.array(z.enum(["Cold", "Warm", "Hot"])),
                z.enum(["Cold", "Warm", "Hot"]),
              ]),
            ),
            isNull: z.optional(
              z.union([
                z.array(z.enum(["Cold", "Warm", "Hot"])),
                z.enum(["Cold", "Warm", "Hot"]),
              ]),
            ),
            isNotNull: z.optional(
              z.union([
                z.array(z.enum(["Cold", "Warm", "Hot"])),
                z.enum(["Cold", "Warm", "Hot"]),
              ]),
            ),
          }),
        ),
        createdBy: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        createdAt: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            gt: z.optional(z.union([z.array(z.string()), z.string()])),
            gte: z.optional(z.union([z.array(z.string()), z.string()])),
            lt: z.optional(z.union([z.array(z.string()), z.string()])),
            lte: z.optional(z.union([z.array(z.string()), z.string()])),
            between: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        updatedAt: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            gt: z.optional(z.union([z.array(z.string()), z.string()])),
            gte: z.optional(z.union([z.array(z.string()), z.string()])),
            lt: z.optional(z.union([z.array(z.string()), z.string()])),
            lte: z.optional(z.union([z.array(z.string()), z.string()])),
            between: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        deletedAt: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            gt: z.optional(z.union([z.array(z.string()), z.string()])),
            gte: z.optional(z.union([z.array(z.string()), z.string()])),
            lt: z.optional(z.union([z.array(z.string()), z.string()])),
            lte: z.optional(z.union([z.array(z.string()), z.string()])),
            between: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        get or() {
          return z.array(filterGroupObjectSchema).max(10).optional();
        },
      }),
    ),
    search: z.optional(z.string().min(1)),
    get pagination() {
      return paginationSchema.optional();
    },
    sort: z.optional(z.string()),
  })
  .optional();

/**
 * @description Paginated list of contacts.
 */
export const getContacts200Schema = z.lazy(() => contactListResponseSchema);

/**
 * @description Unauthorized.
 */
export const getContacts401Schema = z.lazy(() => problemSchema);

export const getContactsQueryResponseSchema = z.lazy(
  () => getContacts200Schema,
);
