/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactAssignmentListResponseSchema } from "./contactAssignmentListResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getContactsIdAssignmentsPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Paginated list of assignments.
 */
export const getContactsIdAssignments200Schema = z.lazy(
  () => contactAssignmentListResponseSchema,
);

/**
 * @description Unauthorized.
 */
export const getContactsIdAssignments401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const getContactsIdAssignments404Schema = z.lazy(() => problemSchema);

export const getContactsIdAssignmentsQueryResponseSchema = z.lazy(
  () => getContactsIdAssignments200Schema,
);
