/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactStateChangeListResponseSchema } from "./contactStateChangeListResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getContactsIdStateChangesPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Paginated list of state changes.
 */
export const getContactsIdStateChanges200Schema = z.lazy(
  () => contactStateChangeListResponseSchema,
);

/**
 * @description Unauthorized.
 */
export const getContactsIdStateChanges401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const getContactsIdStateChanges404Schema = z.lazy(() => problemSchema);

export const getContactsIdStateChangesQueryResponseSchema = z.lazy(
  () => getContactsIdStateChanges200Schema,
);
