/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getEnrichmentsQueryParamsSchema = z.object({
  contactId: z.uuid(),
});

/**
 * @description Insights for the given contact, newest first.
 */
export const getEnrichments200Schema = z.array(
  z.object({
    id: z.uuid(),
    contactId: z.uuid(),
    templateId: z.uuid(),
    templateVersion: z.int(),
    triggerKind: z.enum(["post_import", "batch", "individual", "retry"]),
    status: z.enum(["queued", "processing", "completed", "failed"]),
    attempts: z.int(),
    result: z.nullable(
      z.object({
        resumen: z.string(),
        recomendaciones: z.array(z.string()),
        observaciones: z.string(),
      }),
    ),
    modelUsed: z.nullable(z.string()),
    promptTokens: z.nullable(z.int()),
    completionTokens: z.nullable(z.int()),
    costUsd: z.nullable(z.string()),
    lastError: z.nullable(z.string()),
    completedAt: z.nullable(z.string()),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
);

/**
 * @description Missing or invalid contactId.
 */
export const getEnrichments400Schema = z.lazy(() => problemSchema);

/**
 * @description Unauthorized.
 */
export const getEnrichments401Schema = z.lazy(() => problemSchema);

export const getEnrichmentsQueryResponseSchema = z.lazy(
  () => getEnrichments200Schema,
);
