/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { importStatusResponseSchema } from "./importStatusResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getImportsIdPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Import status with progress counters and optional rejected.csv link.
 */
export const getImportsId200Schema = z.lazy(() => importStatusResponseSchema);

/**
 * @description Unauthorized.
 */
export const getImportsId401Schema = z.lazy(() => problemSchema);

/**
 * @description Import not found.
 */
export const getImportsId404Schema = z.lazy(() => problemSchema);

export const getImportsIdQueryResponseSchema = z.lazy(
  () => getImportsId200Schema,
);
