/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { importListResponseSchema } from "./importListResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const getImportsQueryParamsSchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .min(1)
    .max(100)
    .default(20)
    .describe("Number of items to return"),
  offset: z.nullable(
    z.coerce
      .number()
      .int()
      .min(0)
      .default(0)
      .describe("Number of items to skip"),
  ),
});

/**
 * @description Paginated list of imports, newest first.
 */
export const getImports200Schema = z.lazy(() => importListResponseSchema);

/**
 * @description Unauthorized.
 */
export const getImports401Schema = z.lazy(() => problemSchema);

export const getImportsQueryResponseSchema = z.lazy(() => getImports200Schema);
