/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectKpisResponseSchema } from "./projectKpisResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Status KPIs for current and previous 30-day windows.
 */
export const getProjectsKpis200Schema = z.lazy(() => projectKpisResponseSchema);

/**
 * @description Unauthorized.
 */
export const getProjectsKpis401Schema = z.lazy(() => problemSchema);

export const getProjectsKpisQueryResponseSchema = z.lazy(
  () => getProjectsKpis200Schema,
);
