/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectDocumentDownloadUrlSchema } from "./projectDocumentDownloadUrlSchema.ts";
import { z } from "zod/v4";

export const getProjectsIdDocumentsDocidDownloadUrlPathParamsSchema = z.object({
  id: z.string(),
  docId: z.string(),
});

/**
 * @description Presigned download URL.
 */
export const getProjectsIdDocumentsDocidDownloadUrl200Schema = z.lazy(
  () => projectDocumentDownloadUrlSchema,
);

/**
 * @description Unauthorized.
 */
export const getProjectsIdDocumentsDocidDownloadUrl401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Project or document not found.
 */
export const getProjectsIdDocumentsDocidDownloadUrl404Schema = z.lazy(
  () => problemSchema,
);

export const getProjectsIdDocumentsDocidDownloadUrlQueryResponseSchema = z.lazy(
  () => getProjectsIdDocumentsDocidDownloadUrl200Schema,
);
