/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { filterGroupObjectSchema } from "./filterGroupObjectSchema.ts";
import { paginationSchema } from "./paginationSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { projectDocumentListResponseSchema } from "./projectDocumentListResponseSchema.ts";
import { z } from "zod/v4";

export const getProjectsIdDocumentsPathParamsSchema = z.object({
  id: z.string(),
});

export const getProjectsIdDocumentsQueryParamsSchema = z
  .object({
    filter: z.optional(
      z.object({
        id: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        fileName: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        contentType: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        sizeBytes: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            ilike: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        uploadedBy: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            in: z.optional(z.union([z.array(z.string()), z.string()])),
            nin: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        uploadedAt: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            gt: z.optional(z.union([z.array(z.string()), z.string()])),
            gte: z.optional(z.union([z.array(z.string()), z.string()])),
            lt: z.optional(z.union([z.array(z.string()), z.string()])),
            lte: z.optional(z.union([z.array(z.string()), z.string()])),
            between: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        createdAt: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            gt: z.optional(z.union([z.array(z.string()), z.string()])),
            gte: z.optional(z.union([z.array(z.string()), z.string()])),
            lt: z.optional(z.union([z.array(z.string()), z.string()])),
            lte: z.optional(z.union([z.array(z.string()), z.string()])),
            between: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        updatedAt: z.optional(
          z.object({
            eq: z.optional(z.union([z.array(z.string()), z.string()])),
            ne: z.optional(z.union([z.array(z.string()), z.string()])),
            gt: z.optional(z.union([z.array(z.string()), z.string()])),
            gte: z.optional(z.union([z.array(z.string()), z.string()])),
            lt: z.optional(z.union([z.array(z.string()), z.string()])),
            lte: z.optional(z.union([z.array(z.string()), z.string()])),
            between: z.optional(z.union([z.array(z.string()), z.string()])),
            isNull: z.optional(z.union([z.array(z.string()), z.string()])),
            isNotNull: z.optional(z.union([z.array(z.string()), z.string()])),
          }),
        ),
        get or() {
          return z.array(filterGroupObjectSchema).max(10).optional();
        },
      }),
    ),
    search: z.optional(z.string().min(1)),
    get pagination() {
      return paginationSchema.optional();
    },
    sort: z.optional(z.string()),
  })
  .optional();

/**
 * @description Paginated list of documents.
 */
export const getProjectsIdDocuments200Schema = z.lazy(
  () => projectDocumentListResponseSchema,
);

/**
 * @description Unauthorized.
 */
export const getProjectsIdDocuments401Schema = z.lazy(() => problemSchema);

/**
 * @description Project not found.
 */
export const getProjectsIdDocuments404Schema = z.lazy(() => problemSchema);

export const getProjectsIdDocumentsQueryResponseSchema = z.lazy(
  () => getProjectsIdDocuments200Schema,
);
