/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { userViewSchema } from "./userViewSchema.ts";
import { z } from "zod/v4";

export const getUsersIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description User found.
 */
export const getUsersId200Schema = z.lazy(() => userViewSchema);

/**
 * @description Unauthorized.
 */
export const getUsersId401Schema = z.lazy(() => problemSchema);

/**
 * @description User not found.
 */
export const getUsersId404Schema = z.lazy(() => problemSchema);

export const getUsersIdQueryResponseSchema = z.lazy(() => getUsersId200Schema);
