/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { userListResponseSchema } from "./userListResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Paginated list of users.
 */
export const getUsers200Schema = z.lazy(() => userListResponseSchema);

/**
 * @description Unauthorized.
 */
export const getUsers401Schema = z.lazy(() => problemSchema);

export const getUsersQueryResponseSchema = z.lazy(() => getUsers200Schema);
