/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const importUploadResponseSchema = z.object({
  importId: z.uuid().describe("UUID of the created import record"),
  status: z.string().describe("Import status after upload (awaiting_mapping)"),
  columnHeaders: z
    .array(z.string())
    .describe(
      "Column headers detected from the first row of the uploaded file",
    ),
});
