/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const importSetMappingResponseSchema = z.object({
  importId: z.uuid().describe("UUID of the import record"),
  status: z.string().describe("Import status after mapping (pending)"),
});
