/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const paginationSchema = z.object({
  limit: z.optional(z.int().min(1).max(100).default(20)),
  offset: z.int().min(0).default(0).nullish(),
});
