/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { updateAssignmentRoleBodySchema } from "./updateAssignmentRoleBodySchema.ts";
import { z } from "zod/v4";

export const patchContactsIdAssignmentsUseridPathParamsSchema = z.object({
  id: z.string(),
  userId: z.string(),
});

/**
 * @description Assignment role updated. Returns updated contact.
 */
export const patchContactsIdAssignmentsUserid200Schema = z.lazy(
  () => contactViewSchema,
);

/**
 * @description Unauthorized.
 */
export const patchContactsIdAssignmentsUserid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Contact or assignment not found.
 */
export const patchContactsIdAssignmentsUserid404Schema = z.lazy(
  () => problemSchema,
);

export const patchContactsIdAssignmentsUseridMutationRequestSchema = z.lazy(
  () => updateAssignmentRoleBodySchema,
);

export const patchContactsIdAssignmentsUseridMutationResponseSchema = z.lazy(
  () => patchContactsIdAssignmentsUserid200Schema,
);
