/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { updateProjectBodySchema } from "./updateProjectBodySchema.ts";
import { z } from "zod/v4";

export const patchProjectsIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Project updated.
 */
export const patchProjectsId200Schema = z.lazy(() => projectViewSchema);

/**
 * @description Unauthorized.
 */
export const patchProjectsId401Schema = z.lazy(() => problemSchema);

/**
 * @description Project not found.
 */
export const patchProjectsId404Schema = z.lazy(() => problemSchema);

export const patchProjectsIdMutationRequestSchema = z.lazy(
  () => updateProjectBodySchema,
);

export const patchProjectsIdMutationResponseSchema = z.lazy(
  () => patchProjectsId200Schema,
);
