/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { updateExpenseBodySchema } from "./updateExpenseBodySchema.ts";
import { z } from "zod/v4";

export const patchProjectsIdExpensesExpenseidPathParamsSchema = z.object({
  id: z.string(),
  expenseId: z.string(),
});

/**
 * @description Expense updated. Returns updated project.
 */
export const patchProjectsIdExpensesExpenseid200Schema = z.lazy(
  () => projectViewSchema,
);

/**
 * @description Unauthorized.
 */
export const patchProjectsIdExpensesExpenseid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Project or expense not found.
 */
export const patchProjectsIdExpensesExpenseid404Schema = z.lazy(
  () => problemSchema,
);

export const patchProjectsIdExpensesExpenseidMutationRequestSchema = z.lazy(
  () => updateExpenseBodySchema,
);

export const patchProjectsIdExpensesExpenseidMutationResponseSchema = z.lazy(
  () => patchProjectsIdExpensesExpenseid200Schema,
);
