/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { updateChannelBodySchema } from "./updateChannelBodySchema.ts";
import { z } from "zod/v4";

export const patchContactsIdChannelsChannelidPathParamsSchema = z.object({
  id: z.string(),
  channelId: z.string(),
});

/**
 * @description Channel updated. Returns updated contact.
 */
export const patchContactsIdChannelsChannelid200Schema = z.lazy(
  () => contactViewSchema,
);

/**
 * @description Unauthorized.
 */
export const patchContactsIdChannelsChannelid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Contact not found.
 */
export const patchContactsIdChannelsChannelid404Schema = z.lazy(
  () => problemSchema,
);

export const patchContactsIdChannelsChannelidMutationRequestSchema = z.lazy(
  () => updateChannelBodySchema,
);

export const patchContactsIdChannelsChannelidMutationResponseSchema = z.lazy(
  () => patchContactsIdChannelsChannelid200Schema,
);
