/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { updateExtensionBodySchema } from "./updateExtensionBodySchema.ts";
import { z } from "zod/v4";

export const patchProjectsIdExtensionsExtidPathParamsSchema = z.object({
  id: z.string(),
  extId: z.string(),
});

/**
 * @description Extension updated. Returns updated project.
 */
export const patchProjectsIdExtensionsExtid200Schema = z.lazy(
  () => projectViewSchema,
);

/**
 * @description Unauthorized.
 */
export const patchProjectsIdExtensionsExtid401Schema = z.lazy(
  () => problemSchema,
);

/**
 * @description Project or extension not found.
 */
export const patchProjectsIdExtensionsExtid404Schema = z.lazy(
  () => problemSchema,
);

export const patchProjectsIdExtensionsExtidMutationRequestSchema = z.lazy(
  () => updateExtensionBodySchema,
);

export const patchProjectsIdExtensionsExtidMutationResponseSchema = z.lazy(
  () => patchProjectsIdExtensionsExtid200Schema,
);
