/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const patchAnalysisTemplatesIdPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Template updated.
 */
export const patchAnalysisTemplatesId200Schema = z.object({
  id: z.uuid(),
  name: z.string(),
  rubro: z.string(),
  prompt: z.string(),
  modelProvider: z.string(),
  version: z.int(),
  isActive: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @description Validation error.
 */
export const patchAnalysisTemplatesId400Schema = z.lazy(() => problemSchema);

/**
 * @description Unauthorized.
 */
export const patchAnalysisTemplatesId401Schema = z.lazy(() => problemSchema);

/**
 * @description Template not found.
 */
export const patchAnalysisTemplatesId404Schema = z.lazy(() => problemSchema);

export const patchAnalysisTemplatesIdMutationRequestSchema = z.object({
  name: z.optional(z.string().min(1)),
  rubro: z.optional(z.string().min(1)),
  prompt: z.optional(z.string().min(1)),
  modelProvider: z.optional(z.string().min(1)),
});

export const patchAnalysisTemplatesIdMutationResponseSchema = z.lazy(
  () => patchAnalysisTemplatesId200Schema,
);
