/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { updateUserBodySchema } from "./updateUserBodySchema.ts";
import { userViewSchema } from "./userViewSchema.ts";
import { z } from "zod/v4";

export const patchUsersIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description User updated.
 */
export const patchUsersId200Schema = z.lazy(() => userViewSchema);

/**
 * @description Unauthorized.
 */
export const patchUsersId401Schema = z.lazy(() => problemSchema);

/**
 * @description User not found.
 */
export const patchUsersId404Schema = z.lazy(() => problemSchema);

export const patchUsersIdMutationRequestSchema = z.lazy(
  () => updateUserBodySchema,
);

export const patchUsersIdMutationResponseSchema = z.lazy(
  () => patchUsersId200Schema,
);
