/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { changeStateBodySchema } from "./changeStateBodySchema.ts";
import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const patchContactsIdStatePathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description State changed. Returns updated contact.
 */
export const patchContactsIdState200Schema = z.lazy(() => contactViewSchema);

/**
 * @description Unauthorized.
 */
export const patchContactsIdState401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const patchContactsIdState404Schema = z.lazy(() => problemSchema);

export const patchContactsIdStateMutationRequestSchema = z.lazy(
  () => changeStateBodySchema,
);

export const patchContactsIdStateMutationResponseSchema = z.lazy(
  () => patchContactsIdState200Schema,
);
