/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { updateContactBodySchema } from "./updateContactBodySchema.ts";
import { z } from "zod/v4";

export const patchContactsIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Contact updated.
 */
export const patchContactsId200Schema = z.lazy(() => contactViewSchema);

/**
 * @description Unauthorized.
 */
export const patchContactsId401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const patchContactsId404Schema = z.lazy(() => problemSchema);

export const patchContactsIdMutationRequestSchema = z.lazy(
  () => updateContactBodySchema,
);

export const patchContactsIdMutationResponseSchema = z.lazy(
  () => patchContactsId200Schema,
);
