/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addBudgetItemBodySchema } from "./addBudgetItemBodySchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

export const postProjectsIdBudgetItemsPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Budget item added. Returns updated project.
 */
export const postProjectsIdBudgetItems200Schema = z.lazy(
  () => projectViewSchema,
);

/**
 * @description Unauthorized.
 */
export const postProjectsIdBudgetItems401Schema = z.lazy(() => problemSchema);

/**
 * @description Project not found.
 */
export const postProjectsIdBudgetItems404Schema = z.lazy(() => problemSchema);

export const postProjectsIdBudgetItemsMutationRequestSchema = z.lazy(
  () => addBudgetItemBodySchema,
);

export const postProjectsIdBudgetItemsMutationResponseSchema = z.lazy(
  () => postProjectsIdBudgetItems200Schema,
);
