/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { changeProjectStateBodySchema } from "./changeProjectStateBodySchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

export const postProjectsIdStatePathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description State changed. Returns updated project.
 */
export const postProjectsIdState200Schema = z.lazy(() => projectViewSchema);

/**
 * @description Unauthorized.
 */
export const postProjectsIdState401Schema = z.lazy(() => problemSchema);

/**
 * @description Project not found.
 */
export const postProjectsIdState404Schema = z.lazy(() => problemSchema);

/**
 * @description Transition not allowed.
 */
export const postProjectsIdState422Schema = z.lazy(() => problemSchema);

export const postProjectsIdStateMutationRequestSchema = z.lazy(
  () => changeProjectStateBodySchema,
);

export const postProjectsIdStateMutationResponseSchema = z.lazy(
  () => postProjectsIdState200Schema,
);
