/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { registerEventBodySchema } from "./registerEventBodySchema.ts";
import { z } from "zod/v4";

export const postContactsIdEventsPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Event registered. Returns updated contact.
 */
export const postContactsIdEvents200Schema = z.lazy(() => contactViewSchema);

/**
 * @description Unauthorized.
 */
export const postContactsIdEvents401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const postContactsIdEvents404Schema = z.lazy(() => problemSchema);

export const postContactsIdEventsMutationRequestSchema = z.lazy(
  () => registerEventBodySchema,
);

export const postContactsIdEventsMutationResponseSchema = z.lazy(
  () => postContactsIdEvents200Schema,
);
