/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addAssignmentBodySchema } from "./addAssignmentBodySchema.ts";
import { contactViewSchema } from "./contactViewSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const postContactsIdAssignmentsPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Assignment added. Returns updated contact.
 */
export const postContactsIdAssignments200Schema = z.lazy(
  () => contactViewSchema,
);

/**
 * @description Unauthorized.
 */
export const postContactsIdAssignments401Schema = z.lazy(() => problemSchema);

/**
 * @description Contact not found.
 */
export const postContactsIdAssignments404Schema = z.lazy(() => problemSchema);

export const postContactsIdAssignmentsMutationRequestSchema = z.lazy(
  () => addAssignmentBodySchema,
);

export const postContactsIdAssignmentsMutationResponseSchema = z.lazy(
  () => postContactsIdAssignments200Schema,
);
