/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createUserBodySchema } from "./createUserBodySchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { userViewSchema } from "./userViewSchema.ts";
import { z } from "zod/v4";

/**
 * @description User created.
 */
export const postUsers201Schema = z.lazy(() => userViewSchema);

/**
 * @description Unauthorized.
 */
export const postUsers401Schema = z.lazy(() => problemSchema);

/**
 * @description Email already registered.
 */
export const postUsers409Schema = z.lazy(() => problemSchema);

export const postUsersMutationRequestSchema = z.lazy(
  () => createUserBodySchema,
);

export const postUsersMutationResponseSchema = z.lazy(() => postUsers201Schema);
