/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Template created.
 */
export const postAnalysisTemplates201Schema = z.object({
  id: z.uuid(),
  name: z.string(),
  rubro: z.string(),
  prompt: z.string(),
  modelProvider: z.string(),
  version: z.int(),
  isActive: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * @description Validation error.
 */
export const postAnalysisTemplates400Schema = z.lazy(() => problemSchema);

/**
 * @description Unauthorized.
 */
export const postAnalysisTemplates401Schema = z.lazy(() => problemSchema);

export const postAnalysisTemplatesMutationRequestSchema = z.object({
  name: z.string().min(1),
  rubro: z.string().min(1),
  prompt: z.string().min(1),
  modelProvider: z.string().min(1),
});

export const postAnalysisTemplatesMutationResponseSchema = z.lazy(
  () => postAnalysisTemplates201Schema,
);
