/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { importUploadResponseSchema } from "./importUploadResponseSchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Import created. Returns detected column headers for mapping.
 */
export const postImports201Schema = z.lazy(() => importUploadResponseSchema);

/**
 * @description Invalid file (wrong MIME, size exceeded, or missing file field).
 */
export const postImports400Schema = z.lazy(() => problemSchema);

/**
 * @description Unauthorized.
 */
export const postImports401Schema = z.lazy(() => problemSchema);

export const postImportsMutationResponseSchema = z.lazy(
  () => postImports201Schema,
);
