/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createProjectBodySchema } from "./createProjectBodySchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

/**
 * @description Project created.
 */
export const postProjects201Schema = z.lazy(() => projectViewSchema);

/**
 * @description Unauthorized.
 */
export const postProjects401Schema = z.lazy(() => problemSchema);

export const postProjectsMutationRequestSchema = z.lazy(
  () => createProjectBodySchema,
);

export const postProjectsMutationResponseSchema = z.lazy(
  () => postProjects201Schema,
);
