/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addResponsibleBodySchema } from "./addResponsibleBodySchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

export const postProjectsIdResponsiblesPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Responsible added. Returns updated project.
 */
export const postProjectsIdResponsibles200Schema = z.lazy(
  () => projectViewSchema,
);

/**
 * @description Unauthorized.
 */
export const postProjectsIdResponsibles401Schema = z.lazy(() => problemSchema);

/**
 * @description Project not found.
 */
export const postProjectsIdResponsibles404Schema = z.lazy(() => problemSchema);

export const postProjectsIdResponsiblesMutationRequestSchema = z.lazy(
  () => addResponsibleBodySchema,
);

export const postProjectsIdResponsiblesMutationResponseSchema = z.lazy(
  () => postProjectsIdResponsibles200Schema,
);
