/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Batch enrichment queued. Returns created insight IDs (duplicates skipped).
 */
export const postEnrichmentsBatch201Schema = z.object({
  insightIds: z.array(z.uuid()),
  count: z.int(),
});

/**
 * @description Validation error.
 */
export const postEnrichmentsBatch400Schema = z.lazy(() => problemSchema);

/**
 * @description Unauthorized.
 */
export const postEnrichmentsBatch401Schema = z.lazy(() => problemSchema);

/**
 * @description Template inactive.
 */
export const postEnrichmentsBatch422Schema = z.lazy(() => problemSchema);

export const postEnrichmentsBatchMutationRequestSchema = z.object({
  contactIds: z.array(z.uuid()).min(1),
  templateId: z.uuid(),
});

export const postEnrichmentsBatchMutationResponseSchema = z.lazy(
  () => postEnrichmentsBatch201Schema,
);
