/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

/**
 * @description Sesión iniciada. La cookie de sesión queda seteada.
 */
export const postAuthLogin200Schema = z.object({
  userId: z.string(),
});

/**
 * @description Credenciales inválidas.
 */
export const postAuthLogin401Schema = z.lazy(() => problemSchema);

export const postAuthLoginMutationRequestSchema = z.object({
  email: z.email(),
  password: z.string().min(1),
});

export const postAuthLoginMutationResponseSchema = z.lazy(
  () => postAuthLogin200Schema,
);
