/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemSchema } from "./problemSchema.ts";
import { z } from "zod/v4";

export const postEnrichmentsIdRetryPathParamsSchema = z.object({
  id: z.uuid(),
});

/**
 * @description Insight reset to queued and re-enqueued.
 */
export const postEnrichmentsIdRetry200Schema = z.object({
  insightId: z.uuid(),
});

/**
 * @description Unauthorized.
 */
export const postEnrichmentsIdRetry401Schema = z.lazy(() => problemSchema);

/**
 * @description Insight not found.
 */
export const postEnrichmentsIdRetry404Schema = z.lazy(() => problemSchema);

/**
 * @description Insight is not in failed status.
 */
export const postEnrichmentsIdRetry422Schema = z.lazy(() => problemSchema);

export const postEnrichmentsIdRetryMutationResponseSchema = z.lazy(
  () => postEnrichmentsIdRetry200Schema,
);
