/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addExpenseBodySchema } from "./addExpenseBodySchema.ts";
import { problemSchema } from "./problemSchema.ts";
import { projectViewSchema } from "./projectViewSchema.ts";
import { z } from "zod/v4";

export const postProjectsIdExpensesPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Expense added. Returns updated project.
 */
export const postProjectsIdExpenses200Schema = z.lazy(() => projectViewSchema);

/**
 * @description Unauthorized.
 */
export const postProjectsIdExpenses401Schema = z.lazy(() => problemSchema);

/**
 * @description Project not found.
 */
export const postProjectsIdExpenses404Schema = z.lazy(() => problemSchema);

export const postProjectsIdExpensesMutationRequestSchema = z.lazy(
  () => addExpenseBodySchema,
);

export const postProjectsIdExpensesMutationResponseSchema = z.lazy(
  () => postProjectsIdExpenses200Schema,
);
