/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const projectDocumentViewSchema = z.object({
  id: z.string().describe("Document UUID"),
  projectId: z.string().describe("Project UUID"),
  fileName: z.string().describe("Sanitized file name"),
  contentType: z.string().describe("MIME type"),
  sizeBytes: z.number().describe("File size in bytes"),
  uploadedBy: z.string().describe("User UUID who uploaded the document"),
  uploadedAt: z.string().describe("ISO 8601 timestamp"),
  createdAt: z.string().describe("ISO 8601 timestamp"),
  updatedAt: z.string().describe("ISO 8601 timestamp"),
});
