/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const projectBudgetItemViewSchema = z.object({
  id: z.string().describe("Budget item UUID"),
  projectId: z.string().describe("Project UUID"),
  concept: z.string(),
  amountMinor: z.number().describe("Amount in minor currency units"),
  createdAt: z.string().describe("ISO 8601 timestamp"),
  updatedAt: z.string().describe("ISO 8601 timestamp"),
});
