/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const projectExtensionViewSchema = z.object({
  id: z.string().describe("Extension UUID"),
  projectId: z.string().describe("Project UUID"),
  additionalDays: z.number().describe("Number of additional days granted"),
  appliedEndDate: z
    .string()
    .describe("Computed end date after this extension (YYYY-MM-DD)"),
  reason: z.string(),
  cost: z.nullable(
    z.number().describe("Extension cost in minor currency units"),
  ),
  billedAmount: z.nullable(
    z.number().describe("Amount billed in minor currency units"),
  ),
  grantedAt: z.string().describe("Date the extension was granted (YYYY-MM-DD)"),
  grantedBy: z.string().describe("User UUID who granted the extension"),
  createdAt: z.string().describe("ISO 8601 timestamp"),
  updatedAt: z.string().describe("ISO 8601 timestamp"),
});
