/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { moneySchema } from "./moneySchema.ts";
import { projectProfitSchema } from "./projectProfitSchema.ts";
import { z } from "zod/v4";

export const projectViewSchema = z.object({
  id: z.string().describe("Project UUID"),
  name: z.string(),
  description: z.nullable(z.string()),
  contactId: z.string().describe("Associated contact UUID"),
  currency: z.string().describe("ISO 4217 currency code"),
  status: z.enum(["Draft", "Active", "Closed", "Cancelled"]),
  startDate: z.string().describe("Start date (YYYY-MM-DD)"),
  originalPlannedEndDate: z
    .string()
    .describe("Original planned end date before any extensions (YYYY-MM-DD)"),
  plannedEndDate: z
    .string()
    .describe("Derived planned end date including all extensions (YYYY-MM-DD)"),
  createdBy: z.string().describe("User UUID who created this project"),
  responsibles: z
    .array(
      z.object({
        id: z.string(),
        userId: z.string(),
        userName: z.nullable(z.string()),
        role: z.enum(["Lead", "Member"]),
        assignedBy: z.string(),
        assignedAt: z.string(),
      }),
    )
    .describe("Project responsibles"),
  totals: z
    .object({
      get budget() {
        return moneySchema;
      },
      get expenses() {
        return moneySchema;
      },
      get profit() {
        return projectProfitSchema;
      },
    })
    .describe("Derived financial totals"),
  createdAt: z.string().describe("ISO 8601 timestamp"),
  updatedAt: z.string().describe("ISO 8601 timestamp"),
});
