/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const projectProfitSchema = z.object({
  amountMinor: z
    .number()
    .describe("Signed amount in minor currency units (may be negative)"),
  currency: z.string().describe("ISO 4217 currency code"),
});
