/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const projectKpisResponseSchema = z.object({
  total: z.object({
    count: z.int().min(0),
    current: z.int().min(0),
    previous: z.int().min(0),
  }),
  states: z.array(
    z.object({
      state: z.enum(["Draft", "Active", "Closed", "Cancelled"]),
      current: z.int().min(0),
      previous: z.int().min(0),
    }),
  ),
});
