/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const projectDocumentDownloadUrlSchema = z.object({
  url: z.url().describe("Presigned download URL"),
  expiresAt: z.iso.datetime().describe("ISO 8601 expiration timestamp"),
});
