/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const registerEventBodySchema = z.object({
  eventType: z
    .enum([
      "FirstContact",
      "MessageSent",
      "ResponseReceived",
      "MeetingCall",
      "ProposalSent",
      "ProposalWon",
      "ProposalRejected",
      "FollowUpPending",
      "Note",
      "Discarded",
      "Reopened",
    ])
    .describe("Type of event"),
  detail: z.optional(z.string().default("").describe("Event notes")),
  occurredAt: z
    .string()
    .describe("ISO 8601 timestamp of when the event occurred"),
});
