/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const setMappingBodySchema = z.object({
  mapping: z
    .object({})
    .catchall(z.string())
    .describe("Maps each Excel column header to a Contact field name."),
  templateId: z
    .uuid()
    .describe(
      "Optional template UUID to associate with this import (no FK in Fase 1).",
    )
    .nullish(),
});
