/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateProjectBodySchema = z.object({
  name: z.optional(z.string().min(1).describe("Project name")),
  description: z.string().describe("Project description").nullish(),
  contactId: z.optional(z.uuid().describe("UUID of the associated contact")),
  currency: z.optional(
    z.string().min(3).max(3).describe("ISO 4217 currency code"),
  ),
  startDate: z.optional(
    z.iso.date().describe("Project start date (YYYY-MM-DD)"),
  ),
  plannedEndDate: z.optional(
    z.iso.date().describe("Project planned end date (YYYY-MM-DD)"),
  ),
});
