/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateExtensionBodySchema = z.object({
  additionalDays: z.optional(
    z.int().gt(0).describe("Number of additional days"),
  ),
  reason: z.optional(z.string().min(1).describe("Reason for the extension")),
  cost: z
    .int()
    .min(0)
    .describe("Extension cost in minor currency units")
    .nullish(),
  billedAmount: z
    .int()
    .min(0)
    .describe("Amount billed in minor currency units")
    .nullish(),
  grantedAt: z.optional(
    z.iso.date().describe("Date the extension was granted (YYYY-MM-DD)"),
  ),
});
