/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateChannelBodySchema = z.object({
  channelType: z.optional(
    z
      .enum(["Phone", "Email", "WhatsApp", "Instagram", "Website", "Other"])
      .describe("Communication channel type"),
  ),
  value: z.optional(
    z.string().min(1).describe("Channel value (phone number, URL, handle)"),
  ),
  isPrimary: z.optional(
    z.boolean().describe("Whether this is the primary contact channel"),
  ),
});
