/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateContactBodySchema = z.object({
  name: z.optional(z.string().min(1).describe("Contact full name")),
  contactType: z.optional(
    z.enum(["Person", "Company"]).describe("Contact type"),
  ),
  sex: z
    .enum(["Male", "Female", "Other", "Unspecified"])
    .describe("Sex (only for Person contacts)")
    .nullish(),
  addressStreet: z.string().describe("Street name").nullish(),
  addressNumber: z.string().describe("Street number").nullish(),
  addressPostalCode: z.string().describe("Postal code").nullish(),
  addressCity: z.string().describe("City").nullish(),
  addressProvince: z.string().describe("Province or state").nullish(),
  addressCountry: z.string().describe("Country").nullish(),
  notes: z.string().describe("Free-form notes").nullish(),
  sourceChannel: z
    .enum(["Instagram", "WhatsApp", "Referral", "Email", "Other"])
    .describe("Acquisition channel")
    .nullish(),
  interestLevel: z
    .enum(["Cold", "Warm", "Hot"])
    .describe("Interest level")
    .nullish(),
});
