/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateAssignmentRoleBodySchema = z.object({
  role: z.enum(["Owner", "Collaborator"]).describe("New assignment role"),
});
