/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateExpenseBodySchema = z.object({
  concept: z.optional(z.string().min(1).describe("Expense description")),
  amountMinor: z.optional(
    z.int().min(0).describe("Amount in minor currency units"),
  ),
  incurredAt: z.optional(
    z.iso.date().describe("Date expense was incurred (YYYY-MM-DD)"),
  ),
});
