/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateBudgetItemBodySchema = z.object({
  concept: z.optional(z.string().min(1).describe("Budget item description")),
  amountMinor: z.optional(
    z.int().min(0).describe("Amount in minor currency units"),
  ),
});
