/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateUserBodySchema = z.object({
  name: z.optional(z.string().min(1).describe("New full name")),
  password: z.optional(z.string().min(8).describe("New password (>= 8 chars)")),
});
