/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateResponsibleRoleBodySchema = z.object({
  role: z.enum(["Lead", "Member"]).describe("New responsible role"),
});
