/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteContactsIdMutationResponse,
  DeleteContactsIdPathParams,
  DeleteContactsId401,
  DeleteContactsId404,
} from "../types/DeleteContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteContactsId } from "../clients/deleteContactsId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteContactsIdMutationKey = () =>
  [{ url: "/contacts/:id" }] as const;

export type DeleteContactsIdMutationKey = ReturnType<
  typeof deleteContactsIdMutationKey
>;

export function deleteContactsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteContactsIdMutationKey();
  return mutationOptions<
    DeleteContactsIdMutationResponse,
    ResponseErrorConfig<DeleteContactsId401 | DeleteContactsId404>,
    { id: DeleteContactsIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteContactsId(id, config);
    },
  });
}

/**
 * @summary Soft-delete a contact
 * {@link /contacts/:id}
 */
export function useDeleteContactsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteContactsIdMutationResponse,
      ResponseErrorConfig<DeleteContactsId401 | DeleteContactsId404>,
      { id: DeleteContactsIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteContactsIdMutationKey();

  const baseOptions = deleteContactsIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteContactsIdMutationResponse,
    ResponseErrorConfig<DeleteContactsId401 | DeleteContactsId404>,
    { id: DeleteContactsIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteContactsIdMutationResponse,
    ResponseErrorConfig<DeleteContactsId401 | DeleteContactsId404>,
    { id: DeleteContactsIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteContactsIdMutationResponse,
    ResponseErrorConfig<DeleteContactsId401 | DeleteContactsId404>,
    { id: DeleteContactsIdPathParams["id"] },
    TContext
  >;
}
