/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteProjectsIdDocumentsDocidMutationResponse,
  DeleteProjectsIdDocumentsDocidPathParams,
  DeleteProjectsIdDocumentsDocid401,
  DeleteProjectsIdDocumentsDocid404,
} from "../types/DeleteProjectsIdDocumentsDocid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteProjectsIdDocumentsDocid } from "../clients/deleteProjectsIdDocumentsDocid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteProjectsIdDocumentsDocidMutationKey = () =>
  [{ url: "/projects/:id/documents/:docId" }] as const;

export type DeleteProjectsIdDocumentsDocidMutationKey = ReturnType<
  typeof deleteProjectsIdDocumentsDocidMutationKey
>;

export function deleteProjectsIdDocumentsDocidMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteProjectsIdDocumentsDocidMutationKey();
  return mutationOptions<
    DeleteProjectsIdDocumentsDocidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdDocumentsDocid401 | DeleteProjectsIdDocumentsDocid404
    >,
    {
      id: DeleteProjectsIdDocumentsDocidPathParams["id"];
      docId: DeleteProjectsIdDocumentsDocidPathParams["docId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, docId }) => {
      return deleteProjectsIdDocumentsDocid(id, docId, config);
    },
  });
}

/**
 * @summary Delete a document from a project
 * {@link /projects/:id/documents/:docId}
 */
export function useDeleteProjectsIdDocumentsDocid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteProjectsIdDocumentsDocidMutationResponse,
      ResponseErrorConfig<
        DeleteProjectsIdDocumentsDocid401 | DeleteProjectsIdDocumentsDocid404
      >,
      {
        id: DeleteProjectsIdDocumentsDocidPathParams["id"];
        docId: DeleteProjectsIdDocumentsDocidPathParams["docId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteProjectsIdDocumentsDocidMutationKey();

  const baseOptions = deleteProjectsIdDocumentsDocidMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteProjectsIdDocumentsDocidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdDocumentsDocid401 | DeleteProjectsIdDocumentsDocid404
    >,
    {
      id: DeleteProjectsIdDocumentsDocidPathParams["id"];
      docId: DeleteProjectsIdDocumentsDocidPathParams["docId"];
    },
    TContext
  >;

  return useMutation<
    DeleteProjectsIdDocumentsDocidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdDocumentsDocid401 | DeleteProjectsIdDocumentsDocid404
    >,
    {
      id: DeleteProjectsIdDocumentsDocidPathParams["id"];
      docId: DeleteProjectsIdDocumentsDocidPathParams["docId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteProjectsIdDocumentsDocidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdDocumentsDocid401 | DeleteProjectsIdDocumentsDocid404
    >,
    {
      id: DeleteProjectsIdDocumentsDocidPathParams["id"];
      docId: DeleteProjectsIdDocumentsDocidPathParams["docId"];
    },
    TContext
  >;
}
