/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteProjectsIdExtensionsExtidMutationResponse,
  DeleteProjectsIdExtensionsExtidPathParams,
  DeleteProjectsIdExtensionsExtid401,
  DeleteProjectsIdExtensionsExtid404,
} from "../types/DeleteProjectsIdExtensionsExtid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteProjectsIdExtensionsExtid } from "../clients/deleteProjectsIdExtensionsExtid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteProjectsIdExtensionsExtidMutationKey = () =>
  [{ url: "/projects/:id/extensions/:extId" }] as const;

export type DeleteProjectsIdExtensionsExtidMutationKey = ReturnType<
  typeof deleteProjectsIdExtensionsExtidMutationKey
>;

export function deleteProjectsIdExtensionsExtidMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteProjectsIdExtensionsExtidMutationKey();
  return mutationOptions<
    DeleteProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdExtensionsExtid401 | DeleteProjectsIdExtensionsExtid404
    >,
    {
      id: DeleteProjectsIdExtensionsExtidPathParams["id"];
      extId: DeleteProjectsIdExtensionsExtidPathParams["extId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, extId }) => {
      return deleteProjectsIdExtensionsExtid(id, extId, config);
    },
  });
}

/**
 * @summary Remove an extension from a project
 * {@link /projects/:id/extensions/:extId}
 */
export function useDeleteProjectsIdExtensionsExtid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteProjectsIdExtensionsExtidMutationResponse,
      ResponseErrorConfig<
        DeleteProjectsIdExtensionsExtid401 | DeleteProjectsIdExtensionsExtid404
      >,
      {
        id: DeleteProjectsIdExtensionsExtidPathParams["id"];
        extId: DeleteProjectsIdExtensionsExtidPathParams["extId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteProjectsIdExtensionsExtidMutationKey();

  const baseOptions = deleteProjectsIdExtensionsExtidMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdExtensionsExtid401 | DeleteProjectsIdExtensionsExtid404
    >,
    {
      id: DeleteProjectsIdExtensionsExtidPathParams["id"];
      extId: DeleteProjectsIdExtensionsExtidPathParams["extId"];
    },
    TContext
  >;

  return useMutation<
    DeleteProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdExtensionsExtid401 | DeleteProjectsIdExtensionsExtid404
    >,
    {
      id: DeleteProjectsIdExtensionsExtidPathParams["id"];
      extId: DeleteProjectsIdExtensionsExtidPathParams["extId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      DeleteProjectsIdExtensionsExtid401 | DeleteProjectsIdExtensionsExtid404
    >,
    {
      id: DeleteProjectsIdExtensionsExtidPathParams["id"];
      extId: DeleteProjectsIdExtensionsExtidPathParams["extId"];
    },
    TContext
  >;
}
