/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteProjectsIdResponsiblesUseridMutationResponse,
  DeleteProjectsIdResponsiblesUseridPathParams,
  DeleteProjectsIdResponsiblesUserid401,
  DeleteProjectsIdResponsiblesUserid404,
  DeleteProjectsIdResponsiblesUserid422,
} from "../types/DeleteProjectsIdResponsiblesUserid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteProjectsIdResponsiblesUserid } from "../clients/deleteProjectsIdResponsiblesUserid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteProjectsIdResponsiblesUseridMutationKey = () =>
  [{ url: "/projects/:id/responsibles/:userId" }] as const;

export type DeleteProjectsIdResponsiblesUseridMutationKey = ReturnType<
  typeof deleteProjectsIdResponsiblesUseridMutationKey
>;

export function deleteProjectsIdResponsiblesUseridMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteProjectsIdResponsiblesUseridMutationKey();
  return mutationOptions<
    DeleteProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdResponsiblesUserid401
      | DeleteProjectsIdResponsiblesUserid404
      | DeleteProjectsIdResponsiblesUserid422
    >,
    {
      id: DeleteProjectsIdResponsiblesUseridPathParams["id"];
      userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, userId }) => {
      return deleteProjectsIdResponsiblesUserid(id, userId, config);
    },
  });
}

/**
 * @summary Remove a responsible from a project
 * {@link /projects/:id/responsibles/:userId}
 */
export function useDeleteProjectsIdResponsiblesUserid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteProjectsIdResponsiblesUseridMutationResponse,
      ResponseErrorConfig<
        | DeleteProjectsIdResponsiblesUserid401
        | DeleteProjectsIdResponsiblesUserid404
        | DeleteProjectsIdResponsiblesUserid422
      >,
      {
        id: DeleteProjectsIdResponsiblesUseridPathParams["id"];
        userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteProjectsIdResponsiblesUseridMutationKey();

  const baseOptions = deleteProjectsIdResponsiblesUseridMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdResponsiblesUserid401
      | DeleteProjectsIdResponsiblesUserid404
      | DeleteProjectsIdResponsiblesUserid422
    >,
    {
      id: DeleteProjectsIdResponsiblesUseridPathParams["id"];
      userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"];
    },
    TContext
  >;

  return useMutation<
    DeleteProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdResponsiblesUserid401
      | DeleteProjectsIdResponsiblesUserid404
      | DeleteProjectsIdResponsiblesUserid422
    >,
    {
      id: DeleteProjectsIdResponsiblesUseridPathParams["id"];
      userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdResponsiblesUserid401
      | DeleteProjectsIdResponsiblesUserid404
      | DeleteProjectsIdResponsiblesUserid422
    >,
    {
      id: DeleteProjectsIdResponsiblesUseridPathParams["id"];
      userId: DeleteProjectsIdResponsiblesUseridPathParams["userId"];
    },
    TContext
  >;
}
