/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteProjectsIdExpensesExpenseidMutationResponse,
  DeleteProjectsIdExpensesExpenseidPathParams,
  DeleteProjectsIdExpensesExpenseid401,
  DeleteProjectsIdExpensesExpenseid404,
} from "../types/DeleteProjectsIdExpensesExpenseid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteProjectsIdExpensesExpenseid } from "../clients/deleteProjectsIdExpensesExpenseid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteProjectsIdExpensesExpenseidMutationKey = () =>
  [{ url: "/projects/:id/expenses/:expenseId" }] as const;

export type DeleteProjectsIdExpensesExpenseidMutationKey = ReturnType<
  typeof deleteProjectsIdExpensesExpenseidMutationKey
>;

export function deleteProjectsIdExpensesExpenseidMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteProjectsIdExpensesExpenseidMutationKey();
  return mutationOptions<
    DeleteProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdExpensesExpenseid401
      | DeleteProjectsIdExpensesExpenseid404
    >,
    {
      id: DeleteProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: DeleteProjectsIdExpensesExpenseidPathParams["expenseId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, expenseId }) => {
      return deleteProjectsIdExpensesExpenseid(id, expenseId, config);
    },
  });
}

/**
 * @summary Remove an expense from a project
 * {@link /projects/:id/expenses/:expenseId}
 */
export function useDeleteProjectsIdExpensesExpenseid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteProjectsIdExpensesExpenseidMutationResponse,
      ResponseErrorConfig<
        | DeleteProjectsIdExpensesExpenseid401
        | DeleteProjectsIdExpensesExpenseid404
      >,
      {
        id: DeleteProjectsIdExpensesExpenseidPathParams["id"];
        expenseId: DeleteProjectsIdExpensesExpenseidPathParams["expenseId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteProjectsIdExpensesExpenseidMutationKey();

  const baseOptions = deleteProjectsIdExpensesExpenseidMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdExpensesExpenseid401
      | DeleteProjectsIdExpensesExpenseid404
    >,
    {
      id: DeleteProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: DeleteProjectsIdExpensesExpenseidPathParams["expenseId"];
    },
    TContext
  >;

  return useMutation<
    DeleteProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdExpensesExpenseid401
      | DeleteProjectsIdExpensesExpenseid404
    >,
    {
      id: DeleteProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: DeleteProjectsIdExpensesExpenseidPathParams["expenseId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      | DeleteProjectsIdExpensesExpenseid401
      | DeleteProjectsIdExpensesExpenseid404
    >,
    {
      id: DeleteProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: DeleteProjectsIdExpensesExpenseidPathParams["expenseId"];
    },
    TContext
  >;
}
