/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteContactsIdAssignmentsUseridMutationResponse,
  DeleteContactsIdAssignmentsUseridPathParams,
  DeleteContactsIdAssignmentsUserid401,
  DeleteContactsIdAssignmentsUserid404,
} from "../types/DeleteContactsIdAssignmentsUserid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteContactsIdAssignmentsUserid } from "../clients/deleteContactsIdAssignmentsUserid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteContactsIdAssignmentsUseridMutationKey = () =>
  [{ url: "/contacts/:id/assignments/:userId" }] as const;

export type DeleteContactsIdAssignmentsUseridMutationKey = ReturnType<
  typeof deleteContactsIdAssignmentsUseridMutationKey
>;

export function deleteContactsIdAssignmentsUseridMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteContactsIdAssignmentsUseridMutationKey();
  return mutationOptions<
    DeleteContactsIdAssignmentsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteContactsIdAssignmentsUserid401
      | DeleteContactsIdAssignmentsUserid404
    >,
    {
      id: DeleteContactsIdAssignmentsUseridPathParams["id"];
      userId: DeleteContactsIdAssignmentsUseridPathParams["userId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, userId }) => {
      return deleteContactsIdAssignmentsUserid(id, userId, config);
    },
  });
}

/**
 * @summary Remove an assignment from a contact
 * {@link /contacts/:id/assignments/:userId}
 */
export function useDeleteContactsIdAssignmentsUserid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteContactsIdAssignmentsUseridMutationResponse,
      ResponseErrorConfig<
        | DeleteContactsIdAssignmentsUserid401
        | DeleteContactsIdAssignmentsUserid404
      >,
      {
        id: DeleteContactsIdAssignmentsUseridPathParams["id"];
        userId: DeleteContactsIdAssignmentsUseridPathParams["userId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteContactsIdAssignmentsUseridMutationKey();

  const baseOptions = deleteContactsIdAssignmentsUseridMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteContactsIdAssignmentsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteContactsIdAssignmentsUserid401
      | DeleteContactsIdAssignmentsUserid404
    >,
    {
      id: DeleteContactsIdAssignmentsUseridPathParams["id"];
      userId: DeleteContactsIdAssignmentsUseridPathParams["userId"];
    },
    TContext
  >;

  return useMutation<
    DeleteContactsIdAssignmentsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteContactsIdAssignmentsUserid401
      | DeleteContactsIdAssignmentsUserid404
    >,
    {
      id: DeleteContactsIdAssignmentsUseridPathParams["id"];
      userId: DeleteContactsIdAssignmentsUseridPathParams["userId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteContactsIdAssignmentsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteContactsIdAssignmentsUserid401
      | DeleteContactsIdAssignmentsUserid404
    >,
    {
      id: DeleteContactsIdAssignmentsUseridPathParams["id"];
      userId: DeleteContactsIdAssignmentsUseridPathParams["userId"];
    },
    TContext
  >;
}
