/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteUsersIdMutationResponse,
  DeleteUsersIdPathParams,
  DeleteUsersId401,
  DeleteUsersId404,
} from "../types/DeleteUsersId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteUsersId } from "../clients/deleteUsersId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteUsersIdMutationKey = () => [{ url: "/users/:id" }] as const;

export type DeleteUsersIdMutationKey = ReturnType<
  typeof deleteUsersIdMutationKey
>;

export function deleteUsersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteUsersIdMutationKey();
  return mutationOptions<
    DeleteUsersIdMutationResponse,
    ResponseErrorConfig<DeleteUsersId401 | DeleteUsersId404>,
    { id: DeleteUsersIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteUsersId(id, config);
    },
  });
}

/**
 * @summary Soft-delete a user
 * {@link /users/:id}
 */
export function useDeleteUsersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteUsersIdMutationResponse,
      ResponseErrorConfig<DeleteUsersId401 | DeleteUsersId404>,
      { id: DeleteUsersIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteUsersIdMutationKey();

  const baseOptions = deleteUsersIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteUsersIdMutationResponse,
    ResponseErrorConfig<DeleteUsersId401 | DeleteUsersId404>,
    { id: DeleteUsersIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteUsersIdMutationResponse,
    ResponseErrorConfig<DeleteUsersId401 | DeleteUsersId404>,
    { id: DeleteUsersIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteUsersIdMutationResponse,
    ResponseErrorConfig<DeleteUsersId401 | DeleteUsersId404>,
    { id: DeleteUsersIdPathParams["id"] },
    TContext
  >;
}
