/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetAnalysisTemplatesQueryResponse,
  GetAnalysisTemplates401,
} from "../types/GetAnalysisTemplates.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getAnalysisTemplates } from "../clients/getAnalysisTemplates.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAnalysisTemplatesQueryKey = () =>
  [{ url: "/analysis-templates" }] as const;

export type GetAnalysisTemplatesQueryKey = ReturnType<
  typeof getAnalysisTemplatesQueryKey
>;

export function getAnalysisTemplatesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAnalysisTemplatesQueryKey();
  return queryOptions<
    GetAnalysisTemplatesQueryResponse,
    ResponseErrorConfig<GetAnalysisTemplates401>,
    GetAnalysisTemplatesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getAnalysisTemplates({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List all analysis templates
 * {@link /analysis-templates}
 */
export function useGetAnalysisTemplates<
  TData = GetAnalysisTemplatesQueryResponse,
  TQueryData = GetAnalysisTemplatesQueryResponse,
  TQueryKey extends QueryKey = GetAnalysisTemplatesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAnalysisTemplatesQueryResponse,
        ResponseErrorConfig<GetAnalysisTemplates401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getAnalysisTemplatesQueryKey();

  const query = useQuery(
    {
      ...getAnalysisTemplatesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetAnalysisTemplates401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
