/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
  GetProjectsIdDocumentsDocidDownloadUrlPathParams,
  GetProjectsIdDocumentsDocidDownloadUrl401,
  GetProjectsIdDocumentsDocidDownloadUrl404,
} from "../types/GetProjectsIdDocumentsDocidDownloadUrl.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdDocumentsDocidDownloadUrl } from "../clients/getProjectsIdDocumentsDocidDownloadUrl.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProjectsIdDocumentsDocidDownloadUrlQueryKey = (
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"] | undefined,
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"] | undefined,
) =>
  [
    {
      url: "/projects/:id/documents/:docId/download-url",
      params: { id: id, docId: docId },
    },
  ] as const;

export type GetProjectsIdDocumentsDocidDownloadUrlQueryKey = ReturnType<
  typeof getProjectsIdDocumentsDocidDownloadUrlQueryKey
>;

export function getProjectsIdDocumentsDocidDownloadUrlQueryOptions(
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"] | undefined,
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdDocumentsDocidDownloadUrlQueryKey(id, docId);
  return queryOptions<
    GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
    ResponseErrorConfig<
      | GetProjectsIdDocumentsDocidDownloadUrl401
      | GetProjectsIdDocumentsDocidDownloadUrl404
    >,
    GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
    typeof queryKey
  >({
    enabled: !!(id && docId),
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdDocumentsDocidDownloadUrl(id!, docId!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get a presigned download URL for a document
 * {@link /projects/:id/documents/:docId/download-url}
 */
export function useGetProjectsIdDocumentsDocidDownloadUrl<
  TData = GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
  TQueryData = GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdDocumentsDocidDownloadUrlQueryKey,
>(
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"] | undefined,
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
        ResponseErrorConfig<
          | GetProjectsIdDocumentsDocidDownloadUrl401
          | GetProjectsIdDocumentsDocidDownloadUrl404
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProjectsIdDocumentsDocidDownloadUrlQueryKey(id, docId);

  const query = useQuery(
    {
      ...getProjectsIdDocumentsDocidDownloadUrlQueryOptions(id, docId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetProjectsIdDocumentsDocidDownloadUrl401
      | GetProjectsIdDocumentsDocidDownloadUrl404
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
