/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsKpisQueryResponse,
  GetProjectsKpis401,
} from "../types/GetProjectsKpis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getProjectsKpis } from "../clients/getProjectsKpis.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProjectsKpisQueryKey = () =>
  [{ url: "/projects/kpis" }] as const;

export type GetProjectsKpisQueryKey = ReturnType<
  typeof getProjectsKpisQueryKey
>;

export function getProjectsKpisQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsKpisQueryKey();
  return queryOptions<
    GetProjectsKpisQueryResponse,
    ResponseErrorConfig<GetProjectsKpis401>,
    GetProjectsKpisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsKpis({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get status KPIs for projects
 * {@link /projects/kpis}
 */
export function useGetProjectsKpis<
  TData = GetProjectsKpisQueryResponse,
  TQueryData = GetProjectsKpisQueryResponse,
  TQueryKey extends QueryKey = GetProjectsKpisQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProjectsKpisQueryResponse,
        ResponseErrorConfig<GetProjectsKpis401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getProjectsKpisQueryKey();

  const query = useQuery(
    {
      ...getProjectsKpisQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetProjectsKpis401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
