/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsQueryResponse,
  GetContactsQueryParams,
  GetContacts401,
} from "../types/GetContacts.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getContacts } from "../clients/getContacts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getContactsQueryKey = (params?: GetContactsQueryParams) =>
  [{ url: "/contacts" }, ...(params ? [params] : [])] as const;

export type GetContactsQueryKey = ReturnType<typeof getContactsQueryKey>;

export function getContactsQueryOptions(
  params?: GetContactsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsQueryKey(params);
  return queryOptions<
    GetContactsQueryResponse,
    ResponseErrorConfig<GetContacts401>,
    GetContactsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getContacts(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List contacts
 * {@link /contacts}
 */
export function useGetContacts<
  TData = GetContactsQueryResponse,
  TQueryData = GetContactsQueryResponse,
  TQueryKey extends QueryKey = GetContactsQueryKey,
>(
  params?: GetContactsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetContactsQueryResponse,
        ResponseErrorConfig<GetContacts401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getContactsQueryKey(params);

  const query = useQuery(
    {
      ...getContactsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetContacts401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
