/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetUsersQueryResponse,
  GetUsersQueryParams,
  GetUsers401,
} from "../types/GetUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getUsers } from "../clients/getUsers.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUsersSuspenseQueryKey = (params?: GetUsersQueryParams) =>
  [{ url: "/users" }, ...(params ? [params] : [])] as const;

export type GetUsersSuspenseQueryKey = ReturnType<
  typeof getUsersSuspenseQueryKey
>;

export function getUsersSuspenseQueryOptions(
  params?: GetUsersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getUsersSuspenseQueryKey(params);
  return queryOptions<
    GetUsersQueryResponse,
    ResponseErrorConfig<GetUsers401>,
    GetUsersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getUsers(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary List users
 * {@link /users}
 */
export function useGetUsersSuspense<
  TData = GetUsersQueryResponse,
  TQueryKey extends QueryKey = GetUsersSuspenseQueryKey,
>(
  params?: GetUsersQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetUsersQueryResponse,
        ResponseErrorConfig<GetUsers401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getUsersSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getUsersSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUsers401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
