/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsIdEventsQueryResponse,
  GetContactsIdEventsPathParams,
  GetContactsIdEvents401,
  GetContactsIdEvents404,
} from "../types/GetContactsIdEvents.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getContactsIdEvents } from "../clients/getContactsIdEvents.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getContactsIdEventsQueryKey = (
  id: GetContactsIdEventsPathParams["id"] | undefined,
) => [{ url: "/contacts/:id/events", params: { id: id } }] as const;

export type GetContactsIdEventsQueryKey = ReturnType<
  typeof getContactsIdEventsQueryKey
>;

export function getContactsIdEventsQueryOptions(
  id: GetContactsIdEventsPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsIdEventsQueryKey(id);
  return queryOptions<
    GetContactsIdEventsQueryResponse,
    ResponseErrorConfig<GetContactsIdEvents401 | GetContactsIdEvents404>,
    GetContactsIdEventsQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getContactsIdEvents(id!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List events for a contact
 * {@link /contacts/:id/events}
 */
export function useGetContactsIdEvents<
  TData = GetContactsIdEventsQueryResponse,
  TQueryData = GetContactsIdEventsQueryResponse,
  TQueryKey extends QueryKey = GetContactsIdEventsQueryKey,
>(
  id: GetContactsIdEventsPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetContactsIdEventsQueryResponse,
        ResponseErrorConfig<GetContactsIdEvents401 | GetContactsIdEvents404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getContactsIdEventsQueryKey(id);

  const query = useQuery(
    {
      ...getContactsIdEventsQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetContactsIdEvents401 | GetContactsIdEvents404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
