/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdExtensionsQueryResponse,
  GetProjectsIdExtensionsPathParams,
  GetProjectsIdExtensionsQueryParams,
  GetProjectsIdExtensions401,
  GetProjectsIdExtensions404,
} from "../types/GetProjectsIdExtensions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdExtensions } from "../clients/getProjectsIdExtensions.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProjectsIdExtensionsSuspenseQueryKey = (
  id: GetProjectsIdExtensionsPathParams["id"] | undefined,
  params?: GetProjectsIdExtensionsQueryParams,
) =>
  [
    { url: "/projects/:id/extensions", params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type GetProjectsIdExtensionsSuspenseQueryKey = ReturnType<
  typeof getProjectsIdExtensionsSuspenseQueryKey
>;

export function getProjectsIdExtensionsSuspenseQueryOptions(
  id: GetProjectsIdExtensionsPathParams["id"] | undefined,
  params?: GetProjectsIdExtensionsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdExtensionsSuspenseQueryKey(id, params);
  return queryOptions<
    GetProjectsIdExtensionsQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdExtensions401 | GetProjectsIdExtensions404
    >,
    GetProjectsIdExtensionsQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdExtensions(id!, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List extensions for a project
 * {@link /projects/:id/extensions}
 */
export function useGetProjectsIdExtensionsSuspense<
  TData = GetProjectsIdExtensionsQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdExtensionsSuspenseQueryKey,
>(
  id: GetProjectsIdExtensionsPathParams["id"] | undefined,
  params?: GetProjectsIdExtensionsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProjectsIdExtensionsQueryResponse,
        ResponseErrorConfig<
          GetProjectsIdExtensions401 | GetProjectsIdExtensions404
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProjectsIdExtensionsSuspenseQueryKey(id, params);

  const query = useSuspenseQuery(
    {
      ...getProjectsIdExtensionsSuspenseQueryOptions(id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetProjectsIdExtensions401 | GetProjectsIdExtensions404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
