/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdExpensesQueryResponse,
  GetProjectsIdExpensesPathParams,
  GetProjectsIdExpensesQueryParams,
  GetProjectsIdExpenses401,
  GetProjectsIdExpenses404,
} from "../types/GetProjectsIdExpenses.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdExpenses } from "../clients/getProjectsIdExpenses.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProjectsIdExpensesSuspenseQueryKey = (
  id: GetProjectsIdExpensesPathParams["id"] | undefined,
  params?: GetProjectsIdExpensesQueryParams,
) =>
  [
    { url: "/projects/:id/expenses", params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type GetProjectsIdExpensesSuspenseQueryKey = ReturnType<
  typeof getProjectsIdExpensesSuspenseQueryKey
>;

export function getProjectsIdExpensesSuspenseQueryOptions(
  id: GetProjectsIdExpensesPathParams["id"] | undefined,
  params?: GetProjectsIdExpensesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdExpensesSuspenseQueryKey(id, params);
  return queryOptions<
    GetProjectsIdExpensesQueryResponse,
    ResponseErrorConfig<GetProjectsIdExpenses401 | GetProjectsIdExpenses404>,
    GetProjectsIdExpensesQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdExpenses(id!, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List expenses for a project
 * {@link /projects/:id/expenses}
 */
export function useGetProjectsIdExpensesSuspense<
  TData = GetProjectsIdExpensesQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdExpensesSuspenseQueryKey,
>(
  id: GetProjectsIdExpensesPathParams["id"] | undefined,
  params?: GetProjectsIdExpensesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProjectsIdExpensesQueryResponse,
        ResponseErrorConfig<
          GetProjectsIdExpenses401 | GetProjectsIdExpenses404
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProjectsIdExpensesSuspenseQueryKey(id, params);

  const query = useSuspenseQuery(
    {
      ...getProjectsIdExpensesSuspenseQueryOptions(id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetProjectsIdExpenses401 | GetProjectsIdExpenses404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
