/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsIdQueryResponse,
  GetContactsIdPathParams,
  GetContactsId401,
  GetContactsId404,
} from "../types/GetContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getContactsId } from "../clients/getContactsId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getContactsIdQueryKey = (
  id: GetContactsIdPathParams["id"] | undefined,
) => [{ url: "/contacts/:id" }] as const;

export type GetContactsIdQueryKey = ReturnType<typeof getContactsIdQueryKey>;

export function getContactsIdQueryOptions(
  id: GetContactsIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsIdQueryKey(id);
  return queryOptions<
    GetContactsIdQueryResponse,
    ResponseErrorConfig<GetContactsId401 | GetContactsId404>,
    GetContactsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getContactsId(id!, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get a contact by id
 * {@link /contacts/:id}
 */
export function useGetContactsId<
  TData = GetContactsIdQueryResponse,
  TQueryData = GetContactsIdQueryResponse,
  TQueryKey extends QueryKey = GetContactsIdQueryKey,
>(
  id: GetContactsIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetContactsIdQueryResponse,
        ResponseErrorConfig<GetContactsId401 | GetContactsId404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getContactsIdQueryKey(id);

  const query = useQuery(
    {
      ...getContactsIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetContactsId401 | GetContactsId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
