/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdQueryResponse,
  GetProjectsIdPathParams,
  GetProjectsId401,
  GetProjectsId404,
} from "../types/GetProjectsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getProjectsId } from "../clients/getProjectsId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProjectsIdQueryKey = (
  id: GetProjectsIdPathParams["id"] | undefined,
) => [{ url: "/projects/:id", params: { id: id } }] as const;

export type GetProjectsIdQueryKey = ReturnType<typeof getProjectsIdQueryKey>;

export function getProjectsIdQueryOptions(
  id: GetProjectsIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdQueryKey(id);
  return queryOptions<
    GetProjectsIdQueryResponse,
    ResponseErrorConfig<GetProjectsId401 | GetProjectsId404>,
    GetProjectsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsId(id!, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get a project by id
 * {@link /projects/:id}
 */
export function useGetProjectsId<
  TData = GetProjectsIdQueryResponse,
  TQueryData = GetProjectsIdQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdQueryKey,
>(
  id: GetProjectsIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProjectsIdQueryResponse,
        ResponseErrorConfig<GetProjectsId401 | GetProjectsId404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getProjectsIdQueryKey(id);

  const query = useQuery(
    {
      ...getProjectsIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetProjectsId401 | GetProjectsId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
