/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetUsersQueryResponse, GetUsers401 } from "../types/GetUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getUsers } from "../clients/getUsers.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUsersSuspenseQueryKey = () => [{ url: "/users" }] as const;

export type GetUsersSuspenseQueryKey = ReturnType<
  typeof getUsersSuspenseQueryKey
>;

export function getUsersSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getUsersSuspenseQueryKey();
  return queryOptions<
    GetUsersQueryResponse,
    ResponseErrorConfig<GetUsers401>,
    GetUsersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getUsers({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary List users
 * {@link /users}
 */
export function useGetUsersSuspense<
  TData = GetUsersQueryResponse,
  TQueryKey extends QueryKey = GetUsersSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetUsersQueryResponse,
        ResponseErrorConfig<GetUsers401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getUsersSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getUsersSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUsers401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
