/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetEnrichmentsQueryResponse,
  GetEnrichmentsQueryParams,
  GetEnrichments400,
  GetEnrichments401,
} from "../types/GetEnrichments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getEnrichments } from "../clients/getEnrichments.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getEnrichmentsQueryKey = (params: GetEnrichmentsQueryParams) =>
  [{ url: "/enrichments" }, ...(params ? [params] : [])] as const;

export type GetEnrichmentsQueryKey = ReturnType<typeof getEnrichmentsQueryKey>;

export function getEnrichmentsQueryOptions(
  params: GetEnrichmentsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getEnrichmentsQueryKey(params);
  return queryOptions<
    GetEnrichmentsQueryResponse,
    ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>,
    GetEnrichmentsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getEnrichments(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List enrichment insights for a contact
 * {@link /enrichments}
 */
export function useGetEnrichments<
  TData = GetEnrichmentsQueryResponse,
  TQueryData = GetEnrichmentsQueryResponse,
  TQueryKey extends QueryKey = GetEnrichmentsQueryKey,
>(
  params: GetEnrichmentsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetEnrichmentsQueryResponse,
        ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getEnrichmentsQueryKey(params);

  const query = useQuery(
    {
      ...getEnrichmentsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
