/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsKpisQueryResponse,
  GetContactsKpis401,
} from "../types/GetContactsKpis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getContactsKpis } from "../clients/getContactsKpis.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getContactsKpisQueryKey = () =>
  [{ url: "/contacts/kpis" }] as const;

export type GetContactsKpisQueryKey = ReturnType<
  typeof getContactsKpisQueryKey
>;

export function getContactsKpisQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsKpisQueryKey();
  return queryOptions<
    GetContactsKpisQueryResponse,
    ResponseErrorConfig<GetContactsKpis401>,
    GetContactsKpisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getContactsKpis({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get pipeline-flow KPIs for contacts
 * {@link /contacts/kpis}
 */
export function useGetContactsKpis<
  TData = GetContactsKpisQueryResponse,
  TQueryData = GetContactsKpisQueryResponse,
  TQueryKey extends QueryKey = GetContactsKpisQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetContactsKpisQueryResponse,
        ResponseErrorConfig<GetContactsKpis401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getContactsKpisQueryKey();

  const query = useQuery(
    {
      ...getContactsKpisQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetContactsKpis401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
