/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
  GetProjectsIdDocumentsDocidDownloadUrlPathParams,
  GetProjectsIdDocumentsDocidDownloadUrl401,
  GetProjectsIdDocumentsDocidDownloadUrl404,
} from "../types/GetProjectsIdDocumentsDocidDownloadUrl.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdDocumentsDocidDownloadUrl } from "../clients/getProjectsIdDocumentsDocidDownloadUrl.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProjectsIdDocumentsDocidDownloadUrlSuspenseQueryKey = (
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"] | undefined,
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"] | undefined,
) =>
  [
    {
      url: "/projects/:id/documents/:docId/download-url",
      params: { id: id, docId: docId },
    },
  ] as const;

export type GetProjectsIdDocumentsDocidDownloadUrlSuspenseQueryKey = ReturnType<
  typeof getProjectsIdDocumentsDocidDownloadUrlSuspenseQueryKey
>;

export function getProjectsIdDocumentsDocidDownloadUrlSuspenseQueryOptions(
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"] | undefined,
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdDocumentsDocidDownloadUrlSuspenseQueryKey(
    id,
    docId,
  );
  return queryOptions<
    GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
    ResponseErrorConfig<
      | GetProjectsIdDocumentsDocidDownloadUrl401
      | GetProjectsIdDocumentsDocidDownloadUrl404
    >,
    GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
    typeof queryKey
  >({
    enabled: !!(id && docId),
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdDocumentsDocidDownloadUrl(id!, docId!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get a presigned download URL for a document
 * {@link /projects/:id/documents/:docId/download-url}
 */
export function useGetProjectsIdDocumentsDocidDownloadUrlSuspense<
  TData = GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
  TQueryKey extends QueryKey =
    GetProjectsIdDocumentsDocidDownloadUrlSuspenseQueryKey,
>(
  id: GetProjectsIdDocumentsDocidDownloadUrlPathParams["id"] | undefined,
  docId: GetProjectsIdDocumentsDocidDownloadUrlPathParams["docId"] | undefined,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProjectsIdDocumentsDocidDownloadUrlQueryResponse,
        ResponseErrorConfig<
          | GetProjectsIdDocumentsDocidDownloadUrl401
          | GetProjectsIdDocumentsDocidDownloadUrl404
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProjectsIdDocumentsDocidDownloadUrlSuspenseQueryKey(id, docId);

  const query = useSuspenseQuery(
    {
      ...getProjectsIdDocumentsDocidDownloadUrlSuspenseQueryOptions(
        id,
        docId,
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetProjectsIdDocumentsDocidDownloadUrl401
      | GetProjectsIdDocumentsDocidDownloadUrl404
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
