/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsIdStateChangesQueryResponse,
  GetContactsIdStateChangesPathParams,
  GetContactsIdStateChanges401,
  GetContactsIdStateChanges404,
} from "../types/GetContactsIdStateChanges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getContactsIdStateChanges } from "../clients/getContactsIdStateChanges.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getContactsIdStateChangesSuspenseQueryKey = (
  id: GetContactsIdStateChangesPathParams["id"] | undefined,
) => [{ url: "/contacts/:id/state-changes", params: { id: id } }] as const;

export type GetContactsIdStateChangesSuspenseQueryKey = ReturnType<
  typeof getContactsIdStateChangesSuspenseQueryKey
>;

export function getContactsIdStateChangesSuspenseQueryOptions(
  id: GetContactsIdStateChangesPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsIdStateChangesSuspenseQueryKey(id);
  return queryOptions<
    GetContactsIdStateChangesQueryResponse,
    ResponseErrorConfig<
      GetContactsIdStateChanges401 | GetContactsIdStateChanges404
    >,
    GetContactsIdStateChangesQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getContactsIdStateChanges(id!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List state changes for a contact
 * {@link /contacts/:id/state-changes}
 */
export function useGetContactsIdStateChangesSuspense<
  TData = GetContactsIdStateChangesQueryResponse,
  TQueryKey extends QueryKey = GetContactsIdStateChangesSuspenseQueryKey,
>(
  id: GetContactsIdStateChangesPathParams["id"] | undefined,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetContactsIdStateChangesQueryResponse,
        ResponseErrorConfig<
          GetContactsIdStateChanges401 | GetContactsIdStateChanges404
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getContactsIdStateChangesSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getContactsIdStateChangesSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      GetContactsIdStateChanges401 | GetContactsIdStateChanges404
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
