/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetImportsQueryResponse,
  GetImportsQueryParams,
  GetImports401,
} from "../types/GetImports.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getImports } from "../clients/getImports.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getImportsQueryKey = (params?: GetImportsQueryParams) =>
  [{ url: "/imports" }, ...(params ? [params] : [])] as const;

export type GetImportsQueryKey = ReturnType<typeof getImportsQueryKey>;

export function getImportsQueryOptions(
  params?: GetImportsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getImportsQueryKey(params);
  return queryOptions<
    GetImportsQueryResponse,
    ResponseErrorConfig<GetImports401>,
    GetImportsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getImports(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary List imports (paginated)
 * {@link /imports}
 */
export function useGetImports<
  TData = GetImportsQueryResponse,
  TQueryData = GetImportsQueryResponse,
  TQueryKey extends QueryKey = GetImportsQueryKey,
>(
  params?: GetImportsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetImportsQueryResponse,
        ResponseErrorConfig<GetImports401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getImportsQueryKey(params);

  const query = useQuery(
    {
      ...getImportsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetImports401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
