/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsQueryResponse,
  GetContactsQueryParams,
  GetContacts401,
} from "../types/GetContacts.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getContacts } from "../clients/getContacts.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getContactsSuspenseQueryKey = (params?: GetContactsQueryParams) =>
  [{ url: "/contacts" }, ...(params ? [params] : [])] as const;

export type GetContactsSuspenseQueryKey = ReturnType<
  typeof getContactsSuspenseQueryKey
>;

export function getContactsSuspenseQueryOptions(
  params?: GetContactsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsSuspenseQueryKey(params);
  return queryOptions<
    GetContactsQueryResponse,
    ResponseErrorConfig<GetContacts401>,
    GetContactsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getContacts(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List contacts
 * {@link /contacts}
 */
export function useGetContactsSuspense<
  TData = GetContactsQueryResponse,
  TQueryKey extends QueryKey = GetContactsSuspenseQueryKey,
>(
  params?: GetContactsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetContactsQueryResponse,
        ResponseErrorConfig<GetContacts401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getContactsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getContactsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetContacts401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
