/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsKpisQueryResponse,
  GetProjectsKpis401,
} from "../types/GetProjectsKpis.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getProjectsKpis } from "../clients/getProjectsKpis.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProjectsKpisSuspenseQueryKey = () =>
  [{ url: "/projects/kpis" }] as const;

export type GetProjectsKpisSuspenseQueryKey = ReturnType<
  typeof getProjectsKpisSuspenseQueryKey
>;

export function getProjectsKpisSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsKpisSuspenseQueryKey();
  return queryOptions<
    GetProjectsKpisQueryResponse,
    ResponseErrorConfig<GetProjectsKpis401>,
    GetProjectsKpisQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsKpis({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get status KPIs for projects
 * {@link /projects/kpis}
 */
export function useGetProjectsKpisSuspense<
  TData = GetProjectsKpisQueryResponse,
  TQueryKey extends QueryKey = GetProjectsKpisSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProjectsKpisQueryResponse,
        ResponseErrorConfig<GetProjectsKpis401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getProjectsKpisSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getProjectsKpisSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetProjectsKpis401>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
