/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdBudgetItemsQueryResponse,
  GetProjectsIdBudgetItemsPathParams,
  GetProjectsIdBudgetItemsQueryParams,
  GetProjectsIdBudgetItems401,
  GetProjectsIdBudgetItems404,
} from "../types/GetProjectsIdBudgetItems.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdBudgetItems } from "../clients/getProjectsIdBudgetItems.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProjectsIdBudgetItemsQueryKey = (
  id: GetProjectsIdBudgetItemsPathParams["id"] | undefined,
  params?: GetProjectsIdBudgetItemsQueryParams,
) =>
  [
    { url: "/projects/:id/budget-items", params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type GetProjectsIdBudgetItemsQueryKey = ReturnType<
  typeof getProjectsIdBudgetItemsQueryKey
>;

export function getProjectsIdBudgetItemsQueryOptions(
  id: GetProjectsIdBudgetItemsPathParams["id"] | undefined,
  params?: GetProjectsIdBudgetItemsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdBudgetItemsQueryKey(id, params);
  return queryOptions<
    GetProjectsIdBudgetItemsQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdBudgetItems401 | GetProjectsIdBudgetItems404
    >,
    GetProjectsIdBudgetItemsQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdBudgetItems(id!, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List budget items for a project
 * {@link /projects/:id/budget-items}
 */
export function useGetProjectsIdBudgetItems<
  TData = GetProjectsIdBudgetItemsQueryResponse,
  TQueryData = GetProjectsIdBudgetItemsQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdBudgetItemsQueryKey,
>(
  id: GetProjectsIdBudgetItemsPathParams["id"] | undefined,
  params?: GetProjectsIdBudgetItemsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProjectsIdBudgetItemsQueryResponse,
        ResponseErrorConfig<
          GetProjectsIdBudgetItems401 | GetProjectsIdBudgetItems404
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getProjectsIdBudgetItemsQueryKey(id, params);

  const query = useQuery(
    {
      ...getProjectsIdBudgetItemsQueryOptions(id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetProjectsIdBudgetItems401 | GetProjectsIdBudgetItems404
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
