/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdStateChangesQueryResponse,
  GetProjectsIdStateChangesPathParams,
  GetProjectsIdStateChangesQueryParams,
  GetProjectsIdStateChanges401,
  GetProjectsIdStateChanges404,
} from "../types/GetProjectsIdStateChanges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdStateChanges } from "../clients/getProjectsIdStateChanges.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProjectsIdStateChangesSuspenseQueryKey = (
  id: GetProjectsIdStateChangesPathParams["id"] | undefined,
  params?: GetProjectsIdStateChangesQueryParams,
) =>
  [
    { url: "/projects/:id/state-changes", params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type GetProjectsIdStateChangesSuspenseQueryKey = ReturnType<
  typeof getProjectsIdStateChangesSuspenseQueryKey
>;

export function getProjectsIdStateChangesSuspenseQueryOptions(
  id: GetProjectsIdStateChangesPathParams["id"] | undefined,
  params?: GetProjectsIdStateChangesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdStateChangesSuspenseQueryKey(id, params);
  return queryOptions<
    GetProjectsIdStateChangesQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
    >,
    GetProjectsIdStateChangesQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdStateChanges(id!, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List state changes for a project
 * {@link /projects/:id/state-changes}
 */
export function useGetProjectsIdStateChangesSuspense<
  TData = GetProjectsIdStateChangesQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdStateChangesSuspenseQueryKey,
>(
  id: GetProjectsIdStateChangesPathParams["id"] | undefined,
  params?: GetProjectsIdStateChangesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProjectsIdStateChangesQueryResponse,
        ResponseErrorConfig<
          GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProjectsIdStateChangesSuspenseQueryKey(id, params);

  const query = useSuspenseQuery(
    {
      ...getProjectsIdStateChangesSuspenseQueryOptions(id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
