/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsIdStateChangesQueryResponse,
  GetProjectsIdStateChangesPathParams,
  GetProjectsIdStateChangesQueryParams,
  GetProjectsIdStateChanges401,
  GetProjectsIdStateChanges404,
} from "../types/GetProjectsIdStateChanges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getProjectsIdStateChanges } from "../clients/getProjectsIdStateChanges.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProjectsIdStateChangesQueryKey = (
  id: GetProjectsIdStateChangesPathParams["id"] | undefined,
  params?: GetProjectsIdStateChangesQueryParams,
) =>
  [
    { url: "/projects/:id/state-changes", params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type GetProjectsIdStateChangesQueryKey = ReturnType<
  typeof getProjectsIdStateChangesQueryKey
>;

export function getProjectsIdStateChangesQueryOptions(
  id: GetProjectsIdStateChangesPathParams["id"] | undefined,
  params?: GetProjectsIdStateChangesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsIdStateChangesQueryKey(id, params);
  return queryOptions<
    GetProjectsIdStateChangesQueryResponse,
    ResponseErrorConfig<
      GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
    >,
    GetProjectsIdStateChangesQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjectsIdStateChanges(id!, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List state changes for a project
 * {@link /projects/:id/state-changes}
 */
export function useGetProjectsIdStateChanges<
  TData = GetProjectsIdStateChangesQueryResponse,
  TQueryData = GetProjectsIdStateChangesQueryResponse,
  TQueryKey extends QueryKey = GetProjectsIdStateChangesQueryKey,
>(
  id: GetProjectsIdStateChangesPathParams["id"] | undefined,
  params?: GetProjectsIdStateChangesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProjectsIdStateChangesQueryResponse,
        ResponseErrorConfig<
          GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getProjectsIdStateChangesQueryKey(id, params);

  const query = useQuery(
    {
      ...getProjectsIdStateChangesQueryOptions(id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetProjectsIdStateChanges401 | GetProjectsIdStateChanges404
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
