/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetEnrichmentsIdQueryResponse,
  GetEnrichmentsIdPathParams,
  GetEnrichmentsId401,
  GetEnrichmentsId404,
} from "../types/GetEnrichmentsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getEnrichmentsId } from "../clients/getEnrichmentsId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getEnrichmentsIdSuspenseQueryKey = (
  id: GetEnrichmentsIdPathParams["id"] | undefined,
) => [{ url: "/enrichments/:id", params: { id: id } }] as const;

export type GetEnrichmentsIdSuspenseQueryKey = ReturnType<
  typeof getEnrichmentsIdSuspenseQueryKey
>;

export function getEnrichmentsIdSuspenseQueryOptions(
  id: GetEnrichmentsIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getEnrichmentsIdSuspenseQueryKey(id);
  return queryOptions<
    GetEnrichmentsIdQueryResponse,
    ResponseErrorConfig<GetEnrichmentsId401 | GetEnrichmentsId404>,
    GetEnrichmentsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getEnrichmentsId(id!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get enrichment insight status and result
 * {@link /enrichments/:id}
 */
export function useGetEnrichmentsIdSuspense<
  TData = GetEnrichmentsIdQueryResponse,
  TQueryKey extends QueryKey = GetEnrichmentsIdSuspenseQueryKey,
>(
  id: GetEnrichmentsIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetEnrichmentsIdQueryResponse,
        ResponseErrorConfig<GetEnrichmentsId401 | GetEnrichmentsId404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getEnrichmentsIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getEnrichmentsIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetEnrichmentsId401 | GetEnrichmentsId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
