/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetImportsIdQueryResponse,
  GetImportsIdPathParams,
  GetImportsId401,
  GetImportsId404,
} from "../types/GetImportsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getImportsId } from "../clients/getImportsId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getImportsIdQueryKey = (
  id: GetImportsIdPathParams["id"] | undefined,
) => [{ url: "/imports/:id", params: { id: id } }] as const;

export type GetImportsIdQueryKey = ReturnType<typeof getImportsIdQueryKey>;

export function getImportsIdQueryOptions(
  id: GetImportsIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getImportsIdQueryKey(id);
  return queryOptions<
    GetImportsIdQueryResponse,
    ResponseErrorConfig<GetImportsId401 | GetImportsId404>,
    GetImportsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getImportsId(id!, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get the current status and progress of an import
 * {@link /imports/:id}
 */
export function useGetImportsId<
  TData = GetImportsIdQueryResponse,
  TQueryData = GetImportsIdQueryResponse,
  TQueryKey extends QueryKey = GetImportsIdQueryKey,
>(
  id: GetImportsIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetImportsIdQueryResponse,
        ResponseErrorConfig<GetImportsId401 | GetImportsId404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getImportsIdQueryKey(id);

  const query = useQuery(
    {
      ...getImportsIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetImportsId401 | GetImportsId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
