/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetContactsIdQueryResponse,
  GetContactsIdPathParams,
  GetContactsId401,
  GetContactsId404,
} from "../types/GetContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getContactsId } from "../clients/getContactsId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getContactsIdSuspenseQueryKey = (
  id: GetContactsIdPathParams["id"] | undefined,
) => [{ url: "/contacts/:id", params: { id: id } }] as const;

export type GetContactsIdSuspenseQueryKey = ReturnType<
  typeof getContactsIdSuspenseQueryKey
>;

export function getContactsIdSuspenseQueryOptions(
  id: GetContactsIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getContactsIdSuspenseQueryKey(id);
  return queryOptions<
    GetContactsIdQueryResponse,
    ResponseErrorConfig<GetContactsId401 | GetContactsId404>,
    GetContactsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getContactsId(id!, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get a contact by id
 * {@link /contacts/:id}
 */
export function useGetContactsIdSuspense<
  TData = GetContactsIdQueryResponse,
  TQueryKey extends QueryKey = GetContactsIdSuspenseQueryKey,
>(
  id: GetContactsIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetContactsIdQueryResponse,
        ResponseErrorConfig<GetContactsId401 | GetContactsId404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getContactsIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getContactsIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetContactsId401 | GetContactsId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
