/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetUsersQueryResponse,
  GetUsersQueryParams,
  GetUsers401,
} from "../types/GetUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getUsers } from "../clients/getUsers.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUsersQueryKey = (params?: GetUsersQueryParams) =>
  [{ url: "/users" }, ...(params ? [params] : [])] as const;

export type GetUsersQueryKey = ReturnType<typeof getUsersQueryKey>;

export function getUsersQueryOptions(
  params?: GetUsersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getUsersQueryKey(params);
  return queryOptions<
    GetUsersQueryResponse,
    ResponseErrorConfig<GetUsers401>,
    GetUsersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getUsers(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary List users
 * {@link /users}
 */
export function useGetUsers<
  TData = GetUsersQueryResponse,
  TQueryData = GetUsersQueryResponse,
  TQueryKey extends QueryKey = GetUsersQueryKey,
>(
  params?: GetUsersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetUsersQueryResponse,
        ResponseErrorConfig<GetUsers401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getUsersQueryKey(params);

  const query = useQuery(
    {
      ...getUsersQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetUsers401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
