/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetProjectsQueryResponse,
  GetProjectsQueryParams,
  GetProjects401,
} from "../types/GetProjects.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getProjects } from "../clients/getProjects.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProjectsSuspenseQueryKey = (params?: GetProjectsQueryParams) =>
  [{ url: "/projects" }, ...(params ? [params] : [])] as const;

export type GetProjectsSuspenseQueryKey = ReturnType<
  typeof getProjectsSuspenseQueryKey
>;

export function getProjectsSuspenseQueryOptions(
  params?: GetProjectsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProjectsSuspenseQueryKey(params);
  return queryOptions<
    GetProjectsQueryResponse,
    ResponseErrorConfig<GetProjects401>,
    GetProjectsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProjects(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List projects
 * {@link /projects}
 */
export function useGetProjectsSuspense<
  TData = GetProjectsQueryResponse,
  TQueryKey extends QueryKey = GetProjectsSuspenseQueryKey,
>(
  params?: GetProjectsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProjectsQueryResponse,
        ResponseErrorConfig<GetProjects401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getProjectsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getProjectsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetProjects401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
