/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetImportsIdQueryResponse,
  GetImportsIdPathParams,
  GetImportsId401,
  GetImportsId404,
} from "../types/GetImportsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getImportsId } from "../clients/getImportsId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getImportsIdSuspenseQueryKey = (
  id: GetImportsIdPathParams["id"] | undefined,
) => [{ url: "/imports/:id", params: { id: id } }] as const;

export type GetImportsIdSuspenseQueryKey = ReturnType<
  typeof getImportsIdSuspenseQueryKey
>;

export function getImportsIdSuspenseQueryOptions(
  id: GetImportsIdPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getImportsIdSuspenseQueryKey(id);
  return queryOptions<
    GetImportsIdQueryResponse,
    ResponseErrorConfig<GetImportsId401 | GetImportsId404>,
    GetImportsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getImportsId(id!, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get the current status and progress of an import
 * {@link /imports/:id}
 */
export function useGetImportsIdSuspense<
  TData = GetImportsIdQueryResponse,
  TQueryKey extends QueryKey = GetImportsIdSuspenseQueryKey,
>(
  id: GetImportsIdPathParams["id"] | undefined,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetImportsIdQueryResponse,
        ResponseErrorConfig<GetImportsId401 | GetImportsId404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getImportsIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getImportsIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetImportsId401 | GetImportsId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
