/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetImportsQueryResponse,
  GetImportsQueryParams,
  GetImports401,
} from "../types/GetImports.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getImports } from "../clients/getImports.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getImportsSuspenseQueryKey = (params?: GetImportsQueryParams) =>
  [{ url: "/imports" }, ...(params ? [params] : [])] as const;

export type GetImportsSuspenseQueryKey = ReturnType<
  typeof getImportsSuspenseQueryKey
>;

export function getImportsSuspenseQueryOptions(
  params?: GetImportsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getImportsSuspenseQueryKey(params);
  return queryOptions<
    GetImportsQueryResponse,
    ResponseErrorConfig<GetImports401>,
    GetImportsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getImports(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary List imports (paginated)
 * {@link /imports}
 */
export function useGetImportsSuspense<
  TData = GetImportsQueryResponse,
  TQueryKey extends QueryKey = GetImportsSuspenseQueryKey,
>(
  params?: GetImportsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetImportsQueryResponse,
        ResponseErrorConfig<GetImports401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getImportsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getImportsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetImports401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
