/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetEnrichmentsQueryResponse,
  GetEnrichmentsQueryParams,
  GetEnrichments400,
  GetEnrichments401,
} from "../types/GetEnrichments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getEnrichments } from "../clients/getEnrichments.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getEnrichmentsSuspenseQueryKey = (
  params: GetEnrichmentsQueryParams,
) => [{ url: "/enrichments" }, ...(params ? [params] : [])] as const;

export type GetEnrichmentsSuspenseQueryKey = ReturnType<
  typeof getEnrichmentsSuspenseQueryKey
>;

export function getEnrichmentsSuspenseQueryOptions(
  params: GetEnrichmentsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getEnrichmentsSuspenseQueryKey(params);
  return queryOptions<
    GetEnrichmentsQueryResponse,
    ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>,
    GetEnrichmentsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getEnrichments(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List enrichment insights for a contact
 * {@link /enrichments}
 */
export function useGetEnrichmentsSuspense<
  TData = GetEnrichmentsQueryResponse,
  TQueryKey extends QueryKey = GetEnrichmentsSuspenseQueryKey,
>(
  params: GetEnrichmentsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetEnrichmentsQueryResponse,
        ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getEnrichmentsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getEnrichmentsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetEnrichments400 | GetEnrichments401>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
