/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostContactsBulkDeleteMutationRequest,
  PostContactsBulkDeleteMutationResponse,
  PostContactsBulkDelete401,
} from "../types/PostContactsBulkDelete.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postContactsBulkDelete } from "../clients/postContactsBulkDelete.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postContactsBulkDeleteMutationKey = () =>
  [{ url: "/contacts/bulk-delete" }] as const;

export type PostContactsBulkDeleteMutationKey = ReturnType<
  typeof postContactsBulkDeleteMutationKey
>;

export function postContactsBulkDeleteMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostContactsBulkDeleteMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postContactsBulkDeleteMutationKey();
  return mutationOptions<
    PostContactsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostContactsBulkDelete401>,
    { data: PostContactsBulkDeleteMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postContactsBulkDelete(data, config);
    },
  });
}

/**
 * @summary Soft-delete multiple contacts
 * {@link /contacts/bulk-delete}
 */
export function usePostContactsBulkDelete<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostContactsBulkDeleteMutationResponse,
      ResponseErrorConfig<PostContactsBulkDelete401>,
      { data: PostContactsBulkDeleteMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostContactsBulkDeleteMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postContactsBulkDeleteMutationKey();

  const baseOptions = postContactsBulkDeleteMutationOptions(
    config,
  ) as UseMutationOptions<
    PostContactsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostContactsBulkDelete401>,
    { data: PostContactsBulkDeleteMutationRequest },
    TContext
  >;

  return useMutation<
    PostContactsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostContactsBulkDelete401>,
    { data: PostContactsBulkDeleteMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostContactsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostContactsBulkDelete401>,
    { data: PostContactsBulkDeleteMutationRequest },
    TContext
  >;
}
