/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchContactsIdChannelsChannelidMutationRequest,
  PatchContactsIdChannelsChannelidMutationResponse,
  PatchContactsIdChannelsChannelidPathParams,
  PatchContactsIdChannelsChannelid401,
  PatchContactsIdChannelsChannelid404,
} from "../types/PatchContactsIdChannelsChannelid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchContactsIdChannelsChannelid } from "../clients/patchContactsIdChannelsChannelid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchContactsIdChannelsChannelidMutationKey = () =>
  [{ url: "/contacts/:id/channels/:channelId" }] as const;

export type PatchContactsIdChannelsChannelidMutationKey = ReturnType<
  typeof patchContactsIdChannelsChannelidMutationKey
>;

export function patchContactsIdChannelsChannelidMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchContactsIdChannelsChannelidMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchContactsIdChannelsChannelidMutationKey();
  return mutationOptions<
    PatchContactsIdChannelsChannelidMutationResponse,
    ResponseErrorConfig<
      PatchContactsIdChannelsChannelid401 | PatchContactsIdChannelsChannelid404
    >,
    {
      id: PatchContactsIdChannelsChannelidPathParams["id"];
      channelId: PatchContactsIdChannelsChannelidPathParams["channelId"];
      data: PatchContactsIdChannelsChannelidMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, channelId, data }) => {
      return patchContactsIdChannelsChannelid(id, channelId, data, config);
    },
  });
}

/**
 * @summary Update a communication channel on a contact
 * {@link /contacts/:id/channels/:channelId}
 */
export function usePatchContactsIdChannelsChannelid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchContactsIdChannelsChannelidMutationResponse,
      ResponseErrorConfig<
        | PatchContactsIdChannelsChannelid401
        | PatchContactsIdChannelsChannelid404
      >,
      {
        id: PatchContactsIdChannelsChannelidPathParams["id"];
        channelId: PatchContactsIdChannelsChannelidPathParams["channelId"];
        data: PatchContactsIdChannelsChannelidMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchContactsIdChannelsChannelidMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    patchContactsIdChannelsChannelidMutationKey();

  const baseOptions = patchContactsIdChannelsChannelidMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchContactsIdChannelsChannelidMutationResponse,
    ResponseErrorConfig<
      PatchContactsIdChannelsChannelid401 | PatchContactsIdChannelsChannelid404
    >,
    {
      id: PatchContactsIdChannelsChannelidPathParams["id"];
      channelId: PatchContactsIdChannelsChannelidPathParams["channelId"];
      data: PatchContactsIdChannelsChannelidMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchContactsIdChannelsChannelidMutationResponse,
    ResponseErrorConfig<
      PatchContactsIdChannelsChannelid401 | PatchContactsIdChannelsChannelid404
    >,
    {
      id: PatchContactsIdChannelsChannelidPathParams["id"];
      channelId: PatchContactsIdChannelsChannelidPathParams["channelId"];
      data: PatchContactsIdChannelsChannelidMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchContactsIdChannelsChannelidMutationResponse,
    ResponseErrorConfig<
      PatchContactsIdChannelsChannelid401 | PatchContactsIdChannelsChannelid404
    >,
    {
      id: PatchContactsIdChannelsChannelidPathParams["id"];
      channelId: PatchContactsIdChannelsChannelidPathParams["channelId"];
      data: PatchContactsIdChannelsChannelidMutationRequest;
    },
    TContext
  >;
}
