/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostContactsIdEventsMutationRequest,
  PostContactsIdEventsMutationResponse,
  PostContactsIdEventsPathParams,
  PostContactsIdEvents401,
  PostContactsIdEvents404,
} from "../types/PostContactsIdEvents.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postContactsIdEvents } from "../clients/postContactsIdEvents.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postContactsIdEventsMutationKey = () =>
  [{ url: "/contacts/:id/events" }] as const;

export type PostContactsIdEventsMutationKey = ReturnType<
  typeof postContactsIdEventsMutationKey
>;

export function postContactsIdEventsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostContactsIdEventsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postContactsIdEventsMutationKey();
  return mutationOptions<
    PostContactsIdEventsMutationResponse,
    ResponseErrorConfig<PostContactsIdEvents401 | PostContactsIdEvents404>,
    {
      id: PostContactsIdEventsPathParams["id"];
      data: PostContactsIdEventsMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postContactsIdEvents(id, data, config);
    },
  });
}

/**
 * @summary Register an event on a contact
 * {@link /contacts/:id/events}
 */
export function usePostContactsIdEvents<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostContactsIdEventsMutationResponse,
      ResponseErrorConfig<PostContactsIdEvents401 | PostContactsIdEvents404>,
      {
        id: PostContactsIdEventsPathParams["id"];
        data: PostContactsIdEventsMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostContactsIdEventsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postContactsIdEventsMutationKey();

  const baseOptions = postContactsIdEventsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostContactsIdEventsMutationResponse,
    ResponseErrorConfig<PostContactsIdEvents401 | PostContactsIdEvents404>,
    {
      id: PostContactsIdEventsPathParams["id"];
      data: PostContactsIdEventsMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostContactsIdEventsMutationResponse,
    ResponseErrorConfig<PostContactsIdEvents401 | PostContactsIdEvents404>,
    {
      id: PostContactsIdEventsPathParams["id"];
      data: PostContactsIdEventsMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostContactsIdEventsMutationResponse,
    ResponseErrorConfig<PostContactsIdEvents401 | PostContactsIdEvents404>,
    {
      id: PostContactsIdEventsPathParams["id"];
      data: PostContactsIdEventsMutationRequest;
    },
    TContext
  >;
}
