/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostImportsMutationResponse,
  PostImports400,
  PostImports401,
} from "../types/PostImports.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postImports } from "../clients/postImports.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postImportsMutationKey = () => [{ url: "/imports" }] as const;

export type PostImportsMutationKey = ReturnType<typeof postImportsMutationKey>;

export function postImportsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postImportsMutationKey();
  return mutationOptions<
    PostImportsMutationResponse,
    ResponseErrorConfig<PostImports400 | PostImports401>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return postImports(config);
    },
  });
}

/**
 * @summary Upload an xlsx file and start an import
 * {@link /imports}
 */
export function usePostImports<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostImportsMutationResponse,
      ResponseErrorConfig<PostImports400 | PostImports401>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postImportsMutationKey();

  const baseOptions = postImportsMutationOptions(config) as UseMutationOptions<
    PostImportsMutationResponse,
    ResponseErrorConfig<PostImports400 | PostImports401>,
    void,
    TContext
  >;

  return useMutation<
    PostImportsMutationResponse,
    ResponseErrorConfig<PostImports400 | PostImports401>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostImportsMutationResponse,
    ResponseErrorConfig<PostImports400 | PostImports401>,
    void,
    TContext
  >;
}
