/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostAnalysisTemplatesMutationRequest,
  PostAnalysisTemplatesMutationResponse,
  PostAnalysisTemplates400,
  PostAnalysisTemplates401,
} from "../types/PostAnalysisTemplates.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postAnalysisTemplates } from "../clients/postAnalysisTemplates.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAnalysisTemplatesMutationKey = () =>
  [{ url: "/analysis-templates" }] as const;

export type PostAnalysisTemplatesMutationKey = ReturnType<
  typeof postAnalysisTemplatesMutationKey
>;

export function postAnalysisTemplatesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAnalysisTemplatesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAnalysisTemplatesMutationKey();
  return mutationOptions<
    PostAnalysisTemplatesMutationResponse,
    ResponseErrorConfig<PostAnalysisTemplates400 | PostAnalysisTemplates401>,
    { data: PostAnalysisTemplatesMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAnalysisTemplates(data, config);
    },
  });
}

/**
 * @summary Create an analysis template
 * {@link /analysis-templates}
 */
export function usePostAnalysisTemplates<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAnalysisTemplatesMutationResponse,
      ResponseErrorConfig<PostAnalysisTemplates400 | PostAnalysisTemplates401>,
      { data: PostAnalysisTemplatesMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAnalysisTemplatesMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAnalysisTemplatesMutationKey();

  const baseOptions = postAnalysisTemplatesMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAnalysisTemplatesMutationResponse,
    ResponseErrorConfig<PostAnalysisTemplates400 | PostAnalysisTemplates401>,
    { data: PostAnalysisTemplatesMutationRequest },
    TContext
  >;

  return useMutation<
    PostAnalysisTemplatesMutationResponse,
    ResponseErrorConfig<PostAnalysisTemplates400 | PostAnalysisTemplates401>,
    { data: PostAnalysisTemplatesMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAnalysisTemplatesMutationResponse,
    ResponseErrorConfig<PostAnalysisTemplates400 | PostAnalysisTemplates401>,
    { data: PostAnalysisTemplatesMutationRequest },
    TContext
  >;
}
