/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchProjectsIdExpensesExpenseidMutationRequest,
  PatchProjectsIdExpensesExpenseidMutationResponse,
  PatchProjectsIdExpensesExpenseidPathParams,
  PatchProjectsIdExpensesExpenseid401,
  PatchProjectsIdExpensesExpenseid404,
} from "../types/PatchProjectsIdExpensesExpenseid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchProjectsIdExpensesExpenseid } from "../clients/patchProjectsIdExpensesExpenseid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchProjectsIdExpensesExpenseidMutationKey = () =>
  [{ url: "/projects/:id/expenses/:expenseId" }] as const;

export type PatchProjectsIdExpensesExpenseidMutationKey = ReturnType<
  typeof patchProjectsIdExpensesExpenseidMutationKey
>;

export function patchProjectsIdExpensesExpenseidMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchProjectsIdExpensesExpenseidMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchProjectsIdExpensesExpenseidMutationKey();
  return mutationOptions<
    PatchProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExpensesExpenseid401 | PatchProjectsIdExpensesExpenseid404
    >,
    {
      id: PatchProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"];
      data: PatchProjectsIdExpensesExpenseidMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, expenseId, data }) => {
      return patchProjectsIdExpensesExpenseid(id, expenseId, data, config);
    },
  });
}

/**
 * @summary Update an expense
 * {@link /projects/:id/expenses/:expenseId}
 */
export function usePatchProjectsIdExpensesExpenseid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchProjectsIdExpensesExpenseidMutationResponse,
      ResponseErrorConfig<
        | PatchProjectsIdExpensesExpenseid401
        | PatchProjectsIdExpensesExpenseid404
      >,
      {
        id: PatchProjectsIdExpensesExpenseidPathParams["id"];
        expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"];
        data: PatchProjectsIdExpensesExpenseidMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchProjectsIdExpensesExpenseidMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    patchProjectsIdExpensesExpenseidMutationKey();

  const baseOptions = patchProjectsIdExpensesExpenseidMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExpensesExpenseid401 | PatchProjectsIdExpensesExpenseid404
    >,
    {
      id: PatchProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"];
      data: PatchProjectsIdExpensesExpenseidMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExpensesExpenseid401 | PatchProjectsIdExpensesExpenseid404
    >,
    {
      id: PatchProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"];
      data: PatchProjectsIdExpensesExpenseidMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchProjectsIdExpensesExpenseidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExpensesExpenseid401 | PatchProjectsIdExpensesExpenseid404
    >,
    {
      id: PatchProjectsIdExpensesExpenseidPathParams["id"];
      expenseId: PatchProjectsIdExpensesExpenseidPathParams["expenseId"];
      data: PatchProjectsIdExpensesExpenseidMutationRequest;
    },
    TContext
  >;
}
