/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostProjectsIdBudgetItemsMutationRequest,
  PostProjectsIdBudgetItemsMutationResponse,
  PostProjectsIdBudgetItemsPathParams,
  PostProjectsIdBudgetItems401,
  PostProjectsIdBudgetItems404,
} from "../types/PostProjectsIdBudgetItems.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postProjectsIdBudgetItems } from "../clients/postProjectsIdBudgetItems.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postProjectsIdBudgetItemsMutationKey = () =>
  [{ url: "/projects/:id/budget-items" }] as const;

export type PostProjectsIdBudgetItemsMutationKey = ReturnType<
  typeof postProjectsIdBudgetItemsMutationKey
>;

export function postProjectsIdBudgetItemsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostProjectsIdBudgetItemsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postProjectsIdBudgetItemsMutationKey();
  return mutationOptions<
    PostProjectsIdBudgetItemsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdBudgetItems401 | PostProjectsIdBudgetItems404
    >,
    {
      id: PostProjectsIdBudgetItemsPathParams["id"];
      data: PostProjectsIdBudgetItemsMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postProjectsIdBudgetItems(id, data, config);
    },
  });
}

/**
 * @summary Add a budget item to a project
 * {@link /projects/:id/budget-items}
 */
export function usePostProjectsIdBudgetItems<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProjectsIdBudgetItemsMutationResponse,
      ResponseErrorConfig<
        PostProjectsIdBudgetItems401 | PostProjectsIdBudgetItems404
      >,
      {
        id: PostProjectsIdBudgetItemsPathParams["id"];
        data: PostProjectsIdBudgetItemsMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostProjectsIdBudgetItemsMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postProjectsIdBudgetItemsMutationKey();

  const baseOptions = postProjectsIdBudgetItemsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostProjectsIdBudgetItemsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdBudgetItems401 | PostProjectsIdBudgetItems404
    >,
    {
      id: PostProjectsIdBudgetItemsPathParams["id"];
      data: PostProjectsIdBudgetItemsMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostProjectsIdBudgetItemsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdBudgetItems401 | PostProjectsIdBudgetItems404
    >,
    {
      id: PostProjectsIdBudgetItemsPathParams["id"];
      data: PostProjectsIdBudgetItemsMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostProjectsIdBudgetItemsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdBudgetItems401 | PostProjectsIdBudgetItems404
    >,
    {
      id: PostProjectsIdBudgetItemsPathParams["id"];
      data: PostProjectsIdBudgetItemsMutationRequest;
    },
    TContext
  >;
}
