/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchAnalysisTemplatesIdMutationRequest,
  PatchAnalysisTemplatesIdMutationResponse,
  PatchAnalysisTemplatesIdPathParams,
  PatchAnalysisTemplatesId400,
  PatchAnalysisTemplatesId401,
  PatchAnalysisTemplatesId404,
} from "../types/PatchAnalysisTemplatesId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchAnalysisTemplatesId } from "../clients/patchAnalysisTemplatesId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchAnalysisTemplatesIdMutationKey = () =>
  [{ url: "/analysis-templates/:id" }] as const;

export type PatchAnalysisTemplatesIdMutationKey = ReturnType<
  typeof patchAnalysisTemplatesIdMutationKey
>;

export function patchAnalysisTemplatesIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchAnalysisTemplatesIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchAnalysisTemplatesIdMutationKey();
  return mutationOptions<
    PatchAnalysisTemplatesIdMutationResponse,
    ResponseErrorConfig<
      | PatchAnalysisTemplatesId400
      | PatchAnalysisTemplatesId401
      | PatchAnalysisTemplatesId404
    >,
    {
      id: PatchAnalysisTemplatesIdPathParams["id"];
      data: PatchAnalysisTemplatesIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchAnalysisTemplatesId(id, data, config);
    },
  });
}

/**
 * @summary Update an analysis template
 * {@link /analysis-templates/:id}
 */
export function usePatchAnalysisTemplatesId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchAnalysisTemplatesIdMutationResponse,
      ResponseErrorConfig<
        | PatchAnalysisTemplatesId400
        | PatchAnalysisTemplatesId401
        | PatchAnalysisTemplatesId404
      >,
      {
        id: PatchAnalysisTemplatesIdPathParams["id"];
        data: PatchAnalysisTemplatesIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchAnalysisTemplatesIdMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchAnalysisTemplatesIdMutationKey();

  const baseOptions = patchAnalysisTemplatesIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchAnalysisTemplatesIdMutationResponse,
    ResponseErrorConfig<
      | PatchAnalysisTemplatesId400
      | PatchAnalysisTemplatesId401
      | PatchAnalysisTemplatesId404
    >,
    {
      id: PatchAnalysisTemplatesIdPathParams["id"];
      data: PatchAnalysisTemplatesIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchAnalysisTemplatesIdMutationResponse,
    ResponseErrorConfig<
      | PatchAnalysisTemplatesId400
      | PatchAnalysisTemplatesId401
      | PatchAnalysisTemplatesId404
    >,
    {
      id: PatchAnalysisTemplatesIdPathParams["id"];
      data: PatchAnalysisTemplatesIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchAnalysisTemplatesIdMutationResponse,
    ResponseErrorConfig<
      | PatchAnalysisTemplatesId400
      | PatchAnalysisTemplatesId401
      | PatchAnalysisTemplatesId404
    >,
    {
      id: PatchAnalysisTemplatesIdPathParams["id"];
      data: PatchAnalysisTemplatesIdMutationRequest;
    },
    TContext
  >;
}
