/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchProjectsIdExtensionsExtidMutationRequest,
  PatchProjectsIdExtensionsExtidMutationResponse,
  PatchProjectsIdExtensionsExtidPathParams,
  PatchProjectsIdExtensionsExtid401,
  PatchProjectsIdExtensionsExtid404,
} from "../types/PatchProjectsIdExtensionsExtid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchProjectsIdExtensionsExtid } from "../clients/patchProjectsIdExtensionsExtid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchProjectsIdExtensionsExtidMutationKey = () =>
  [{ url: "/projects/:id/extensions/:extId" }] as const;

export type PatchProjectsIdExtensionsExtidMutationKey = ReturnType<
  typeof patchProjectsIdExtensionsExtidMutationKey
>;

export function patchProjectsIdExtensionsExtidMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchProjectsIdExtensionsExtidMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchProjectsIdExtensionsExtidMutationKey();
  return mutationOptions<
    PatchProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExtensionsExtid401 | PatchProjectsIdExtensionsExtid404
    >,
    {
      id: PatchProjectsIdExtensionsExtidPathParams["id"];
      extId: PatchProjectsIdExtensionsExtidPathParams["extId"];
      data: PatchProjectsIdExtensionsExtidMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, extId, data }) => {
      return patchProjectsIdExtensionsExtid(id, extId, data, config);
    },
  });
}

/**
 * @summary Update an extension
 * {@link /projects/:id/extensions/:extId}
 */
export function usePatchProjectsIdExtensionsExtid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchProjectsIdExtensionsExtidMutationResponse,
      ResponseErrorConfig<
        PatchProjectsIdExtensionsExtid401 | PatchProjectsIdExtensionsExtid404
      >,
      {
        id: PatchProjectsIdExtensionsExtidPathParams["id"];
        extId: PatchProjectsIdExtensionsExtidPathParams["extId"];
        data: PatchProjectsIdExtensionsExtidMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchProjectsIdExtensionsExtidMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchProjectsIdExtensionsExtidMutationKey();

  const baseOptions = patchProjectsIdExtensionsExtidMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExtensionsExtid401 | PatchProjectsIdExtensionsExtid404
    >,
    {
      id: PatchProjectsIdExtensionsExtidPathParams["id"];
      extId: PatchProjectsIdExtensionsExtidPathParams["extId"];
      data: PatchProjectsIdExtensionsExtidMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExtensionsExtid401 | PatchProjectsIdExtensionsExtid404
    >,
    {
      id: PatchProjectsIdExtensionsExtidPathParams["id"];
      extId: PatchProjectsIdExtensionsExtidPathParams["extId"];
      data: PatchProjectsIdExtensionsExtidMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchProjectsIdExtensionsExtidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdExtensionsExtid401 | PatchProjectsIdExtensionsExtid404
    >,
    {
      id: PatchProjectsIdExtensionsExtidPathParams["id"];
      extId: PatchProjectsIdExtensionsExtidPathParams["extId"];
      data: PatchProjectsIdExtensionsExtidMutationRequest;
    },
    TContext
  >;
}
