/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostProjectsIdDocumentsMutationResponse,
  PostProjectsIdDocumentsPathParams,
  PostProjectsIdDocuments400,
  PostProjectsIdDocuments401,
  PostProjectsIdDocuments404,
} from "../types/PostProjectsIdDocuments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postProjectsIdDocuments } from "../clients/postProjectsIdDocuments.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postProjectsIdDocumentsMutationKey = () =>
  [{ url: "/projects/:id/documents" }] as const;

export type PostProjectsIdDocumentsMutationKey = ReturnType<
  typeof postProjectsIdDocumentsMutationKey
>;

export function postProjectsIdDocumentsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postProjectsIdDocumentsMutationKey();
  return mutationOptions<
    PostProjectsIdDocumentsMutationResponse,
    ResponseErrorConfig<
      | PostProjectsIdDocuments400
      | PostProjectsIdDocuments401
      | PostProjectsIdDocuments404
    >,
    { id: PostProjectsIdDocumentsPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postProjectsIdDocuments(id, config);
    },
  });
}

/**
 * @summary Upload a document to a project
 * {@link /projects/:id/documents}
 */
export function usePostProjectsIdDocuments<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProjectsIdDocumentsMutationResponse,
      ResponseErrorConfig<
        | PostProjectsIdDocuments400
        | PostProjectsIdDocuments401
        | PostProjectsIdDocuments404
      >,
      { id: PostProjectsIdDocumentsPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postProjectsIdDocumentsMutationKey();

  const baseOptions = postProjectsIdDocumentsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostProjectsIdDocumentsMutationResponse,
    ResponseErrorConfig<
      | PostProjectsIdDocuments400
      | PostProjectsIdDocuments401
      | PostProjectsIdDocuments404
    >,
    { id: PostProjectsIdDocumentsPathParams["id"] },
    TContext
  >;

  return useMutation<
    PostProjectsIdDocumentsMutationResponse,
    ResponseErrorConfig<
      | PostProjectsIdDocuments400
      | PostProjectsIdDocuments401
      | PostProjectsIdDocuments404
    >,
    { id: PostProjectsIdDocumentsPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostProjectsIdDocumentsMutationResponse,
    ResponseErrorConfig<
      | PostProjectsIdDocuments400
      | PostProjectsIdDocuments401
      | PostProjectsIdDocuments404
    >,
    { id: PostProjectsIdDocumentsPathParams["id"] },
    TContext
  >;
}
