/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostProjectsIdExtensionsMutationRequest,
  PostProjectsIdExtensionsMutationResponse,
  PostProjectsIdExtensionsPathParams,
  PostProjectsIdExtensions401,
  PostProjectsIdExtensions404,
} from "../types/PostProjectsIdExtensions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postProjectsIdExtensions } from "../clients/postProjectsIdExtensions.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postProjectsIdExtensionsMutationKey = () =>
  [{ url: "/projects/:id/extensions" }] as const;

export type PostProjectsIdExtensionsMutationKey = ReturnType<
  typeof postProjectsIdExtensionsMutationKey
>;

export function postProjectsIdExtensionsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostProjectsIdExtensionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postProjectsIdExtensionsMutationKey();
  return mutationOptions<
    PostProjectsIdExtensionsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdExtensions401 | PostProjectsIdExtensions404
    >,
    {
      id: PostProjectsIdExtensionsPathParams["id"];
      data: PostProjectsIdExtensionsMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postProjectsIdExtensions(id, data, config);
    },
  });
}

/**
 * @summary Add an extension to a project
 * {@link /projects/:id/extensions}
 */
export function usePostProjectsIdExtensions<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProjectsIdExtensionsMutationResponse,
      ResponseErrorConfig<
        PostProjectsIdExtensions401 | PostProjectsIdExtensions404
      >,
      {
        id: PostProjectsIdExtensionsPathParams["id"];
        data: PostProjectsIdExtensionsMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostProjectsIdExtensionsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postProjectsIdExtensionsMutationKey();

  const baseOptions = postProjectsIdExtensionsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostProjectsIdExtensionsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdExtensions401 | PostProjectsIdExtensions404
    >,
    {
      id: PostProjectsIdExtensionsPathParams["id"];
      data: PostProjectsIdExtensionsMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostProjectsIdExtensionsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdExtensions401 | PostProjectsIdExtensions404
    >,
    {
      id: PostProjectsIdExtensionsPathParams["id"];
      data: PostProjectsIdExtensionsMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostProjectsIdExtensionsMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdExtensions401 | PostProjectsIdExtensions404
    >,
    {
      id: PostProjectsIdExtensionsPathParams["id"];
      data: PostProjectsIdExtensionsMutationRequest;
    },
    TContext
  >;
}
