/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostContactsIdChannelsMutationRequest,
  PostContactsIdChannelsMutationResponse,
  PostContactsIdChannelsPathParams,
  PostContactsIdChannels401,
  PostContactsIdChannels404,
} from "../types/PostContactsIdChannels.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postContactsIdChannels } from "../clients/postContactsIdChannels.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postContactsIdChannelsMutationKey = () =>
  [{ url: "/contacts/:id/channels" }] as const;

export type PostContactsIdChannelsMutationKey = ReturnType<
  typeof postContactsIdChannelsMutationKey
>;

export function postContactsIdChannelsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostContactsIdChannelsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postContactsIdChannelsMutationKey();
  return mutationOptions<
    PostContactsIdChannelsMutationResponse,
    ResponseErrorConfig<PostContactsIdChannels401 | PostContactsIdChannels404>,
    {
      id: PostContactsIdChannelsPathParams["id"];
      data: PostContactsIdChannelsMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postContactsIdChannels(id, data, config);
    },
  });
}

/**
 * @summary Add a communication channel to a contact
 * {@link /contacts/:id/channels}
 */
export function usePostContactsIdChannels<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostContactsIdChannelsMutationResponse,
      ResponseErrorConfig<
        PostContactsIdChannels401 | PostContactsIdChannels404
      >,
      {
        id: PostContactsIdChannelsPathParams["id"];
        data: PostContactsIdChannelsMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostContactsIdChannelsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postContactsIdChannelsMutationKey();

  const baseOptions = postContactsIdChannelsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostContactsIdChannelsMutationResponse,
    ResponseErrorConfig<PostContactsIdChannels401 | PostContactsIdChannels404>,
    {
      id: PostContactsIdChannelsPathParams["id"];
      data: PostContactsIdChannelsMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostContactsIdChannelsMutationResponse,
    ResponseErrorConfig<PostContactsIdChannels401 | PostContactsIdChannels404>,
    {
      id: PostContactsIdChannelsPathParams["id"];
      data: PostContactsIdChannelsMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostContactsIdChannelsMutationResponse,
    ResponseErrorConfig<PostContactsIdChannels401 | PostContactsIdChannels404>,
    {
      id: PostContactsIdChannelsPathParams["id"];
      data: PostContactsIdChannelsMutationRequest;
    },
    TContext
  >;
}
