/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchProjectsIdResponsiblesUseridMutationRequest,
  PatchProjectsIdResponsiblesUseridMutationResponse,
  PatchProjectsIdResponsiblesUseridPathParams,
  PatchProjectsIdResponsiblesUserid401,
  PatchProjectsIdResponsiblesUserid404,
} from "../types/PatchProjectsIdResponsiblesUserid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchProjectsIdResponsiblesUserid } from "../clients/patchProjectsIdResponsiblesUserid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchProjectsIdResponsiblesUseridMutationKey = () =>
  [{ url: "/projects/:id/responsibles/:userId" }] as const;

export type PatchProjectsIdResponsiblesUseridMutationKey = ReturnType<
  typeof patchProjectsIdResponsiblesUseridMutationKey
>;

export function patchProjectsIdResponsiblesUseridMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchProjectsIdResponsiblesUseridMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchProjectsIdResponsiblesUseridMutationKey();
  return mutationOptions<
    PatchProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | PatchProjectsIdResponsiblesUserid401
      | PatchProjectsIdResponsiblesUserid404
    >,
    {
      id: PatchProjectsIdResponsiblesUseridPathParams["id"];
      userId: PatchProjectsIdResponsiblesUseridPathParams["userId"];
      data: PatchProjectsIdResponsiblesUseridMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, userId, data }) => {
      return patchProjectsIdResponsiblesUserid(id, userId, data, config);
    },
  });
}

/**
 * @summary Update the role of a responsible
 * {@link /projects/:id/responsibles/:userId}
 */
export function usePatchProjectsIdResponsiblesUserid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchProjectsIdResponsiblesUseridMutationResponse,
      ResponseErrorConfig<
        | PatchProjectsIdResponsiblesUserid401
        | PatchProjectsIdResponsiblesUserid404
      >,
      {
        id: PatchProjectsIdResponsiblesUseridPathParams["id"];
        userId: PatchProjectsIdResponsiblesUseridPathParams["userId"];
        data: PatchProjectsIdResponsiblesUseridMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchProjectsIdResponsiblesUseridMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    patchProjectsIdResponsiblesUseridMutationKey();

  const baseOptions = patchProjectsIdResponsiblesUseridMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | PatchProjectsIdResponsiblesUserid401
      | PatchProjectsIdResponsiblesUserid404
    >,
    {
      id: PatchProjectsIdResponsiblesUseridPathParams["id"];
      userId: PatchProjectsIdResponsiblesUseridPathParams["userId"];
      data: PatchProjectsIdResponsiblesUseridMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | PatchProjectsIdResponsiblesUserid401
      | PatchProjectsIdResponsiblesUserid404
    >,
    {
      id: PatchProjectsIdResponsiblesUseridPathParams["id"];
      userId: PatchProjectsIdResponsiblesUseridPathParams["userId"];
      data: PatchProjectsIdResponsiblesUseridMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchProjectsIdResponsiblesUseridMutationResponse,
    ResponseErrorConfig<
      | PatchProjectsIdResponsiblesUserid401
      | PatchProjectsIdResponsiblesUserid404
    >,
    {
      id: PatchProjectsIdResponsiblesUseridPathParams["id"];
      userId: PatchProjectsIdResponsiblesUseridPathParams["userId"];
      data: PatchProjectsIdResponsiblesUseridMutationRequest;
    },
    TContext
  >;
}
