/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchProjectsIdBudgetItemsItemidMutationRequest,
  PatchProjectsIdBudgetItemsItemidMutationResponse,
  PatchProjectsIdBudgetItemsItemidPathParams,
  PatchProjectsIdBudgetItemsItemid401,
  PatchProjectsIdBudgetItemsItemid404,
} from "../types/PatchProjectsIdBudgetItemsItemid.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchProjectsIdBudgetItemsItemid } from "../clients/patchProjectsIdBudgetItemsItemid.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchProjectsIdBudgetItemsItemidMutationKey = () =>
  [{ url: "/projects/:id/budget-items/:itemId" }] as const;

export type PatchProjectsIdBudgetItemsItemidMutationKey = ReturnType<
  typeof patchProjectsIdBudgetItemsItemidMutationKey
>;

export function patchProjectsIdBudgetItemsItemidMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchProjectsIdBudgetItemsItemidMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchProjectsIdBudgetItemsItemidMutationKey();
  return mutationOptions<
    PatchProjectsIdBudgetItemsItemidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdBudgetItemsItemid401 | PatchProjectsIdBudgetItemsItemid404
    >,
    {
      id: PatchProjectsIdBudgetItemsItemidPathParams["id"];
      itemId: PatchProjectsIdBudgetItemsItemidPathParams["itemId"];
      data: PatchProjectsIdBudgetItemsItemidMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, itemId, data }) => {
      return patchProjectsIdBudgetItemsItemid(id, itemId, data, config);
    },
  });
}

/**
 * @summary Update a budget item
 * {@link /projects/:id/budget-items/:itemId}
 */
export function usePatchProjectsIdBudgetItemsItemid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchProjectsIdBudgetItemsItemidMutationResponse,
      ResponseErrorConfig<
        | PatchProjectsIdBudgetItemsItemid401
        | PatchProjectsIdBudgetItemsItemid404
      >,
      {
        id: PatchProjectsIdBudgetItemsItemidPathParams["id"];
        itemId: PatchProjectsIdBudgetItemsItemidPathParams["itemId"];
        data: PatchProjectsIdBudgetItemsItemidMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchProjectsIdBudgetItemsItemidMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    patchProjectsIdBudgetItemsItemidMutationKey();

  const baseOptions = patchProjectsIdBudgetItemsItemidMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchProjectsIdBudgetItemsItemidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdBudgetItemsItemid401 | PatchProjectsIdBudgetItemsItemid404
    >,
    {
      id: PatchProjectsIdBudgetItemsItemidPathParams["id"];
      itemId: PatchProjectsIdBudgetItemsItemidPathParams["itemId"];
      data: PatchProjectsIdBudgetItemsItemidMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchProjectsIdBudgetItemsItemidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdBudgetItemsItemid401 | PatchProjectsIdBudgetItemsItemid404
    >,
    {
      id: PatchProjectsIdBudgetItemsItemidPathParams["id"];
      itemId: PatchProjectsIdBudgetItemsItemidPathParams["itemId"];
      data: PatchProjectsIdBudgetItemsItemidMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchProjectsIdBudgetItemsItemidMutationResponse,
    ResponseErrorConfig<
      PatchProjectsIdBudgetItemsItemid401 | PatchProjectsIdBudgetItemsItemid404
    >,
    {
      id: PatchProjectsIdBudgetItemsItemidPathParams["id"];
      itemId: PatchProjectsIdBudgetItemsItemidPathParams["itemId"];
      data: PatchProjectsIdBudgetItemsItemidMutationRequest;
    },
    TContext
  >;
}
