/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostProjectsIdResponsiblesMutationRequest,
  PostProjectsIdResponsiblesMutationResponse,
  PostProjectsIdResponsiblesPathParams,
  PostProjectsIdResponsibles401,
  PostProjectsIdResponsibles404,
} from "../types/PostProjectsIdResponsibles.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postProjectsIdResponsibles } from "../clients/postProjectsIdResponsibles.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postProjectsIdResponsiblesMutationKey = () =>
  [{ url: "/projects/:id/responsibles" }] as const;

export type PostProjectsIdResponsiblesMutationKey = ReturnType<
  typeof postProjectsIdResponsiblesMutationKey
>;

export function postProjectsIdResponsiblesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostProjectsIdResponsiblesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postProjectsIdResponsiblesMutationKey();
  return mutationOptions<
    PostProjectsIdResponsiblesMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404
    >,
    {
      id: PostProjectsIdResponsiblesPathParams["id"];
      data: PostProjectsIdResponsiblesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postProjectsIdResponsibles(id, data, config);
    },
  });
}

/**
 * @summary Add a responsible to a project
 * {@link /projects/:id/responsibles}
 */
export function usePostProjectsIdResponsibles<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProjectsIdResponsiblesMutationResponse,
      ResponseErrorConfig<
        PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404
      >,
      {
        id: PostProjectsIdResponsiblesPathParams["id"];
        data: PostProjectsIdResponsiblesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostProjectsIdResponsiblesMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postProjectsIdResponsiblesMutationKey();

  const baseOptions = postProjectsIdResponsiblesMutationOptions(
    config,
  ) as UseMutationOptions<
    PostProjectsIdResponsiblesMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404
    >,
    {
      id: PostProjectsIdResponsiblesPathParams["id"];
      data: PostProjectsIdResponsiblesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostProjectsIdResponsiblesMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404
    >,
    {
      id: PostProjectsIdResponsiblesPathParams["id"];
      data: PostProjectsIdResponsiblesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostProjectsIdResponsiblesMutationResponse,
    ResponseErrorConfig<
      PostProjectsIdResponsibles401 | PostProjectsIdResponsibles404
    >,
    {
      id: PostProjectsIdResponsiblesPathParams["id"];
      data: PostProjectsIdResponsiblesMutationRequest;
    },
    TContext
  >;
}
