/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostProjectsBulkDeleteMutationRequest,
  PostProjectsBulkDeleteMutationResponse,
  PostProjectsBulkDelete401,
} from "../types/PostProjectsBulkDelete.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postProjectsBulkDelete } from "../clients/postProjectsBulkDelete.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postProjectsBulkDeleteMutationKey = () =>
  [{ url: "/projects/bulk-delete" }] as const;

export type PostProjectsBulkDeleteMutationKey = ReturnType<
  typeof postProjectsBulkDeleteMutationKey
>;

export function postProjectsBulkDeleteMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostProjectsBulkDeleteMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postProjectsBulkDeleteMutationKey();
  return mutationOptions<
    PostProjectsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostProjectsBulkDelete401>,
    { data: PostProjectsBulkDeleteMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postProjectsBulkDelete(data, config);
    },
  });
}

/**
 * @summary Soft-delete multiple projects
 * {@link /projects/bulk-delete}
 */
export function usePostProjectsBulkDelete<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProjectsBulkDeleteMutationResponse,
      ResponseErrorConfig<PostProjectsBulkDelete401>,
      { data: PostProjectsBulkDeleteMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostProjectsBulkDeleteMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postProjectsBulkDeleteMutationKey();

  const baseOptions = postProjectsBulkDeleteMutationOptions(
    config,
  ) as UseMutationOptions<
    PostProjectsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostProjectsBulkDelete401>,
    { data: PostProjectsBulkDeleteMutationRequest },
    TContext
  >;

  return useMutation<
    PostProjectsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostProjectsBulkDelete401>,
    { data: PostProjectsBulkDeleteMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostProjectsBulkDeleteMutationResponse,
    ResponseErrorConfig<PostProjectsBulkDelete401>,
    { data: PostProjectsBulkDeleteMutationRequest },
    TContext
  >;
}
