/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchContactsIdMutationRequest,
  PatchContactsIdMutationResponse,
  PatchContactsIdPathParams,
  PatchContactsId401,
  PatchContactsId404,
} from "../types/PatchContactsId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchContactsId } from "../clients/patchContactsId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchContactsIdMutationKey = () =>
  [{ url: "/contacts/:id" }] as const;

export type PatchContactsIdMutationKey = ReturnType<
  typeof patchContactsIdMutationKey
>;

export function patchContactsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchContactsIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchContactsIdMutationKey();
  return mutationOptions<
    PatchContactsIdMutationResponse,
    ResponseErrorConfig<PatchContactsId401 | PatchContactsId404>,
    {
      id: PatchContactsIdPathParams["id"];
      data: PatchContactsIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchContactsId(id, data, config);
    },
  });
}

/**
 * @summary Update scalar and address fields of a contact
 * {@link /contacts/:id}
 */
export function usePatchContactsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchContactsIdMutationResponse,
      ResponseErrorConfig<PatchContactsId401 | PatchContactsId404>,
      {
        id: PatchContactsIdPathParams["id"];
        data: PatchContactsIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchContactsIdMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchContactsIdMutationKey();

  const baseOptions = patchContactsIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchContactsIdMutationResponse,
    ResponseErrorConfig<PatchContactsId401 | PatchContactsId404>,
    {
      id: PatchContactsIdPathParams["id"];
      data: PatchContactsIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchContactsIdMutationResponse,
    ResponseErrorConfig<PatchContactsId401 | PatchContactsId404>,
    {
      id: PatchContactsIdPathParams["id"];
      data: PatchContactsIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchContactsIdMutationResponse,
    ResponseErrorConfig<PatchContactsId401 | PatchContactsId404>,
    {
      id: PatchContactsIdPathParams["id"];
      data: PatchContactsIdMutationRequest;
    },
    TContext
  >;
}
