/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchContactsIdStateMutationRequest,
  PatchContactsIdStateMutationResponse,
  PatchContactsIdStatePathParams,
  PatchContactsIdState401,
  PatchContactsIdState404,
} from "../types/PatchContactsIdState.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchContactsIdState } from "../clients/patchContactsIdState.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchContactsIdStateMutationKey = () =>
  [{ url: "/contacts/:id/state" }] as const;

export type PatchContactsIdStateMutationKey = ReturnType<
  typeof patchContactsIdStateMutationKey
>;

export function patchContactsIdStateMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchContactsIdStateMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchContactsIdStateMutationKey();
  return mutationOptions<
    PatchContactsIdStateMutationResponse,
    ResponseErrorConfig<PatchContactsIdState401 | PatchContactsIdState404>,
    {
      id: PatchContactsIdStatePathParams["id"];
      data: PatchContactsIdStateMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchContactsIdState(id, data, config);
    },
  });
}

/**
 * @summary Manually change contact pipeline state
 * {@link /contacts/:id/state}
 */
export function usePatchContactsIdState<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchContactsIdStateMutationResponse,
      ResponseErrorConfig<PatchContactsIdState401 | PatchContactsIdState404>,
      {
        id: PatchContactsIdStatePathParams["id"];
        data: PatchContactsIdStateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchContactsIdStateMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchContactsIdStateMutationKey();

  const baseOptions = patchContactsIdStateMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchContactsIdStateMutationResponse,
    ResponseErrorConfig<PatchContactsIdState401 | PatchContactsIdState404>,
    {
      id: PatchContactsIdStatePathParams["id"];
      data: PatchContactsIdStateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchContactsIdStateMutationResponse,
    ResponseErrorConfig<PatchContactsIdState401 | PatchContactsIdState404>,
    {
      id: PatchContactsIdStatePathParams["id"];
      data: PatchContactsIdStateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchContactsIdStateMutationResponse,
    ResponseErrorConfig<PatchContactsIdState401 | PatchContactsIdState404>,
    {
      id: PatchContactsIdStatePathParams["id"];
      data: PatchContactsIdStateMutationRequest;
    },
    TContext
  >;
}
