/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostEnrichmentsMutationRequest,
  PostEnrichmentsMutationResponse,
  PostEnrichments400,
  PostEnrichments401,
  PostEnrichments404,
  PostEnrichments422,
} from "../types/PostEnrichments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/lib/utils/http-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postEnrichments } from "../clients/postEnrichments.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postEnrichmentsMutationKey = () =>
  [{ url: "/enrichments" }] as const;

export type PostEnrichmentsMutationKey = ReturnType<
  typeof postEnrichmentsMutationKey
>;

export function postEnrichmentsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostEnrichmentsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postEnrichmentsMutationKey();
  return mutationOptions<
    PostEnrichmentsMutationResponse,
    ResponseErrorConfig<
      | PostEnrichments400
      | PostEnrichments401
      | PostEnrichments404
      | PostEnrichments422
    >,
    { data: PostEnrichmentsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postEnrichments(data, config);
    },
  });
}

/**
 * @summary Request LLM enrichment for a single contact
 * {@link /enrichments}
 */
export function usePostEnrichments<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostEnrichmentsMutationResponse,
      ResponseErrorConfig<
        | PostEnrichments400
        | PostEnrichments401
        | PostEnrichments404
        | PostEnrichments422
      >,
      { data: PostEnrichmentsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostEnrichmentsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postEnrichmentsMutationKey();

  const baseOptions = postEnrichmentsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostEnrichmentsMutationResponse,
    ResponseErrorConfig<
      | PostEnrichments400
      | PostEnrichments401
      | PostEnrichments404
      | PostEnrichments422
    >,
    { data: PostEnrichmentsMutationRequest },
    TContext
  >;

  return useMutation<
    PostEnrichmentsMutationResponse,
    ResponseErrorConfig<
      | PostEnrichments400
      | PostEnrichments401
      | PostEnrichments404
      | PostEnrichments422
    >,
    { data: PostEnrichmentsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostEnrichmentsMutationResponse,
    ResponseErrorConfig<
      | PostEnrichments400
      | PostEnrichments401
      | PostEnrichments404
      | PostEnrichments422
    >,
    { data: PostEnrichmentsMutationRequest },
    TContext
  >;
}
